### ISSUE TITLE
A book should be able to span multiple genres

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#1]
A book should be able to have multiple genres. 

Suggested implementation:
```java
private Set<Genre> genre;
```

in backend/model/Book.java

**Update**

This is now a backend-only issue (no Vaadin or React is required).

Branch from `0.2.0` and create a branch to back into it.

**Comment by knjk04** [comment]
Possible idea:
Once the user has filled in one author in the field text field on the new book form, a new text field (for a another author) is generated below the original text field. This is then repeated to allow for a user to add multiple authors.

Should there be a hard limit on the number of authors allowed for a given book?

**Comment by knjk04** [comment]
A MultiCombobox could be used in Vaadin. The maven dependency has already been added.

**Comment by knjk04** [comment]
Update: custom components may not be accessible to those without a Vaadin license, so this may need to be removed.

**Comment by knjk04** [comment]
This is blocked for now as predefined shelves should be exclusive. Once new shelves can be added, this issue can become unblocked.

**Comment by kumawatanupriya** [comment]
Is someone working on it or done working?? If not I would like to work on it.

**Comment by knjk04** [comment]
This is available, so I'll you to it. Thanks!

**Comment by kumawatanupriya** [comment]
@knjk04 raised a PR https://github.com/Project-Books/book-project/pull/631 , Please check.
Please comment is something needs to be changed or you would like a different approach.

**Comment by kumawatanupriya** [comment]
Hi @knjk04 created pull request , please check https://github.com/Project-Books/book-project/pull/647
