### ISSUE TITLE
Show congratulationary message for meeting pages goal

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#137]
**Describe the solution you'd like**
Currently, a congratulatory message is shown if the user has met or exceeded their books goal. The same congratulatory message ('Congratulations for reaching your target!') should be shown if the user has met or exceeded their pages goal.

**Additional context**
Class: `GoalView`

**Comment by tjrelyts** [comment]
Hello, I'd like to attempt to contribute to this project and try this issue.

**Comment by knjk04** [comment]
Thanks! If you need any help with this, let us know on Gitter
