### ISSUE TITLE
Translate app into Spanish

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#145]
**Describe the solution you'd like**
Translate the entire web app into Spanish. 

**Additional context**
This includes:
- The page titles
- All Vaadin component placeholders
- All Vaadin button text (e.g. the 'enable dark mode' in the settings page)
- The reading goal
- Predefined shelf names
- Log out link
- All genres
- All column headings in the table
- Login page

See https://vaadin.com/learn/tutorials/i18n

This may be a little tricky, so feel free to ask for help on Gitter

**Comment by eklecky** [comment]
Hi, could you assign me to this issue please?

**Comment by knjk04** [comment]
Sure! Thanks!

**Comment by knjk04** [comment]
It's been a while since we heard back from you with regards to this issue. How are you getting along with this?

**Comment by knjk04** [comment]
As per our contributing document, as we have not heard back from you, I will unassign you from this issue so that someone else can take it up if they so desire.

**Comment by knjk04** [comment]
This issue will be blocked for the time being. It would be better to implement this once we have designed a fully functioning system. Otherwise, we will rely heavily on Spanish translators to merely keep the app fully translated.
