### ISSUE TITLE
Test whether the dark mode toggle works

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#146]
Test whether the dark mode toggle in the settings view works as expected:

- [ ] Test whether turning the switch on turns dark mode on
- [ ] Test whether turning the switch off turns dark mode on
- [ ] Test whether turning the label is set to "Disable dark mode" when dark mode is turned on
- [ ] Test whether turning the label is set to "Enable dark mode" when dark mode is turned off

Slightly trickier but we need to find a way to get this working:
- [ ] Test whether enabling dark mode and then switching pages retains the state of the switch and the label (e.g. if dark mode is enabled and then the user switches to the 'my books' page and then back to settings, the switch should still be 'on' and the label should still show 'disable dark mode')

**Comment by YBrecher** [comment]
Can I be assigned to this issue?

**Comment by knjk04** [comment]
Thanks for your interest. I'm going to block this issue for the time being while I find out whether it is possible to test it.

**Comment by knjk04** [comment]
I've unblocked this, but I'm still not entirely sure whether this will work, but by all means, go ahead and try

**Comment by knjk04** [comment]
Before anyone works on this, they should discuss their implementation approach with us

**Comment by knjk04** [comment]
Removing the 'hacktoberfest' label as we won't be able to get this merged in before the 31st
