### ISSUE TITLE
Extract UI facing text that are local variables to fields

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#166]
All text that is 'UI facing' (i.e. something the user can see in the web app) should be extracted to a `public static final` field. This will make translations (e.g. issue #145) easier later on

**Comment by ZackHollander** [comment]
I would like to take this on. Can you also add me to the slack channel.

**Comment by knjk04** [comment]
Unfortunately, this issue is blocked. Feel free to request to be assigned to an unblocked and unassigned issue.

Here's a Slack invite: https://join.slack.com/t/teambookproject/shared_invite/zt-kss928q8-zT73FmmlV6HmXE1rhourbw
