### ISSUE TITLE
Remove removeId() to create a new database row

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#196]
In the `BaseEntity`, there is a `removeId` method, which is a hack. This should be removed and there should be a better implementation (more details to follow in due course)

**Comment by NyorJa** [comment]
Can I check this?

**Comment by knjk04** [comment]
Sure, thanks. I'll also provide more details on this shortly.

This issue might be tricky, so feel free to reach out to us on our [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-h6vx3n8l-KN8QnO50r7QWZHgHFnFdPw) channel if you need anything

**Comment by NyorJa** [comment]
Please let me know if I have some improvements to be done @knjk04 . Thanks
