### ISSUE TITLE
Unable to add a new book (valid binder)

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#207]
**Describe the bug**

Unable to add a new book when the app. This is despite the binder being valid and a save event having fired.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'my books'
2. Click on 'add book'
3. Fill in any details (including the required fields)

**Expected behaviour**

A book should be added.

**Comment by hgky95** [comment]
Hi @knjk04 
I'm not able to reproduce this issue. It seems like working well. Thanks
![image](https://user-images.githubusercontent.com/33622784/94997983-f9fb4180-05d8-11eb-9ec8-ff05464b59ce.png)

**Comment by knjk04** [comment]
@hgky95 Thanks for this. I'll double-check to see whether I can reproduce it. If not, I'll close the issue (and we can re-open if we are able to reproduce it)
