### ISSUE TITLE
Fix matching books having different IDs

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#208]
In [RatingStatisticsTest](https://github.com/knjk04/book-project/blob/master/src/test/java/com/karankumar/bookproject/backend/statistics/RatingStatisticsTest.java), we test whether two books are equal in the following methods by using their title. Comparing the objects themselves didn't work.

```java
@Test
public void lowestRatedBookExistsAndIsFound() {
    Assertions.assertEquals(bookWithNoRating.getTitle(), ratingStatistics.findLeastLikedBook().getTitle());
}

@Test
public void highestRatedBookExistsAndIsFound() {
    Assertions.assertEquals(bookWithHighestRating.getTitle(), ratingStatistics.findMostLikedBook().getTitle());
}
```

Comparing the two book's ID values also didn't work as the books have different IDs.

This issue involves fixing this problem so that the following line should work in the first case (and similarly for the other method):
```java
Assertions.assertEquals(bookWithNoRating, ratingStatistics.findLeastLikedBook());
```

The `equals()` method has been defined at the BaseEntity level to compare IDs.

**Update: branch from `0.2.0` and create a branch to go back into it.**

Update: note that, as per our style guide, we are using AssertJ assertions now, not JUnit.

**Comment by sumanth-thyagarajan** [comment]
Assign this to me

**Comment by knjk04** [comment]
@sumanth-thyagarajan Apologies, this slipped past me. Sure, I'll assign you to the issue!

**Comment by knjk04** [comment]
@sumanth-thyagarajan 
How are you getting on with this issue? If you need any help on this, feel free to reach out to us on [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-i7lept44-rgJ9yB0A2vedJTLyyfkjKQ)

If you need more time, that's fine, but please let us know.

**Comment by knjk04** [comment]
@sumanth-thyagarajan As we have not heard back from you in a while, despite following up, I will unassign you from the issue

**Comment by celeste2247** [comment]
Hi @knjk04, is there any way I could be assigned to this project?

**Comment by knjk04** [comment]
@celeste2247 Sure, I'll assign you to the issue

**Comment by knjk04** [comment]
@celeste2247 How are you getting on with this? Did you manage to get a chance to see my replies on Slack?

**Comment by knjk04** [comment]
@celeste2247 Unfortunately, as we have not heard back from you in a while, I will unassign you from the issue. This is in line with our contributing guidelines.

**Comment by bemccandless** [comment]
I would say that a book is unique by ISBN, or more collectively Title, Author, and ISBN.  This problem seems to be fixed by updating `@EqualsAndHashCode(callSuper = false, onlyExplicitlyIncluded = true)` and annotating the Title, Author, and ISBN properties with `@EqualsAndHashCode.Include`.  But it depends on what you consider as unique.   If it's imperative that the Id remain unique for a book and thereby use the `callSuper = true`, then it would depend on how the books are being saved, which I didn't look into.

**Comment by knjk04** [comment]
@bemccandless Thanks for your comment! I agree that title, author and ISBN collectively should be considered unique generally speaking. However, in our case, entering an ISBN would be optional for the user, so we still want the ID to be the unique identifier (this maps to a database table where the ID should be autoincremented).

Would you be interested in working on fixing this? If so, I've updated the issue to the 0.2.0 release. In 0.2.0, there's no `BaseEntity` anymore.

**Comment by bemccandless** [comment]
Sorry, I won't be able to take this issue.  I was unable to get version 0.2.0 to start up correctly in my IDE.  I also don't understand this issue and the expected outcome.  The test I added for checking object equality worked without any additional updates to the Book object. 

```
    @Test
    void lowestRatedBookExistsAndIsFound() {
        assertThat(bookWithNoRating).isEqualTo(ratingStatistics.findLeastLikedBook());
    }

    @Test
    void highestRatedBookExistsAndIsFound() {
        assertThat(bookWithHighestRating).isEqualTo(ratingStatistics.findMostLikedBook());
    }

**Comment by knjk04** [comment]
@bemccandless That's fine. I know a few people ran into some SQL issues that were preventing the app from running, but I'm working on fixing that. I'll have a look into this to see whether this is no longer an issue
