### ISSUE TITLE
Add MySQL instructions for Windows 10 in setup section of the README

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#209]
Currently, we note MySQL or Docker as prerequisites for the app (to run the database before running the app).

It may be helpful for future contributors if we list the steps involved in running MySQL in case that person does not want to install Docker.

To keep the README short and succinct, these further setup instructions would be better in the wiki (with a note linking to the page in the README).

**Comment by cuichenli** [comment]
Hi @knjk04 , I was playing around with this project and trying to set up it locally (Pos_os). Following are a few steps I needed to configure the database:
```mysql
# Need a user `dbuser` with password `dbpassword` 
CREATE USER 'dbuser'@'localhost' IDENTIFIED BY 'dbpassword'
# Need a database named `bookproject`
CREATE DATABASE 'bookproject' ;
# The user `dbuser` need permission to database `bookproject` 
GRANT ALL PRIVILEGES ON bookproject.* to 'dbuser'@'localhost';
# The user may need to configure the timezone (at least for my case)
SET GLOBAL time_zone = '+8:00';
```

PS: For the last time zone issue, another resolution is to configure the `application.properties`:
```
# before
spring.datasource.url = jdbc:mysql://localhost:3306/bookproject
# after 
spring.datasource.url = jdbc:mysql://localhost:3306/bookproject?serverTimeZone=UTC
```
https://stackoverflow.com/q/37719818

**Comment by knjk04** [comment]
Thanks for this!

**Comment by knjk04** [comment]
as Docker is our recommended approach
