### ISSUE TITLE
Add new page statistics

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#211]
**Describe the solution you'd like**
Extend the page statistics to include the following:

- Longest book read this year
 - Shortest book read this year
 - Average page length of books read this year

**Additional context**
- Accompanying tests are required

**Comment by anotherfathead** [comment]
I'd like to tackle this issue if it's available.

**Comment by knjk04** [comment]
While we appreciate, as you are new to contributing, I think it's best if you're only to one issue for now (as per our contributing document). 

One reason for this is that it prevents one of the issues being blocked while you work on the other. Meanwhile, someone else could have worked on this.

**Comment by vvkpd** [comment]
I would like work on this card, could you please assign to me.
Thanks

**Comment by knjk04** [comment]
@vvkpd I've noticed that you've already got a couple of pull requests to your name. If this issue is still unassigned, feel free to request it after completing your current pull requests

**Comment by MatusMaliar** [comment]
Hello, i am interested in working on this issue.
Thank you, Matus

**Comment by knjk04** [comment]
@MatusMaliar Thanks, I'll assign you to the issue

**Comment by knjk04** [comment]
@MatusMaliar How are you getting on with this issue? If you need more time, that's fine, but please let us know.

If you need any help on this, feel free to reach out to us on [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-i7lept44-rgJ9yB0A2vedJTLyyfkjKQ)

**Comment by MatusMaliar** [comment]
Hi, i had some trouble setting up the project environment and learning project structure, but im working on the issue and i just need a few more days to finish it properly. 
Matus

**Comment by knjk04** [comment]
That's fine. Thanks for letting us know!

**Comment by MatusMaliar** [comment]
Hello, i finished the issue but i cannot create my own branch where i can push the code for review. Will you create the branch for me or do i have to be added as a collaborator to be able to create my own branch?

Matus

**Comment by knjk04** [comment]
@MatusMaliar 

> but i cannot create my own branch where i can push the code for review.

You should be able to create your own branch. Did you try to create your branch on your fork (and not on this repository)?

I may be able to create a branch for you on your fork (if I have the necessary permissions), but feel free to join our [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-i7lept44-rgJ9yB0A2vedJTLyyfkjKQ) workspace and we can help you further with this.

**Comment by MatusMaliar** [comment]
Thank you, the problem was that i did not create fork before trying to make my own branch. I have commited the changes and made a pull request for your review, let me know if everything is ok.

Matus

**Comment by MatusMaliar** [comment]
Hi, did you get a chance to look into the new PR i uploaded? I hope i fixed all the styling errors.

Thank you. Matus

**Comment by knjk04** [comment]
@MatusMaliar Thanks for creating the PR. We haven't had a chance to look just yet -- during the week, we tend to have less time, so we'll take a look over the weekend. 

There may also be a further delay as we have a backlog of work to get through, but we will get to your PR as soon as we can
