### ISSUE TITLE
Add new rating statistics

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#212]
**Describe the solution you'd like**
Extend the rating statistics to include the following:

- Average rating given to all books this year
- Highest rated book this year
- Lowest rated book this year

**Additional context**
- While Vaadin is required, it should be clear what to do by copying the format of the other statistics

- Accompanying tests are required

**Comment by zhupanovdm** [comment]
Hello, I'm new in open source, could I try with the issue?

**Comment by knjk04** [comment]
Hello, 

Sure, I'll assign you to the issue. Thanks! Let us know on Slack if you need a hand with this

**Comment by knjk04** [comment]
@zhupanovdm How are you getting on with this?

**Comment by knjk04** [comment]
As we have not heard back from you in a while, as per our style guide, we are going to unassign you from this issue

**Comment by AndreaSmetankova** [comment]
Hi, is this issue still open? I'm new in open source and I would like to start with this issue as my first one.

**Comment by knjk04** [comment]
@AndreaSmetankova It is, I'll assign you to this issue. Thanks!

**Comment by knjk04** [comment]
@AndreaSmetankova How are you getting on with this issue? If you need more time, that's fine, but please let us know.

If you need any help on this, feel free to reach out to us on [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-i7lept44-rgJ9yB0A2vedJTLyyfkjKQ)

**Comment by AndreaSmetankova** [comment]
I'm working on it, but I'm new at java and there many other technologies than I'm not familiar with so it probably take some time. 

Thank you for offering help ...I probably use in the near future :)

**Comment by knjk04** [comment]
@AndreaSmetankova No problem, let us know if you need anything
