### ISSUE TITLE
Make Grid use lazy loading

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#216]
**Is your feature request related to a problem? If so, please describe.**
If there are lots of entries in a particular shelf, it may take a while to load all of them into memory at once.

**Describe the solution you'd like**
Use a Data Provider that uses callbacks so that only enough entries to fill the grid 'viewport' are fetched.

**Additional context**
See https://vaadin.com/components/vaadin-grid/java-examples

**Comment by josephkenny** [comment]
May I work on this?

Thanks!

**Comment by knjk04** [comment]
Sure, thanks!

**Comment by knjk04** [comment]
Blocked by #254

**Comment by knjk04** [comment]
Unblocked. #254 has been fixed.

**Comment by GabrielCsik** [comment]
Hello! Could I work on this issue? I'm new here and I would like to contribute. 
Thanks!

**Comment by knjk04** [comment]
@GabrielCsik Sure, thanks!

**Comment by GabrielCsik** [comment]
@knjk04 I accidentally unassigned myself... could you reassign me?

**Comment by knjk04** [comment]
@GabrielCsik I don't think we'll get time to review & merge this in before the end of Hacktoberfest, so I'll remove the label. Are you still interested in working on this?

I know you're waiting for me to look into this to provide some help. If I don't get time today, I may not be able to get back to you until next Sunday.

**Comment by GabrielCsik** [comment]
@knjk04 it's okay, I don't worry about hacktoberfest. I would be happy if we could complete this issue in 2 weeks.

**Comment by GabrielCsik** [comment]
I will try to work on it today as well, so if you have time to look at it today, that would be awesome.

**Comment by knjk04** [comment]
@GabrielCsik Unassigning, as discussed on Slack
