### ISSUE TITLE
Make book title & author search bar

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#217]
**Describe the solution you'd like**
Current filters:
![image](https://user-images.githubusercontent.com/11173328/89703981-f5533d80-d947-11ea-8564-41f5597ed266.png)

Instead, it would be better if we had a search bar that allows a user to search for either a book title or an author's name.

The search bar should be above the 'add book button and take up the width of the left side of the shelf dropdown to the right side of the 'add book' button.

**Update: 24/08/2020. Changed the requirement of this issue, as discussed on Gitter**

**Comment by josephkenny** [comment]
May I work on this?

Thanks!

**Comment by knjk04** [comment]
Sure, thanks!

**Comment by knjk04** [comment]
Before starting this, if you haven't already, you may want to wait until #203 has been merged in as the filters have now moved

**Comment by josephkenny** [comment]
Thanks for the info. I haven't started it yet and will wait until #203 has been merged.

**Comment by knjk04** [comment]
Heads-up: #203 has been merged in just now

**Comment by knjk04** [comment]
I've updated the issue. Let me know if you have any questions
