### ISSUE TITLE
Genre can be both most liked & least liked

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#218]
**Describe the bug**

A genre can be both the most liked and least liked genre at the same time.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'my books'
2. Delete all books in the 'read' shelf
2. Add one book into the 'read' shelf and specify the genre
3. Go to 'statistics'

**Expected behaviour**

The most liked and least liked statistics should not show if there is only one genre present.

**Screenshots**

Only one book, and therefore genre, present.

![image](https://user-images.githubusercontent.com/11173328/89706194-46206180-d95b-11ea-8d23-7ab4030f4eff.png)

Sports genre is both the most liked and least liked genre:
![image](https://user-images.githubusercontent.com/11173328/89706187-343ebe80-d95b-11ea-9ad5-73a9b949ecee.png)

**Comment by tmrd993** [comment]
> **Expected behaviour** 
>
>The genre statistics should not show if there is only one genre present.

So if only 1 genre is present, "Most read", "Most liked" and "Least liked" should be omitted from the stats page?

Because in my opinion, "Most read" has nothing to do with the other fields. For example, if we read 2 books of the same genre, we do not have a "Most liked" or "Least liked" genre, but we do have a "Most read" genre.

Can you clarify this?

**Comment by knjk04** [comment]
Sorry, I should have made the expected behaviour line clearer (in line with the issue title). You're right -- we still want to show the "most read" genre. 

I'll update the issue description. Thanks for pointing this out.

**Comment by MikeLowrie** [comment]
Mind if I pick up this issue?

**Comment by pklink** [comment]
I would like to work on this issue. Can you assign it to me, please?

**Comment by pklink** [comment]
Additionally, this issue should be updated. The genre issue seems to be fixed, but a similar problem is affect the "Most liked book" and "Least liked book" now.

![Screenshot 2020-09-30 23-16-58](https://user-images.githubusercontent.com/753350/94740522-201fa800-0373-11eb-875b-6b65d7cd5f03.png)

**Comment by knjk04** [comment]
Thanks for pointing this out. You're right, this bug seems to be fixed now. I'll close this issue and create a new one for the "Most liked book" and "Least liked book" bug. Feel free to request to be assigned to that
