### ISSUE TITLE
Explore using the Roboto font for the entire app

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#220]
Look into whether the Roboto font looks good on the site. If so, this can be adopted for the entire web app.

**Comment by jacobdadoun** [comment]
Are you referring to the Roboto font?
If so, Are you looking to use Roboto as the standard text throughout the site?

**Comment by knjk04** [comment]
Yes, that's correct. I've updated the issue title to make this clearer.

Yes, we're looking into using Roboto for the entire web app. 

If you're interested, there's a discussion on this over in the Gitter room.

**Comment by knjk04** [comment]
As we'll be using Material UI once we've switched to React, we'll be using Roboto by default
