### ISSUE TITLE
Delete account

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#226]
**Describe the solution you'd like**
Allow a user to delete their account. All information that we have on them, such as their books, are deleted immediately. 

A dialog needs to be presented to the user asking them to confirm and informing them that this irreversible. They should also be informed that they are able to export their books before leaving.

**Addtional context**

- The 'delete account' should appear in the settings page
- The confirmation dialog should be put into the `components` package and be made reusable

- Accompanying tests are also required

**Comment by knjk04** [comment]
Blocked by #140

**Comment by knjk04** [comment]
In the future, we could make the user confirm whether they want to delete their account via email (as an added layer of protection. If a user's Book Project account is hacked, we could verify whether the user really wants to delete their account by sending the account deletion confirmation to their email address).

**Comment by mimarcincin** [comment]
Hello, I would like to do this. Can you assign me?

**Comment by knjk04** [comment]
Sure, I'll assign you to the issue. Thanks!

**Comment by knjk04** [comment]
@mimarcincin 
How are you getting on with this issue? If you need more time, that's fine, but please let us know.

If you need any help on this, feel free to reach out to us on [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-i7lept44-rgJ9yB0A2vedJTLyyfkjKQ)

**Comment by mimarcincin** [comment]
Hello, yes please I will need a few weeks. I will inform you about
everything.
And thanks I will use Slack for sure.

Michal Marcincin

št 15. 10. 2020 o 17:04 Karan Kumar <notifications@github.com> napísal(a):

**Comment by knjk04** [comment]
> yes please I will need a few week

Sure. Unfortunately, I'll have to remove the 'hacktoberfest' label as I don't think we'll get the time to review and merge your PR in before the 31st of October. Hopefully, this is fine. 

Also, could you please provide us with a date of when this will be finished by?

**Comment by knjk04** [comment]
@mimarcincin Just following up -- could you let us know when you will have this finished by?

**Comment by mimarcincin** [comment]
Hello, I'm expecting to finish it by the end of this week. If everything
goes well. :)

ne 1. 11. 2020 o 18:14 Karan Kumar <notifications@github.com> napísal(a):

**Comment by knjk04** [comment]
@mimarcincin Thanks for the update. Could you please open a draft PR so that we can provide early feedback and see how you're getting on?

**Comment by celeste2247** [comment]
Hi @knjk04, I would like to pick up this issue to work on with a friend, is it still open?

**Comment by knjk04** [comment]
Hi @celeste2247, this issue is currently being worked on, but I'll let you know if it becomes available again

**Comment by celeste2247** [comment]
@knjk04, thanks for letting me know!

**Comment by knjk04** [comment]
Relevant 0.2.0 issues exist for this feature
