### ISSUE TITLE
Make system create predefined shelves

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#230]
**Context**

There are 4 Predefined shelves: `to read`, `reading`, `read` and `did not finish`. As the name suggests, these are `predefined` -- in other words, these should be created by the system, not the user. 

```java
    public PredefinedShelf(ShelfName predefinedShelfName) {
        super(predefinedShelfName.toString());
        this.predefinedShelfName = predefinedShelfName;
    }
````

**What needs doing**

The app currently requires the predefined shelves to be manually created. While we create some test data to make the shelves, this approach won't work once we later remove it.

The app should create the shelves by itself. The constructor will need to be private.

**Comment by hgky95** [comment]
Hi @knjk04 
Please assign it to me. Thank you.

**Comment by knjk04** [comment]
@hgky95 Thanks for taking an interest in this. Before I assign you, could you please discuss your implementation approach with us?

**Comment by hgky95** [comment]
> @hgky95 Thanks for taking an interest in this. Before I assign you, could you please discuss your implementation approach with us?

My approach is:
- Defined a fixed `PredefinedShelfs` list with 4 items and we just need create 1 times when the application start.
- Change the constructor  of `PredefinedShelfs` to private.
- Adapt changes.
Thank you.

**Comment by hgky95** [comment]
Hi @knjk04 
Is the approach make sense to you?

**Comment by knjk04** [comment]
@hgky95 Yes, I was just thinking about your first point. How were you thinking of populating the database when the application starts?

**Comment by hgky95** [comment]
@knjk04 Sorry for the late reply. I was busy some days ago.
I might misunderstand the requirement and now I get your idea. So if we want to populate the database when the application starts, we can create a new SQL file and put in the migration folder -> flyway will handle the it.
The file will have the content like:
`INSERT INTO predefined_shelf (id, shelf_name, predefined_shelf_name) VALUES 
(11, 'To read', 0),
(12, 'Reading', 1),
(13, 'Read', 2),
(14, 'Did not finish', 3);`
For sure, we need to adapt to changes in some places.

Besides, I can't join the Slack channel, it seems like it no longer exists. ("To join this workspace, you’ll need to ask the person who originally invited you for a new link.")

**Comment by knjk04** [comment]
@hgky95 Thanks, I'll look into this shortly and get back to you.

Here's an updated Slack invitation (it seems our invitations only last for thirty days): https://join.slack.com/t/teambookproject/shared_invite/zt-i7lept44-rgJ9yB0A2vedJTLyyfkjKQ

**Comment by knjk04** [comment]
@hgky95 Sorry for the delay in getting back to you. Your implementation approach sounds fine.

Unfortunately, if you were to work on this, we may not be able to merge your PR in by the 31st of October, so I'll remove the 'hacktoberfest' label. Would you still be interested in working on this?

**Comment by viniciusrplima** [comment]
Can I work on this issue?

**Comment by danielfrentz** [comment]
Hello, 

Please correct me if I am misunderstanding what you are after, but I'm wondering if the following would satisfy your requirements:

Add a list of shelf names to the application.properties. This would allow users to create a list of any size, although of course it could just be the 4 shelves you have in mind right now.

The code for adding these to the database can be implemented in a method annotation with: @EventListener(ApplicationReadyEvent.class) 

And given that the names have now been defined in the application.properties, each time the application starts it can check which ones have been added, and add any that are missing (which would allow people to add more over time)
