### ISSUE TITLE
Add change password endpoint

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#232]
**Describe the solution you'd like**
It should also be possible for a user to change their password. An endpoint in a controller is required

**Additional context**
As this is a new and important feature, there should be accompanying tests.

**Comment by glegshot** [comment]
@knjk04 is it required a REST based endpoint for password change or a complete end to end feature in the application to enable password change?

**Comment by knjk04** [comment]
This is a backend only change. We'll need an endpoint, but depending on how we decide to implement it, we may also need a service method

**Comment by glegshot** [comment]
@knjk04 to get the password reset,there must be some kind of authentication check to be done.
Either we can go with a secret q&a or generate a password reset link with a token linked to the account which can be sent to the user email.
Let me know your insights on these possibilities.
With the latter approach we will have to establish or lease  a SMTP server which would be an extra added task.

**Comment by knjk04** [comment]
@glegshot I was thinking for this endpoint to be for a user changing their password within the web app after having locked in (so they're already authenticated and have a bearer token).

I'll create another issue for resetting the password. That'll be with a password reset link, as you said

**Comment by glegshot** [comment]
@knjk04 ok,in that case we can go with an API that will accept the current password and the new password as the parameters and then update accordingly the user entry after necessary checks.

**Comment by knjk04** [comment]
@glegshot Yes, let's do that. Are you happy to create an endpoint in a controller class for this? If so, I'll assign you to the issue.

**Comment by kumawatanupriya** [comment]
@knjk04 I would like to work on this issue.

**Comment by knjk04** [comment]
@kumawatanupriya Sure, thanks again!

**Comment by kumawatanupriya** [comment]
@knjk04 please assign this to me.

**Comment by kumawatanupriya** [comment]
@knjk04 created PR https://github.com/Project-Books/book-project/pull/686, please have a look
