### ISSUE TITLE
Add genre filter

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#239]
**Describe the solution you'd like**
Add a Vaadin ComboBox filter that is populated with all of the genres. A user should be able to choose a genre and have the book grid only show results that match the genre chosen.

**Additional context**
This should be similar to our existing filters.

**Comment by knjk04** [comment]
Blocked by #217

**Comment by knjk04** [comment]
![image](https://user-images.githubusercontent.com/11173328/90000852-96affb80-dc88-11ea-9b4f-a79cf02811f0.png)

**Comment by janmaijay1997** [comment]
hi i want to contribute on this project

**Comment by knjk04** [comment]
Hi,

Thanks for your interest! This particular issue is blocked. Any issues that have the blocked label means that we aren't looking to implement them right now. Feel free to suggest working on another (non-blocked) issue, though!
