### ISSUE TITLE
Add book replaces book

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#240]
**Describe the bug**

Adding a book (not updating) sometimes replaces a book instead of adding a new one.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'My books'
2. Click on "Add shelf", create shelf named "test"
3. Refresh page (to make new custom shelf available in book form)
4. Click on 'Add book'
5. Create book named "foo" in shelf "To Read", with secondary shelf "test".
6. "foo" is visible in shelf "To Read".
7. Click on 'Add book'
8. Create book named "bar" in shelf "To Read", with secondary shelf "test".
9. "foo" disappears from shelf "To Read", "bar" is visible in shelf "To Read".

**Expected behaviour**

Adding a book should always add a new entry and never replace an existing book.

**Comment by Tom-private** [comment]
Hi, I was able to reproduce the error:

1. Go to 'My books'
2. Click on "Add shelf", create shelf named "test"
3. refresh page (to make new custom shelf available in book form)

4. Click on 'Add book'
5. Create book named "foo" in shelf "To Read", with secondary shelf "test".
6. "foo" is visible in shelf "To Read".

7. Click on 'Add book'
8. Create book named "bar" in shelf "To Read", with secondary shelf "test".
9. "foo" disappears from shelf "To Read", "bar" is visible in shelf "To Read".

I tried different combinations of primary shelves to add the book to, filled out fields in the book form and using the same or a different name for the new book. **As long as the secondary shelf is the same, the book gets replaced.**

**When a different secondary shelf is chosen, the error does not occur.** Example:

1. Go to 'My books'
2. Click on "Add shelf", create shelf named "test_2"
3. refresh page (to make new custom shelf available in book form)

4. Click on 'Add book'
5. Create book named "foo" in shelf "To Read", with secondary shelf "test".
6. "foo" is visible in shelf "To Read".

7. Click on 'Add book'
8. Create book named "bar" in shelf "To Read", with secondary shelf "test_2".
9. "foo" is still visible in shelf "To Read", "bar" is also visible in shelf "To Read".

This is my first time trying to contribute to an open source project, so I am very open for criticism on what I could improve.
I hope that I was able to help. :)

Kind regards, Tom

**Comment by knjk04** [comment]
Thanks a lot for this, Tom!

**Comment by Tom-private** [comment]
Thank you for your feedback, I am very glad that I was able to help. :)

**Comment by amit1307** [comment]
Hey @knjk04 I am looking for another issue, I can pick this one if it's stil unassigned?

**Comment by knjk04** [comment]
Sure, thanks a lot! That would help a lot!

**Comment by knjk04** [comment]
@amit1307 How are you getting on with this issue?

**Comment by amit1307** [comment]
Hi @knjk04 sorry for the late response. I had a quick look at it and it's not reproducible every time so taking a bit of time. Moreover I couldn't give any time this week but planning to spend some time over the weekend. Hope that's okay.

**Comment by amit1307** [comment]
Hey @knjk04 some update related to this issue:

1. It has nothing to do with secondary shelf. This issue _might_ have existed for long time but not 100% sure.
2. There was some refactoring done in `validateOnSave` method in `BookForm` and that could have made this issue more frequently appearing.
3. The problem is around `setBookBean` is not called every time and due to that the binder may not contain the new book data.
4. The underlying problem is when we add the second book it's not coming with id as null and due to that the JPA repo is considering it as a merge on the previous book instead of new book.
4. I have tested this by changing the `validateOnSave` from existing implementation:

```
    private void validateOnSave() {
        if (binder.isValid()) {
            LOGGER.log(Level.INFO, "Valid binder");
            if (binder.getBean() == null) {
                LOGGER.log(Level.SEVERE, "Binder book bean is null");
                setBookBean();
            } else {
                LOGGER.log(Level.INFO, "Binder.getBean() is not null");
                moveBookToDifferentShelf();
                fireEvent(new SaveEvent(this, binder.getBean()));
                closeForm();
            }
        } else {
            LOGGER.log(Level.SEVERE, "Invalid binder");
        }
    }
```

to 

    private void validateOnSave() {
        if (binder.isValid()) {
            LOGGER.log(Level.INFO, "Valid binder");
            setBookBean();
            if (binder.getBean() != null) {
                LOGGER.log(Level.INFO, "Binder.getBean() is not null");
                moveBookToDifferentShelf();
                fireEvent(new SaveEvent(this, binder.getBean()));
                closeForm();
            }
        } else {
            LOGGER.log(Level.SEVERE, "Invalid binder");
        }
    }

and the issue gets fixed. But just wanted to check with you since you did that refactoring in case if you see anything wrong with this change?

**Comment by knjk04** [comment]
Thanks a lot for this, @amit1307. 

Is it still possible to move a book to a different shelf with this change? I don't know I would have done that, but my guess would be as a hack to get a book to move to a different shelf.

**Comment by amit1307** [comment]
I'll test that and get back shortly.

**Comment by amit1307** [comment]
Yes the change I suggested was breaking the move to different shelf functionality. But I have got another fix which would take care of both the issues. I shall raise the PR by tomorrow.

**Comment by knjk04** [comment]
Great, thanks
