### ISSUE TITLE
Custom shelf is required

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#245]
**Describe the bug**

The Book form requires a custom shelf to be specified.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'my books'
2. Click on 'add book'
3. Enter in only the necessary book details for a book on the 'to read' shelf (i.e. leave the custom shelf field blank)

**Expected behaviour**

As the custom shelf is optional, there should not a form error if a custom shelf is not provided.

**Screenshots**

![image](https://user-images.githubusercontent.com/11173328/90155154-e7a41a80-dd82-11ea-82fb-eb54cccaa919.png)

**Comment by joshiswarali** [comment]
hey @knjk04 , is this up for grabs?

**Comment by joshiswarali** [comment]
I am trying to foray into open source contribution, so would be nice to work on this as a first issue

**Comment by knjk04** [comment]
Blocked by #254

**Comment by c99SRS** [comment]
Hi @knjk04 , Can I work on this, please?

**Comment by knjk04** [comment]
Sure, I'll assign you to the issue. Thanks!

**Comment by knjk04** [comment]
@c99SRS 
How are you getting on with this issue? If you need more time, that's fine, but please let us know.

If you need any help on this, feel free to reach out to us on [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-i7lept44-rgJ9yB0A2vedJTLyyfkjKQ)

**Comment by c99SRS** [comment]
Hi @knjk04 , I had a few issues with setting up the project. I fixed that one. Currently, I am investigating the issue. I think I need a little bit more time.

**Comment by knjk04** [comment]
@c99SRS Thanks for the update. Could you please provide us with a date of when this will be completed by? As this is a high priority bug, we need to complete this quickly.

Also, as we're nearing the end of the month, I think it's unlikely we'll be able to review & merge your PR before the 31st of October. I'll remove the 'hacktoberfest' label. Hopefully, you are fine with this, but please let us know if not

**Comment by c99SRS** [comment]
> @c99SRS Thanks for the update. Could you please provide us with a date of when this will be completed by? As this is a high priority bug, we need to complete this quickly.
> 
> Also, as we're nearing the end of the month, I think it's unlikely we'll be able to review & merge your PR before the 31st of October. I'll remove the 'hacktoberfest' label. Hopefully, you are fine with this, but please let us know if not

Hey @knjk04 , I was caught up with other works. I am okay with the removal of the label. Today I will try my best.

**Comment by knjk04** [comment]
Removing the `@NonNull` annotation in `Shelf` does not work
