### ISSUE TITLE
Duplicate custom shelves showing

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#246]
**Describe the bug**

The shelf list currently shows duplicate custom shelves

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

There should only be one shelf with a given name (and this should be case-sensitive). 

**Screenshots**

![image](https://user-images.githubusercontent.com/11173328/90155520-55504680-dd83-11ea-953d-2257d5408be2.png)

---
Requires reproduction steps to be filled in

**Comment by tw-ayush** [comment]
@knjk04 do you want this to be unique in DB and a handling on code side?

**Comment by knjk04** [comment]
@tw-ayush Yes, there should no custom shelves with duplicate names (case insensitive)

**Comment by tw-ayush** [comment]
okay, i guess you can assign this to me, I'll add some constraints.

**Comment by tw-ayush** [comment]
@knjk04 ??

**Comment by knjk04** [comment]
@tw-ayush Apologies for the delay in getting back to you. I wanted us to review your existing PR first as, in line with our contributing guidelines, we only assign one issue at a time to new contributors. 

Also, I'll temporarily block this issue until more information has been provided (e.g. the exact reproduction steps). If you're able to reproduce this, then feel free to let us know the steps.

Also, I don't know if you're on our Slack workspace, but I've made a couple of announcements recently about delays in reviewing PRs and reponding to messages. There's a backlog of work and things to do right now, so there may be a delay in getting back to you.

**Comment by Kapileson** [comment]
Hi, I would like to work on this issue. Could you assign me?

**Comment by knjk04** [comment]
@Kapileson Sorry, this issue is temporarily blocked. If @tw-ayush does not take this up, then I can assign it to you

**Comment by tw-ayush** [comment]
@knjk04 i'd like to take this one but you still haven't reviewed my PR I guess.

**Comment by knjk04** [comment]
@tw-ayush I'm extremely sorry for the delay. I asked someone else to take a look, but they didn't respond, so I was waiting on them. I'll review it myself today

**Comment by knjk04** [comment]
@tw-ayush I'll assign you to this issue

**Comment by tw-ayush** [comment]
> @tw-ayush I'll assign you to this issue

hey thanks for the update i'll look into this 😄

**Comment by tw-ayush** [comment]
@knjk04 hey while working on this i came across a problem, So my question is based on the SQL migration i believe each user has their own shelf/shelve, and that shelf for a user has to be unique so the constraint should be like unique(user, shelf_name) or am i getting this wrong?

**Comment by knjk04** [comment]
@tw-ayush Sorry for the delay in getting back to you. I think you're right.

@amit1307 Could you please confirm ^?

**Comment by tw-ayush** [comment]
@knjk04 before changing the code i'll wait for confirmation from @amit1307 .

**Comment by amit1307** [comment]
>that shelf for a user has to be unique so the constraint should be like unique(user, shelf_name)

That sounds about right to me but I have a question related to this issue: do we know the reason for the duplicate shelves being added? Do we plan to stop that just by adding the DB constraint?

**Comment by knjk04** [comment]
@tw-ayush How are you getting on with this? When you get a chance, could you please reply to Amit's comment?

**Comment by tw-ayush** [comment]
Hey @amit1307 sorry for the delay, I've not been able to get back to you due to some personal work, but last when i tried i was unable to run the code because of migration issues and i'm unable to debug it.

**Comment by knjk04** [comment]
@tw-ayush Feel free to reach out to us on the #help channel on Slack if you need a hand with that. This sounds like a Flyway issue

**Comment by knjk04** [comment]
@tw-ayush How are you getting on with this issue? If you need any help on this, feel free to reach out to us on Slack

If you need more time, that's fine, but please let us know.

**Comment by knjk04** [comment]
Unassigning at your request on Slack

**Comment by knjk04** [comment]
@Kapileson Are you still interested in working on this issue?

**Comment by shubhamsinghrathi** [comment]
Hi @knjk04 , I want to work on this issue. Can you assign it to me?

**Comment by knjk04** [comment]
@shubhamsinghrathi Sure, thanks
