### ISSUE TITLE
Add button (book form) not initially greyed out

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#252]
**Describe the bug**

The 'add book' button is not initially greyed out when the book form is first opened.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'my books'
2. Click on 'add book'
3. See error

**Expected behaviour**

The 'add book' button should be greyed out initially as the required fields have not yet been filled in.

**Screenshots**

![image](https://user-images.githubusercontent.com/11173328/90281385-61600500-de64-11ea-9102-7ca795810fb9.png)

**Additional context**

Add any other context about the problem here (e.g. stack trace, branch name, commit hash, etc.).

**Comment by wesleynepo** [comment]
Can I do this?

**Comment by sumanth-thyagarajan** [comment]
Can you assign this to me

**Comment by knjk04** [comment]
Unfortunately, as per our [contributing guidelines](https://github.com/Project-Books/book-project/blob/master/CONTRIBUTING.md#new-contributors-assigned-to-at-most-one-issue-at-a-time), we only assign one issue at a time to new contributors.

Feel free to request to be assigned to this after completing your assigned issue if this issue is still available

**Comment by shubhamgoel9** [comment]
i want to work on this issue

**Comment by lindnc5** [comment]
Hey can I work on this?

**Comment by knjk04** [comment]
Hey, sure, I'll assign you to the issue. Thanks!

If you need anything, feel free to get in touch with us over [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-h6vx3n8l-KN8QnO50r7QWZHgHFnFdPw)
