### ISSUE TITLE
Test containsBookTitle

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#256]
The following method should be tested:
```java
private boolean containsBookTitle(Book book) {
     return isBookTitleNull() || book.getTitle()
                                                   .toLowerCase()
                                                   .contains(bookTitle.toLowerCase());
```

One problem with this method is that it does not seem from the method name that it should return true if the book title is null.

**Comment by knjk04** [comment]
We should ensure that:
- When the title of the book passed in matches the title of the field title (`bookTitle`), this method returns true
- It returns false when there isn't a match
- The check for the match is case sensitive 

(I say 'match', but we want to continue to use 'contains')

I'll need to double-check the null part. My initial assumption is that it needs to return `true` for the filter to work. If so, then you're right -- we should rename the method to make this explicit that the `null` check is also carried out

**Comment by pnpninja** [comment]
@knjk04 can i work on this?

**Comment by knjk04** [comment]
@pnpninja Thanks for taking an interest in this. Let me first double-check the null part. Then, I'll unblock this and assign it to you
