### ISSUE TITLE
Set an upper limit for the number of pages & pages read fields

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#258]
**Is your feature request related to a problem? If so, please describe.**
Currently, a book can have at most 2,147,483,647 pages (the maximum value for a Java `int`). 

**Describe the solution you'd like**
This does not seem reasonable, so an upper limit of 23,000 pages should be set (this is slightly higher than the current longest book, according to Wikipedia: https://en.wikipedia.org/wiki/List_of_longest_novels)

**Additional context**
A test is required.

**Comment by knjk04** [comment]
How are you getting on with this issue?

**Comment by prabhjot018** [comment]
Hey I am getting this error while pushing my code `remote: Permission to knjk04/book-project.git denied to prabhjot018.
fatal: unable to access 'https://github.com/knjk04/book-project.git/': The requested URL returned error: 403`

**Comment by knjk04** [comment]
Did you fork the repository and create a new branch? This may be happening because you don't have access to push directly to the repository

**Comment by prabhjot018** [comment]
sorry I forgot to fork and created a branch directly from master,  I have created a PR please have a look

**Comment by knjk04** [comment]
Thanks, I'll take a look shortly
