### ISSUE TITLE
Not able to add book

### ISSUE THREAD

**Issue by amit1307** [Project-Books/book-project#267]
**Not able to add book, Add Book button does not get enabled**

When I try to add a new book by providing all the mandatory details, the Add Book button still stays disabled.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to home page and click add book
2. Enter all the required fields
3. Add Book button stays disabled

**Expected behaviour**

Should be able to save a book when all the required details are provided

**Screenshots**

![image](https://user-images.githubusercontent.com/23420222/90863374-d2cd1580-e386-11ea-8d50-08517701e33a.png)

**Comment by knjk04** [comment]
Thanks for raising this. I think this is due to #245. Could you try to first add a custom shelf and then specify the custom shelf (the secondary shelf field)? Let us know whether this works.

The problem is that the secondary shelf (custom shelf) field is currently required (although, it should not be).

**Comment by amit1307** [comment]
Just tried as per the suggestion and can see below behaviour:
1. Added a custom shelf 'test'
2. The shelf 'test' is not available to pick for secondary shelf, actually there is no shelf available for secondary shelf selection.
3. I tried entering the shelf name as test for secondary shelf but as soon as I move out of the secondary shelf, it erases the value I entered manually.
4. Add Book button not enabled.

**Comment by amit1307** [comment]
Yes that's the issue for me, refreshing the page shows the secondary shelf available and after selecting secondary shelf it works fine.

**Comment by knjk04** [comment]
@amit1307 Oh, my bad. Even after rebasing?

**Comment by amit1307** [comment]
yes I had rebased my master before testing this issue which was 3 days ago. If the issue has been fixed in last 3 days I can try again?

**Comment by knjk04** [comment]
@amit1307 I think so, could you try again?

**Comment by knjk04** [comment]
@amit1307 Have you been able to test this on the latest version of master?

**Comment by amit1307** [comment]
Sorry for the delay, have just tested it on the latest version and the issue still persists. Tried below steps:

1. Add a new shelf 'testshelf'.
2. Click on Add Book and the newly added secondary shelf 'testshelf' doesn't appear. It appears if the page is refreshed.
3. Another issue related to this i guess: without refreshing the page not able to add new shelf. Save button on Add secondary shelf stays greyed out until refresh the page.

Please let me know if any other information is needed.

**Comment by knjk04** [comment]
Thanks for the information. Could you please create a new issue for needing to refresh? That would help a lot

**Comment by amit1307** [comment]
https://github.com/knjk04/book-project/issues/319

**Comment by StanislavFranko** [comment]
Is this issue still available?

**Comment by knjk04** [comment]
@StanislavFranko Sorry, I haven't been able to reproduce this. I'll block this until I'm able to do so
