### ISSUE TITLE
Add SonarQube to Docker container

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#270]
Add SonarQube to the Docker container so that a SonarQube server can start when the docker container is started.

Since a developer may not always want SonarQube, this should only run in a separate testing container (perhaps).

**Comment by inhundreds** [comment]
Hello Karan, can you give some additional info about this? AFAIK SonarQube is for static code analysis. Why add it to the docker container that runs the app?

Thanks,
Diego

**Comment by knjk04** [comment]
Hello Diego,

I think that it may be easier to run SonarQube for the app if we add it to a Docker container so that anyone working on the code does not need to run it locally.

Also, I thought that it should perhaps run in a separate container rather than the one used to run the app to prevent the docker container that runs the app from becoming too big and slow.

I'm new to both Docker & SonarQube, so this could be a silly idea. Let me know what you think.

**Comment by inhundreds** [comment]
Ok, now I understand. Can I try to work on this?

Thanks,
Diego

**Comment by knjk04** [comment]
Sure, thanks!

**Comment by inhundreds** [comment]
I easily started a SonarQube server in a docker container and launched a code analysis job with Maven. You can see the results in this screenshot ![screenshot](https://user-images.githubusercontent.com/3390875/92512250-ce21b180-f20e-11ea-8f37-ac39f8649e2a.jpg)

SonarQube saves into a db the issues it has found during its analysis. It also allows you to assign issues to users and allows them to manage each issue's workflow. This is only possible with a shared instance of the server and its database. But we can't have those with a local docker container. In addition to this, the SonarQube Community edition has no integration with GitHub.  

We can, instead, use SonarCloud that is free for public projects, can be integrated with GitHub and with Travis CI. 

What do you think? It makes sense to you?

**Comment by knjk04** [comment]
Sorry, this slipped past me.

Thanks for bringing this up. Yes, that makes sense. Thanks for bringing this up. I'm new to SonarQube, so I didn't realise there was a cloud solution!
