### ISSUE TITLE
Verify email address

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#278]
**Is your feature request related to a problem? If so, please describe.**
A user can enter an email address that doesn't belong to them (intentionally or not). 

**Describe the solution you'd like**
Verify a user's email address by sending a confirmation code to the user that they have to paste into our web app. This should be required for all accounts that have an email address.

A free, secure third-party should be used. Ideally, this would be open-source. Before implementing this issue, please discuss with us any viable options you find.

**Additional context**
In the future, we could extend this to include a confirmation link that the user can click to verify their email address in addition to the code.

**Comment by tw-ayush** [comment]
@knjk04 this could rather be broken into 2 smaller tasks, implementing a mailing service which accepts a mail template and another one can be integration.

also having a mailing service/ class little close to generic will be more useful from scalability prospective. (for start take the complete message as a string parameter)

**Comment by knjk04** [comment]
@tw-ayush Thanks for your suggestion. We'll review this closer to when we are thinking of implementing this (which may be some time)

**Comment by comnk** [comment]
Is this issue available?

**Comment by knjk04** [comment]
Unfortunately not. This is already assigned

**Comment by Kordedekehine** [comment]
Do you know if it has been implemented? If so, the issue should be closed.

**Comment by knjk04** [comment]
@Kordedekehine It hasn't, but I will be archiving the project due to a lack of time to maintain it
