### ISSUE TITLE
Change email address

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#280]
**Is your feature request related to a problem? If so, please describe.**
A user cannot currently change the email address they signed up with.

**Describe the solution you'd like**
Create a new endpoint that allows us to change their email address. We should re-authenticate to handle the time of check to time of use issue (TOCTOU).

**Additional context**
Branch from `0.2.0`. When you're ready, create a pull request with `0.2.0` as the destination branch 

(Once #278 is implemented, we should also send a verification code to the new email address)

**Comment by knjk04** [comment]
Blocked by #278

**Comment by SeonghoLee4** [comment]
I would like to be assigned to this issue.

**Comment by knjk04** [comment]
@SeonghoLee4 Thanks!

**Comment by knjk04** [comment]
@SeonghoLee4 How are you getting on with this?

**Comment by knjk04** [comment]
Unfortunately, as we have not heard back from you in a while, I will unassign you from the issue. This is in line with our contributing guidelines.

**Comment by knjk04** [comment]
@SeonghoLee4 How are you getting on with this?

**Comment by knjk04** [comment]
@SeonghoLee4 Unfortunately, as we have not heard back from you in a while, I will unassign you from the issue. This is in line with our contributing guidelines.

**Comment by ZackHollander** [comment]
Can I take this?

**Comment by knjk04** [comment]
@SeonghoLee4 At your request, I'll reassign you the issue. As discussed, please feel free to reach out for any help required. We're more than happy to assist

**Comment by knjk04** [comment]
@ZackHollander Are you interested in #667, instead?

**Comment by cmadhumita5** [comment]
I want to work on it.

**Comment by knjk04** [comment]
@cmadhumita5 This issue is also taken. Please also note that, as per our contributing guidelines, we only assign at most one issue to new contributors

**Comment by knjk04** [comment]
@SeonghoLee4 As we have not heard back from you in a while, despite following up, I've unassigned you from the issue

**Comment by Stevade-stephen** [comment]
I want to work on this issue

**Comment by knjk04** [comment]
@Stevade-stephen Thanks, I'll assign you to it

**Comment by Stevade-stephen** [comment]
Thanks

**Comment by knjk04** [comment]
@Stevade-stephen How are you getting on with this?

**Comment by Stevade-stephen** [comment]
I'm still working on it. I will let you know when I have questions.

**Comment by knjk04** [comment]
OK, do you know when you'll have this finished?

**Comment by Stevade-stephen** [comment]
I am trying to push to a branch I created and it is telling me that I do not have access rights.
![Screen Shot 2021-07-23 at 2 50 28 AM](https://user-images.githubusercontent.com/75506167/126728956-96fd743a-e379-4620-bf3a-d0dbe818bebd.png)

**Comment by knjk04** [comment]
Are you trying to push to your fork or the cloned repository? Only the former should work

**Comment by Stevade-stephen** [comment]
Oh! I cloned it.

**Comment by knjk04** [comment]
@Stevade-stephen How are you getting on with this?

**Comment by knjk04** [comment]
@Stevade-stephen Unassigning as we haven't heard back from you in a while (as per our contributing guidelines)

**Comment by knjk04** [comment]
@adrianbranescu You can test this manually by checking the database after hitting the endpoint

**Comment by knjk04** [comment]
@adrianbranescu How are you getting on with this?

**Comment by adrianbranescu** [comment]
@knjk04 Hello. I answered you on Slack.
