### ISSUE TITLE
Set an upper limit to maximum user password length

### ISSUE THREAD

**Issue by tmrd993** [Project-Books/book-project#281]
The password strength measuring added to resolve issue https://github.com/knjk04/book-project/issues/262 slows down considerably for very long passwords.

Measuring a 128 character password takes ~500ms.
Measuring a 512 character password takes ~3000ms

This could be used for denial of service attacks when using extremely long passwords.

**to reproduce:**
1. click on "register user"
2. fill out password field

The password length should be limited to a maximum of 100-128 characters.

**Comment by knjk04** [comment]
Thanks for bringing this up!

**Comment by MikeLowrie** [comment]
Mind if I pick this up?

**Comment by knjk04** [comment]
Not at all, thanks!
