### ISSUE TITLE
Create Integration Test for Docker build 

### ISSUE THREAD

**Issue by gm7y8** [Project-Books/book-project#289]
**Is your feature request related to a problem? If so, please describe.**
Create Integration Test for Docker build 

**Describe the solution you'd like**
It Helps to test container-related changes are not broken

**Comment by knjk04** [comment]
Thanks for creating this issue!

**Comment by knjk04** [comment]
If you're interested, there's another Docker issue: #270

**Comment by knjk04** [comment]
How are you getting on with this issue?

**Comment by knjk04** [comment]
Hi @gm7y8, as per our [contributing guidelines](https://github.com/Project-Books/book-project/blob/master/CONTRIBUTING.md), as we have not heard back from you after following up, we are going to unassign you from this issue to open it up to someone else.
