### ISSUE TITLE
Docker compose build support for windows

### ISSUE THREAD

**Issue by gm7y8** [Project-Books/book-project#290]
**Is your feature request related to a problem? If so, please describe.**
Make Docker compose build to support Windows. 

**Describe the solution you'd like**

**Additional context**

**Comment by knjk04** [comment]
Thanks for creating this issue and offering to work on it!

**Comment by knjk04** [comment]
How are you getting on with this issue?

**Comment by knjk04** [comment]
As you may have seen on our Gitter group chat, we've moved the repository from my personal account to an organisation. Could you update the remote for your local fork, please?

$ git remote set-url origin https://github.com/Project-Books/book-project

**Comment by gm7y8** [comment]
@knjk04 sorry was little busy.. just sent PR for this enhancement.. I don't have windows machine to test.. can you help me with the testing.. you just need to change the path in the env file or docker compose file to path jar file is kept after build. try running the docker build.

**Comment by knjk04** [comment]
Sure, I'll test it shortly
