### ISSUE TITLE
Identify areas to add tests

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#294]
This issue is to do with suggesting areas where we could improve our test coverage. As such, no-one will be assigned to this issue. Feel free to suggest as many areas (e.g. methods or a specific functionality) that we should test. New issues will be created for these test suggestions if we're happy to proceed. If you would like to be assigned to implementing some tests, feel free to request to be assigned to the new issue. 

**What we want**

Our current test coverage (71% at the time of writing) is too low. We want to get as close to 100% as possible. In an ideal world, we would find all bugs through failing tests.

**Additional context**

Our [codecov test coverage report](https://codecov.io/gh/knjk04/book-project)

**Comment by NyorJa** [comment]
Hi,

Can I check this?

**Comment by knjk04** [comment]
Sure, so with this particular issue, anyone is free to suggest areas to add tests as comments. We can then create issues if we're happy to proceed with the suggestions. You, or anyone else, can then request to be assigned to a particular issue

**Comment by knjk04** [comment]
Closing as it's better to create specific issues for tests to complete
