### ISSUE TITLE
Rename custom shelf

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#296]
**Is your feature request related to a problem? If so, please describe.**
Once issue #237 is implemented, the only way to rename a custom shelf would be to delete it and then create a new one. Aside from being tedious, this also means that a user would have to go back and add all of the books to that shelf.

**Describe the solution you'd like**
Allow for a shelf to be renamed. 

As before, the name of the custom shelf must not be the same name as the name of a predefined shelf or an existing custom shelf. Case insensitive checks should be carried out.

**Additional context**

A test(s) is also required

**Comment by knjk04** [comment]
Blocked by #237

**Comment by MikeLowrie** [comment]
This was solved as part of #342. Once that is merged, this should be marked as solved.
