### ISSUE TITLE
Test isPredefinedShelf()

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#298]
Test the isPredefinedShelf() method in PredefinedShelfUtils.

Some ideas for things to test:

- True is returned when the method takes the name of a predefined shelf as a string (test all of the predefined shelves -- perhaps a parameterized test would be good here)
- False is returned when the method takes the name of a non-predefined shelf
- True is returned when the method takes the name of a predefined shelf that is either all in uppercase, all in lowercase, etc.

**Comment by mlehotsky13** [comment]
I can take this.

**Comment by knjk04** [comment]
Sure, thanks for offering!

**Comment by mlehotsky13** [comment]
PR open, check the description.

**Comment by knjk04** [comment]
Excellent, I'll take a look shortly
