### ISSUE TITLE
Test getPredefinedShelfNamesAsStrings()

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#299]
Test that `getPredefinedShelfNamesAsStrings()` only returns all of the names of all predefined shelves (see the `ShelfName` enum in `PredefinedShelf`).

**Comment by hgky95** [comment]
Hi @knjk04 
I'd like to take this one. Please assign it to me.
Thank you.

**Comment by knjk04** [comment]
Sure, I'll assign you to the issue. Thank you!

**Comment by knjk04** [comment]
Also, if you need a hand with this, feel free to get in touch with us over [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-h6vx3n8l-KN8QnO50r7QWZHgHFnFdPw)

**Comment by hgky95** [comment]
@knjk04  Yes, I'm fined with this issue. Currently I'm in the working time so I'm not able to create the PR. Anyway, I will join the Slack channel.
Thank for your suggestion.
