### ISSUE TITLE
Make BookGrid fill the entire page

### ISSUE THREAD

**Issue by Tom-private** [Project-Books/book-project#301]
**BookGrid is not utilizing the page height**

When a shelf contains more than 9 books, the book grid shows them in a list with a scroll bar although there is enough space on the page left to show them without the need for scrolling.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add multiple books to a shelf so that it contains at least 10
2. Select the shelf you added the books to in the "choose shelf" combobox
3. See error

**Expected behaviour**

The grid should make use of the whole height of the page instead of displaying a scroll bar. 

**Screenshots**
Much space left below the grid:
![image](https://user-images.githubusercontent.com/58065733/92081737-d4093400-edc3-11ea-8063-8308068fc45a.png)

**Comment by knjk04** [comment]
Thanks for bringing this up. This is actually expected behaviour, but I agree with you that it doesn't make much sense

**Comment by killerkc12** [comment]
I like to make entire page grid

**Comment by knjk04** [comment]
Sure, I'll assign you to the issue. Thanks!

**Comment by knjk04** [comment]
If you need a hand with this, feel free to get in touch with us over [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-h6vx3n8l-KN8QnO50r7QWZHgHFnFdPw)

**Comment by killerkc12** [comment]
Thank you ! Yes i like to be in touch if I get any shit
