### ISSUE TITLE
Add instructions how to work on frontend

### ISSUE THREAD

**Issue by tomglk** [Project-Books/book-project#305]
**Is your feature request related to a problem? If so, please describe.**
I had a lot of trouble when trying to work on the frontend after building the app with maven. After much trial and error I figured out, that I had to delete the target folder that maven generated.

**Describe the solution you'd like**
There should be a section in the readme that describes how to work on the frontend, respectively what to do when encountering the problem, that the new css does not appear after the app was built.

Something like this:
When the app was build with mvn clean package -Pproduction (-> target folder was generated) and you change something in the css, nothing will happen!
You have to delete the target folder.
When the app is started by pressing "play" in intelliJ, a new target folder will be generated. You do not have to delete this one to be able to see changes to the frontend, just restart the app.

**Comment by knjk04** [comment]
Did you see a message that Vaadin reload was not working? If so, this may be the issue

**Comment by knjk04** [comment]
I've just tried this now. It should work if you press the build button (at least of the latest commit)

**Comment by Tom-private** [comment]
I investigated a bit:
``` mvn clean package -Pproduction``` & ```docker-compose up mysql phpmyadmin```:
- start app in IntelliJ
- stop & change css
- start again
→no change
- stop
- click "build project"
- start again
→still no change

``` mvn clean install``` & ```docker-compose up mysql phpmyadmin```:
- start app in IntelliJ
- stop & change css
- start again
→change
- stop
- click "build project"
- start again
→also change

So it was my fault for using the wrong command. But from the description I thought it wouldn't matter. (In hindsight, "production mode" might should have rang a bell.)

**Comment by knjk04** [comment]
Sorry for the slow reply, I missed this.

Thanks for bringing this up. I've added `phpmyadmin` for the non-prod setup. I can look again, but I thought the production build already loaded `phpyadmin`?
