### ISSUE TITLE
Test field reset

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#309]
In `ComponentsUtil`, we have a utility method that clears all passed in components. Write a test to ensure that all fields are correctly reset.

**Comment by vvkpd** [comment]
I wanted to pick this card, please let me know.

**Comment by killerkc12** [comment]
I like to catch it up

**Comment by knjk04** [comment]
Thanks, @vvkpd. I'll assign you to the issue

**Comment by knjk04** [comment]
Apologies once again, @killerkc12. I'd recommend only asking on issues where someone else hasn't already expressed an interest (and that's unassigned and unblocked) to avoid future disappointment
