### ISSUE TITLE
Fix failing DateUtil tests

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#311]
The following tests are failing with `mvn clean install`:
- [ERROR]   DateUtilsTest.testCurrentWeekNumberOfYearAndWeeksLeftInYear:57 expected: <1> but was: <43>
- [ERROR]   DateUtilsTest.testWeeksLeftInYearFromCurrentWeek:65 expected: <51> but was: <0>

**Comment by tmrd993** [comment]
May I work on this?

**Comment by knjk04** [comment]
This appears to be an issue with Mockito not mocking as intended

**Comment by wesleynepo** [comment]
I'm trying to reproduce but none of the tests is failing here. 
`[INFO] Running com.karankumar.bookproject.backend.utils.DateUtilsTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.311 s - in com.karankumar.bookproject.backend.utils.DateUtilsTest
`

**Comment by knjk04** [comment]
Thanks for this. Which OS and JDK (Oracle, OpenJDK, etc.) are you using? Also, what's the version number of the Java JDK you're using?

**Comment by wesleynepo** [comment]
`openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)
`
Maven: 
`Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/maven
Java version: 11.0.8, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-47-generic", arch: "amd64", family: "unix"
`

**Comment by tmrd993** [comment]
I can't reproduce the issue either. Oddly enough, I worked on this a few weeks ago and back then the tests did fail.

> 
> 
> This appears to be an issue with Mockito not mocking as intended

Static method mocking is relatively new in Mockito right? Might be worth looking into [Powermock](https://github.com/powermock/powermock) which is often used for this.

**Comment by knjk04** [comment]
> 
> 
> Ubuntu 20.04
> 
> `openjdk 11.0.8 2020-07-14 OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu120.04) OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu120.04, mixed mode, sharing) `
> Maven:
> `Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f) Maven home: /opt/maven Java version: 11.0.8, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "5.4.0-47-generic", arch: "amd64", family: "unix" `

Thanks for this. I have this bug on Windows, and I haven't had it on Linux, but I'm also using the OpenJDK 11.0.8, so I would have expected it to also fail for you.

**Comment by flouou** [comment]
Works for me too on MacOS Catalina 10.15.7 with sapmachine-11 as JDK (Java Version 10.0.8)
Maven Version 3.6.3

**Comment by knjk04** [comment]
Thanks, @flouou. It looks like this may be a Windows issue then

**Comment by loganrouleau** [comment]
I can reproduce Karan's issue here on Windows with `mvn -Dtest=ReadingGoalCalculatorTest,DateUtilsTest test`

The issue seems to be statically mocking DateUtils from 2 different classes. The mocking survives as long as the test thread, and I don't think we have any surefire parallelization enabled so every test is on 1 thread. I was able to fix it by assigning `Mockito.mockStatic(DateUtils.class)` to a variable like `private static MockedStatic<DateUtils> mockedDateUtils;`, and then unsetting the mock at the end of each test class:
``` @AfterAll
    static void tearDown() {
        mockedDateUtils.close();
    }
