### ISSUE TITLE
Adding a new custom shelf needs a page refresh 

### ISSUE THREAD

**Issue by amit1307** [Project-Books/book-project#319]
**Describe the bug**

New custom shelf isn’t available without page refresh. Only after refreshing the page, the newly added custom shelf is available in the secondary shelf dropdown.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'homepage'
2. Click on 'Add Shelf' and add a new shelf named 'Test Shelf'
3. Click on 'Add Book' and under secondary shelf drop down, 'Test Shelf' is not available
4. Refresh the page and click again on 'Add Book', now under secondary shelf drop down 'Test Shelf' is available 

**Expected behaviour**

'Test Shelf ' should be available immediately after saving and the page refresh shouldn’t be needed.

**Comment by knjk04** [comment]
Thanks for raising this bug

**Comment by shreyasirao** [comment]
Hey, would love to have a go at this. Is it ok if I start working on it?

**Comment by knjk04** [comment]
Hey, sure. That would be great, thanks! If you need a hand with this, feel free to get in touch with us over our [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-h6vx3n8l-KN8QnO50r7QWZHgHFnFdPw) channel

**Comment by knjk04** [comment]
@shreyasirao How are you getting on with this issue? If you need more time, that's fine, but please let us know.

If you need any help on this, feel free to reach out to us on [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-i7lept44-rgJ9yB0A2vedJTLyyfkjKQ)

**Comment by knjk04** [comment]
@shreyasirao 
Unfortunately, as we have not heard back from you in a while, I will unassign you from the issue. This is in line with our contributing guidelines.
