### ISSUE TITLE
Make the data "per user"

### ISSUE THREAD

**Issue by ChFlick** [Project-Books/book-project#320]
**Is your feature request related to a problem? If so, please describe.**
Some time ago, users/login/registration was added to the application.
Yet, the book/shelf logic and relations were not updated for multi-user purposes.
Every user currently shares the same data.

**Describe the solution you'd like**
Add some kind of ownership relation to users/books/shelves.
Each user should have their own books and shelves.

**Additional context**
I'm not sure how this works out with the predefined shelves, maybe the shelves should be generalized into a "shelf" entity and the predefined ones are automatically created upon registration, or some other solution.

**Comment by knjk04** [comment]
Thanks for creating this issue.

For whoever picks this up, we need some way of only allowing a custom user-made shelf to be renamed or deleted, whereas predefined shelves should not be renamed or deleted.

**Comment by MikeLowrie** [comment]
Editing shelves has been made possible with my changes in #342.
However, for ownership of elements, we could create a relation structure between shelves, books, and users like so:
One User owns Many Shelves, One Shelf owns Many Books, One User is related to many Books (could be indirect relation through Shelf).
Coincidentally, my regular work uses relational stuff like this as its core, and I could take this on with a bit of help. The one thing I haven't understood yet (in looking around the code for 15 seconds) is where user information is stored. How are multiple users stored in the model currently?

**Comment by knjk04** [comment]
We have a [User](https://github.com/Project-Books/book-project/blob/master/src/main/java/com/karankumar/bookproject/backend/entity/account/User.java) entity, so we save to the user repository (via the service). Feel free to check out `localhost:8081` to see the table in the database.

If you're still interested in this, I can assign you to the issue once you've worked on your existing issues

**Comment by Burhak** [comment]
I'd like to work on this one if it's still available

**Comment by knjk04** [comment]
Sure, thanks. Before I assign you, could you please describe your implementation approach?

**Comment by Burhak** [comment]
1. add a User reference to Shelf class (both CustomShelf and PredefinedShelf need to belong to some User)
2. create method `findAllByUser` in both of Shelf repositories which will be called by `findAll` methods of Shelf services
3. change method `findByShelfName` to `findByShelfNameAndUser` in both Shelf repositories

**Comment by knjk04** [comment]
Sounds good, thanks!

**Comment by knjk04** [comment]
@Burhak How are you getting on with this issue? If you need more time, that's fine, just let us know.

**Comment by Burhak** [comment]
@knjk04 I just need a couple more days to submit a PR

**Comment by knjk04** [comment]
@Burhak No problem, thanks for letting us know
