### ISSUE TITLE
Remove 'forgot password' link on login page

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#336]
![image](https://user-images.githubusercontent.com/11173328/93053539-dab76700-f65f-11ea-9f77-658eda9ba06d.png)

Remove the forgot password link as this is not implemented (and we are not going to implement this in Vaadin)

**Comment by vvkpd** [comment]
I wanted to pick this card, please let me know If required

**Comment by knjk04** [comment]
Sure, thanks

**Comment by wesleynepo** [comment]
> I wanted to pick this card, please let me know If required

Are you doing this? Because I did this card and just now I saw that was assigned. Please let me know!

**Comment by knjk04** [comment]
@vvkpd It's fine if you're still working on this as you asked first. However, please do let us know.

As per our contributing document, if we do not hear back from you within seven days, we will pass this on to someone else (in this case, @wesleynepo )

**Comment by vvkpd** [comment]
Sorry, I was not aware of that you have assigned me on this card. I started working on it, just doing the project setup.

**Comment by knjk04** [comment]
No problem, thanks for letting us know
