### ISSUE TITLE
Fix failing test: countOnlyReadBooksWithAFinishDateTowardsGoal 

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#337]
**Describe the bug**

The test runs in IntelliJ, but fails on Windows when `mvn clean install` is executed.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open `mvn clean install` at the root of the project
2. See error

**Expected behaviour**

The test should pass.

**Comment by sumanth-thyagarajan** [comment]
can I work on this

**Comment by knjk04** [comment]
Sure, I'll assign you to the issue. Thanks!

**Comment by knjk04** [comment]
If you need a hand with this, feel free to get in touch with us over [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-h6vx3n8l-KN8QnO50r7QWZHgHFnFdPw)

**Comment by knjk04** [comment]
@sumanth-thyagarajan How are you getting on with this issue?

**Comment by knjk04** [comment]
@sumanth-thyagarajan Unfortunately, as we have not heard from you in a while, I will unassign you from this issue

**Comment by knjk04** [comment]
This still fails with Maven

**Comment by glegshot** [comment]
@knjk04  the testcase countOnlyReadBooksWithAFinishDateTowardsGoal and was able to get the test executed successfully in windows.I have used the mvn wrapper in the project to get the test executed.
is the issue still reproducible? Could you post a error snap of the build to get more idea on it.

**Comment by knjk04** [comment]
@glegshot Sorry, I'm not sure where the test is gone. Presumably, you were able to find it. Which file is it in?

**Comment by glegshot** [comment]
@knjk04  the test is in com.karankumar.bookproject.ui.goal.ReadingGoalViewTest.java

**Comment by knjk04** [comment]
@glegshot Ah, I was looking in the wrong place. In that case, I'll close this issue as the test is no longer needed for 0.2.0 and subsequent releases. Apologies for the inconvenience
