### ISSUE TITLE
Unable to import IntelliJ code style file

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#339]
I get the following error when I try to import our [IntelliJ code style file](https://github.com/Project-Books/book-project/blob/master/ide/intellij/book_project_code_style.xml) into IntelliJ:

> IntelliJ IDEA code style XML import failed with error message: The file doesn't seem to be avalid IntelliJ IDEA XML scheme, it should contain 'code_scheme root; element, found 'profiles' instead.

**Comment by flouou** [comment]
Hey @knjk04 it seems to work fine for me. I am working with IntelliJ 2020.2.2 Ultimate Edition.

**Comment by knjk04** [comment]
Thanks for the heads-up. It might just me then!

**Comment by knjk04** [comment]
Removing the 'hacktoberfest' label as we won't be able to get this merged in before the 31st
