### ISSUE TITLE
Add 'flyway clean' to docker-compose

### ISSUE THREAD

**Issue by amit1307** [Project-Books/book-project#341]
**Is your feature request related to a problem? If so, please describe.**
Currently while trying to bring up the application we need to start db using `docker-compose up`. This step sometimes gives an error related to flyway and there is a manual step that needs to be executed to fix the error.

**Describe the solution you'd like**
Manual execution of flyway clean should not be needed and it should happen automatically without user intervention. This will make running the application seamless and would improve user experience a bit while starting the app.

**Comment by knjk04** [comment]
@amit1307 I think we don't need to work on this. We shouldn't always need to flyway clean -- that's only when something's gone wrong and we need to drop all of the tables. What do you think?

**Comment by amit1307** [comment]
Yes I agree to that so we can close this issue. I had spent a bit of time initially but couldn't find any clean solution so was thinking if we really need to do this.
