### ISSUE TITLE
Build failure with JDK 12

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#343]
Oracle JDK 12.0.2 on Windows. The following log is the output of running `mvnw.cmd clean install`:

https://gist.github.com/hieu-t-tran/50199f1ed4aa523b71f96b16a853433f

**Comment by flouou** [comment]
According to https://github.com/mvysny/karibu-testing/issues/31 there does not seem to be much we can do about this issue (beside downgrading to java 11)

**Comment by knjk04** [comment]
Thanks for this! I'll make a note of this on the README
