### ISSUE TITLE
Import books from exported Book Project file

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#345]
**Is your feature request related to a problem? If so, please describe.**
A user may want to import a JSON file they exported from the Book Project.

**Describe the solution you'd like**
Add a controller endpoint that parses JSON and adds the relevant authors, books and custom shelves.

**Additional context**
Branch from `0.2.0`. When you're ready, create a pull request to go back into it.

**Comment by schrothbn** [comment]
Would like to work on that

**Comment by knjk04** [comment]
@schrothbn Sure, thanks!

**Comment by knjk04** [comment]
@schrothbn I don't think we'll get time to review & merge your work on this before the end of Hacktoberfest, so I'll remove the label. Are you still happy to work on this?

**Comment by schrothbn** [comment]
Of course don't worry, i'm happy to help without hacktoberfest as well ,)

**Comment by knjk04** [comment]
@schrothbn Great! How are you getting on with this issue?

**Comment by schrothbn** [comment]
@knjk04 I'm pretty far with it, just need a bit more time to test it and update it with the Shelf-to-User-Relation that is new on master.

**Comment by knjk04** [comment]
@schrothbn Just checking up again -- how are you getting on?

**Comment by schrothbn** [comment]
@knjk04 The PR will come later today. Sorry had much to do at work last 2 weeks, will now integrate recent changes from master and test everything and then create the PR

**Comment by knjk04** [comment]
@schrothbn No problem, thanks for the update!

**Comment by ZackHollander** [comment]
I will like to take this issue.

**Comment by knjk04** [comment]
@ZackHollander Thanks, I've assigned you to it. I've also updated the issue description

**Comment by knjk04** [comment]
@ZackHollander How are you getting on with this?

**Comment by ZackHollander** [comment]
just finished going through all the stuff you sent Kate. I am starting today.
