### ISSUE TITLE
Show books in the New York Times bestseller list

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#347]
**Describe the solution you'd like**
Use the [New York Times Book API](https://developer.nytimes.com/docs/books-product/1/overview) to get a list of the best sellers list. We would like:

- The book title
- Author name
- Publication date
- Publisher
- Book description
- Genre

**Additional context**
We will expand on this later to make it easy for users to add books that feature in the best seller list.

**Comment by chinmay9194** [comment]
Hi,
If I am understanding this right a React Page is to be Developed to Showcase above details.
If yes, can you please help in some more details.
Thanks

**Comment by knjk04** [comment]
Hi,

This issue is currently blocked, so we're not looking to implement this just yet. We haven't switched to React yet, so it may be some time before we get to this issue.

We'll also be specifying the design for this later.

Was there anything in particular that you would like to know about this issue?

**Comment by knjk04** [comment]
Update: this will be the backend issue
