### ISSUE TITLE
Update table of contents in style guide

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#350]
It is now outdated. New sections need to be added and we need to ensure the right level of indentation is used.

**Comment by CptOrange16** [comment]
Hello, i would like to work on this issue

**Comment by knjk04** [comment]
Thanks, I've assigned you to the issue!

**Comment by CptOrange16** [comment]
Thank you for letting me help you guys with the docs.
I've checked the links to the sections in the table of contents and some of them are broken (i'll fix that)
Can you clarify what are the sections that need to be added (or where i can find them)?

**Comment by knjk04** [comment]
Not at all, thanks for offering to help!

Things that need doing:
- Change the '120 characters limit' link to the new section ('100 character column limit')
- Add the 'One true brace style' to the table of contents
- The 'naming' section (and, by extension, everything under it) is indented one level more than it should be in the contents
- The TODOs section is in the wrong place in the table of contents
- JUnit is indented one level more than it should be in the table of contents

- There are some new sections in the JUnit section (see the body) that need to be added to the contents

**Comment by CptOrange16** [comment]
Ok, I'm nearly done with the changes. 
A suggestion: would you also want me to change the anchor links in the table of contents? They are currently urls but we could change them to be local to the document itself, so they won't open a new page when clicked.
Example:
``1. [Introduction](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md#introduction)``
would become 
``1. [Introduction](introduction)``

**Comment by knjk04** [comment]
> Ok, I just finished making all the changes. I am going to do a pull request for the issue.

Great, thanks!

As for the anchor links, a new page doesn't open for me when I click on any of the links in the table of contents. If I were to shorten one of them, then my browser (I've tested this on Firefox and Chrome) ask me whether I'd like to open a new page. Even if I choose yes, it doesn't actually open it up in a new page.

Which browser and OS are you using?

**Comment by CptOrange16** [comment]
> Which browser and OS are you using?

I've tested the current anchor links in Windows and Ubuntu (18.04 LTS). 
- **In Windows Firefox:** clicking on a link on the table of contents **reloads** the page and shows the section
- **In Windows Google Chrome:**  clicking on a link on the table of contents **reloads** the page and shows the section
- **In Ubuntu Firefox:** clicking on a link on the table of contents **reloads** the page and shows the section
- **In Ubuntu Google Chrome:** clicking on a link on the table of contents **reloads** the page and shows the section

If i change the url to the shorter version (a reference to the document itself):
- **In Windows Firefox:** clicking on a link on the table of contents **does not reload** the page and shows the section
- **In Windows Google Chrome:**  clicking on a link on the table of contents **does not reload**the page and shows the section
- **In Ubuntu Firefox:** clicking on a link on the table of contents **does not reload**the page and shows the section
- **In Ubuntu Google Chrome:** clicking on a link on the table of contents **does not reload**the page and shows the section
