### ISSUE TITLE
Create class diagram for classes in the entities package

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#351]
Create an entity-relationship diagram for our Java entities using [JDL-studio](https://start.jhipster.tech/jdl-studio/). This could help onboard new contributors quicker.

If you want to use a different tool, let us know before implementing it

Update: create a class diagram, not an ER diagram

**Comment by Anoop01234** [comment]
Can you give more information on what am I supposed to make the entity-relationship diagram?

**Comment by knjk04** [comment]
The entity-relationship diagram should show our different Java [entities](https://github.com/Project-Books/book-project/tree/master/src/main/java/com/karankumar/bookproject/backend/entity) and how they are related to one another (e.g. one-to-many, many-to-many relationships).

Sure, I'm happy with Lucidchart.

In terms of deliverables, it would be great if you could create a markdown file (called something like `ARCHITECTURE.md`) in the `entity` folder that has a screenshot of the diagram.

If you're happy to proceed, let us know and then I can assign you to the issue.

**Comment by Anoop01234** [comment]
Do I need to include the variable and functions both?

**Comment by Anoop01234** [comment]
Do I need to include functions and Variables both?

And is this pattern fine since I am working on LucidChart:
------------------------------------------
Author
------------------------------------------
-firstName: String
-lastName: String
------------------------------------------
+Author(firstName, lastName)
+toString()
------------------------------------------

**Comment by knjk04** [comment]
Yes. please. That'll be nice.

One update: could you call the file `README.md`? This way, it'll show up as a README. Perhaps we can have a section in this second README called 'Architecture'.

**Comment by Anoop01234** [comment]
Do you mean that I have to add the ER diagram in the README file under a new section called "Architecture"?

**Comment by knjk04** [comment]
Yes, please (in a new `README` file in the `entity` directory)

**Comment by Anoop01234** [comment]
Okay! Got your point.
Thanks

**Comment by Anoop01234** [comment]
Is this correct or there are some more additions that you'd want?

![image](https://user-images.githubusercontent.com/60193636/94965912-f5bc1f00-0519-11eb-8d83-2de44586de16.png)

**Comment by Anoop01234** [comment]
@knjk04 Is this fine Sir?

**Comment by knjk04** [comment]
@Anoop01234 Thanks for sending this diagram. I took a look this morning, but I'd like to think about this more before getting back to you. 

I don't know if you saw my announcement on the #book-project channel on our Slack workspace, but we've had a large influx of new people recently, so there may be a delay in getting back to you. Rest assured, we'll get back to you soon, though!

Also, feel free to call me Karan :)

**Comment by knjk04** [comment]
@Anoop01234 I've been thinking about this and I think it would be better to have a class diagram rather than an entity-relationship diagram. Since ER diagrams are more closely aligned with database tables, I think a class diagram is a better fit. 

Are you happy with this change? If so, could you represent the different relationships between the classes (e.g. the entities should inherit from `BaseEntity`, etc.)?

**Comment by Anoop01234** [comment]
Can you please elaborate a bit more? Also, the diagram that I had made is a class diagram only.
And the arrows themselves represent inheritance, I can add that part. Is there anything other than this that you want me to add?

**Comment by knjk04** [comment]
@Anoop01234 Could you add the different relationships between classes (e.g. association, aggregation, composition, etc.)

**Comment by Anoop01234** [comment]
Is the diagram fine now? Or do I need to make more changes?

![image](https://user-images.githubusercontent.com/60193636/95505061-5db3af00-09cb-11eb-974d-7ff0818cf395.png)

**Comment by knjk04** [comment]
@Anoop01234 Thanks for updating this.

Some feedback:

- For inheritance, could you please use unfilled arrows (direct lines are used to denote association)?
- `Author`, `Tag`, `ReadingGoal` and `CustomShelf` need to inherit from `BaseEntity`. This can be found by looking at those classes and seeing that they extend `BaseEntity`
- `CustomShelf` should inherit from `Shelf`
- The composition diamond for the `Author` and `Book` relationship is the wrong way around
- There should not be a direct relationship between `Book` and `Shelf`
- Could you please change the `Book` and `BookGenre` relationship from composition to aggregation?
- Could you please change the `Book` and `RatingScale` relationship to a dependency?

Also, I can understand that you may have spent a while adding the fields and methods. However, as this may be prone to quickly become outdated (sooner than we add new entities or change the relationships), could you please remove them? Apologies for changing my mind on this

**Comment by Anoop01234** [comment]
I will add or remove the entities in the future if you want. Other than this I have made changes as you mentioned. Also, I welcome any other further amendments in the diagram.

Could you please have a look at the updated diagram and tell me if there are any further changes?

![image](https://user-images.githubusercontent.com/60193636/95690570-665bed80-0c36-11eb-8431-bacd680581c2.png)


Also please tell me whether there will be any relation between `Author`, `tag`, `ReadingGoal`, and `CustomerShelf'`  with the  `Book` or will they be having only with the `BaseEntity`?

**Comment by knjk04** [comment]
@Anoop01234 Thanks for making the changes. 

Book:
- `Book` should inherit from `BaseEntity`, but I can see that you're using association
- Sorry for changing my mind on this. Could you please replace the dependency relationship between `Book` and `RatingScale` to aggregation?

Shelf:
- The `Shelf` and `CustomShelf` inheritance arrow is the wrong away around. `CustomShelf` inherits from `PredefinedShelf`
- You're using association for the `Shelf` and `PredefinedShelf` relationship, but `PredefinedShelf` inherits from `Shelf`

We're almost there! Thanks a lot for everything you've done so far, we highly appreciate it!

Also, I don't know if you saw my Slack message, but could you please submit future submissions in a PR (you can still submit drafts as messages)? It's easier to keep up with in-progress work that way.
