### ISSUE TITLE
Replace query with derived query

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#357]
In `BookRepository`, we currently have

```java
    @Query("select b from Book b " + "where lower(b.title) like lower(concat('%', :filterText, '%'))")
    List<Book> search(@Param("filterText") String filterText);
```

This should be replaced with a derived query (`findByTitle`)

**Comment by flouou** [comment]
Hey, I would like to take a stab at this issue! Please let me know, if it's alright to start working on this, thanks in advance.

**Comment by knjk04** [comment]
Sure, thanks!

**Comment by shreyamodi1999** [comment]
Hey! Can I work on this or is it just assigned to others already?

**Comment by knjk04** [comment]
Hey,

Unfortunately, this issue is already assigned. I'm looking to create a similar issue to this soon, so keep an eye or out (or feel free to join our Slack channel to get notified)!
