### ISSUE TITLE
Ensure there are no duplicate tags

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#359]
As is stands, multiple tags with the same name can be created. Make it so that this is not the case. For example, if a tag called "dystopian" exists, another tag with the same name should not be allowed to be created.

This change should affect the `TagService`. An accompanying test is also required.

The check for a tag with the same name should be case insensitive (i.e. 'Dystopian' should not be permitted if 'dystopian' already exists)

**Additional context**

Branch from `0.2.0` and create a branch to go back into it

**Comment by prathyushasai** [comment]
Hi @knjk04, I'm interested in working on this issue.

**Comment by killerkc12** [comment]
i could work on this

**Comment by knjk04** [comment]
@prathyushasai Hi. Sure, I'll assign you to the issue. Thanks!

**Comment by knjk04** [comment]
Sorry, @killerkc12. It looks like Prathyusha got there just before you! Feel free to enquire about any other unassigned & unblocked issues

**Comment by killerkc12** [comment]
> Sorry, @killerkc12. It looks like Prathyusha got there just before you! Feel free to enquire about any other unassigned & unblocked issues

No problem 😊

**Comment by knjk04** [comment]
@prathyushasai feel free to get in touch with us over [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-h6vx3n8l-KN8QnO50r7QWZHgHFnFdPw) if you need a hand with this

**Comment by prathyushasai** [comment]
Sounds good. Will be joining Slack. Thanks @knjk04  !

**Comment by knjk04** [comment]
@prathyushasai How are you getting on with this issue? If you need more time or need some help, feel free to let us know

**Comment by prathyushasai** [comment]
Doing well, just a bit bogged down with work. Will be making progress this weekend!

**Comment by prathyushasai** [comment]
Hi @knjk04,

Sorry for the delay!

There were two approaches that I am considering. Let me know which is preferred. The methods in both approaches will be called in the `save()` function and return a boolean value and the `Tag` entity will have a public getName() function that returns the String name.:
1. Create a method to check for duplicate values. Use `findAll()` to get a list of tags. Iterate through the list to see if the existing Tag.getName is the same as the parameter Tag.name (accounting for case insensitivity). Return True if duplicate, False otherwise.
2. Create a method similar to `findAll()` that returns the names of all the tags as a Set (faster look-up). Check if the existing Tag.getName is the same as the parameter Tag.name (accounting for case insensitivity). Return True if duplicate, False otherwise.

Thank you!

**Comment by knjk04** [comment]
Hi @prathyushasai.

> Sorry for the delay!

No problem.

> There were two approaches that I was considering. Let me know which is preferred.

Approach two seems better. In `TagRepository.java`, we could have a `findByName` method (Spring Data JPA will be able to run a query for us).

> One question - Should some sort of error message or alert show up on the user side if the tag they are adding is a duplicate?

Good question! We would eventually want to show an error message so that the user is informed if they try to save a duplicate tag. However, as we haven't implemented tags on the frontend yet (we'll be saving it for when we switch to React), don't worry about this for now.

**Comment by knjk04** [comment]
@prathyushasai As we're nearing the end of the month, I think it's unlikely that we'll get a chance to review and merge your PR in before the 31st of October. I'll remove the 'hacktoberfest' label. Are you still happy to work on this?

**Comment by prathyushasai** [comment]
Hi @knjk04, Yes I am. Will still be working on it. I've implemented the initial structure. Just testing currently.

**Comment by knjk04** [comment]
@prathyushasai How are you getting on with this? If you'd like some early feedback/feedback as you go along, feel free to create a draft PR

**Comment by knjk04** [comment]
@prathyushasai Unfortunately, as we have not heard back from you in a while, I will unassign you from the issue. This is in line with our contributing guidelines.

**Comment by Louie-Yep** [comment]
Hello @knjk04, I would like to work on this issue with my friend. Is it still available?

**Comment by knjk04** [comment]
Hello @Louie-Yep. Sure, I'll assign you to the issue. Thanks!

**Comment by Louie-Yep** [comment]
Hey Karan, I think my partner and I have implemented issue #359 ensuring that duplicate tags don’t exist.  What we did:

Run a case insensitive query using JPQL for the tag we are trying to save. To get the name of the tag we're trying to save, we added a public name function in the Tag class. Let me know if there’s a better way to access a tag’s name in the TagService class.

After running the query, we check to make sure that the query returns an empty list before saving the tag.  If the list is not empty, we don’t save the tag.

We added a test case where we create three tags which are only different in the casing of their characters and save all three of them. Then we check that only the first tag was saved to the repository.

**Comment by knjk04** [comment]
@Louie-Yep Sounds good. Is there a particular reason why you're both using JPQL instead of a derived query?

**Comment by Louie-Yep** [comment]
Not a large reason. The syntax for making the query case insensitive seemed easier to do with a JPQL, but we could change it if there's an issue

**Comment by abhity16** [comment]
@knjk04 is this still open ?

**Comment by knjk04** [comment]
@abhity16 It's still open, but this is already assigned, unfortunately

**Comment by knjk04** [comment]
@Louie-Yep How are you getting on with this? Did you manage to get a chance to see my replies on Slack?

**Comment by knjk04** [comment]
@Louie-Yep Unfortunately, as we have not heard back from you in a while, I will unassign you from the issue. This is in line with our contributing guidelines.

**Comment by VikramSitaram** [comment]
@knjk04 Is this issue open to be worked upon? Also, is there an updated Slack link that I can use (seems like the one I clicked is expired). Thanks!

**Comment by knjk04** [comment]
@VikramSitaram Yes, I'll unblock the issue and assign you to it. Thanks!

Here's an updated Slack link: https://join.slack.com/t/teambookproject/shared_invite/zt-lvr8oi47-8BjZzov0QDsx4RvjkNjOcA. I'll update the links on the READMEs
