### ISSUE TITLE
Test whether an Author without any books can be deleted

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#362]
In a new `AuthorServiceTest` class, test whether an author (that is not associated with any books) can be deleted. 

Further requirements:
- The test should be an `IntegrationTest` (it should have the `@IntegrationTest` annotation so that it loads the Spring context)
- A new `Author` will need to first be created

Update: the `AuthorServiceTest` class has since been created, so add the test to this class

**Comment by Anu-123-gif** [comment]
I would like to work on this issue, can you assign it to me please?

**Comment by charchithere** [comment]
Hello! I would like to work on this . pls assign it to me

**Comment by knjk04** [comment]
@Anu-123-gif Sure, I'll assign you to the issue. Thanks!

**Comment by knjk04** [comment]
@charchithere Sorry again, someone else got there ahead of you. Feel free to request to be assigned to an issue that is unassigned, unblocked and someone else hasn't already asked

**Comment by Anu-123-gif** [comment]
Thanks, I'll start working on it !

**Comment by knjk04** [comment]
@Anu-123-gif Great! If you need a hand, we'll be happy to help over our [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-h6vx3n8l-KN8QnO50r7QWZHgHFnFdPw) channel

**Comment by knjk04** [comment]
@Anu-123-gif How are you getting on with this issue? If you need more time or need some help, feel free to let us know

**Comment by Anu-123-gif** [comment]
Yes sir I am working on this issue, I'll ask my doubts on slack channel. Thanks!

**Comment by knjk04** [comment]
Great, thanks! Feel free to call me Karan
