### ISSUE TITLE
Test whether a saved Author can be found

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#363]
In a new `AuthorServiceTest` class, test whether a saved author can be found 

Further requirements:
- The test should be an IntegrationTest (it should have the `@IntegrationTest` annotation so that it loads the Spring context)
- A new `Author` will need to first be created

**Comment by CptOrange16** [comment]
Hey, just finishing up my other open issue. I can take this one aswell if you are ok with it 👍

**Comment by knjk04** [comment]
Sure, thanks!
