### ISSUE TITLE
Test whether a null Book can be saved

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#364]
Test whether a null Book can be saved. This should not be permitted. This test should be added to the `BookServiceTest`.

This should be similar to the `notSaveANullTag()` test in `TagServiceTest`.

**Comment by sahil9001** [comment]
I would like to work on this issue please assign me this, Thanks!

**Comment by knjk04** [comment]
Sure, I'll assign you to the issue. Thanks!

**Comment by knjk04** [comment]
@sahil9001 If you need anything, feel free to get in touch with us over [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-h6vx3n8l-KN8QnO50r7QWZHgHFnFdPw)

**Comment by sahil9001** [comment]
@knjk04 Sure I'll resolve the issue by tomorrow!

**Comment by knjk04** [comment]
As discussed on Slack, this test already exists. Apologies.
