### ISSUE TITLE
Test whether a saved book can be found

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#365]
Test whether a saved book (a `Book` needs to first be saved) can be found using `findById()`.

If you run into issues and get stuck (e.g. lazy initialization exceptions), feel free to get in touch with us over Slack)

**Additional context**

The following can be removed when this test is in place:

```java
        List<Book> books = bookRepository.findAll();
        if (books.contains(book)) {
            LOGGER.log(Level.SEVERE, book.getTitle() + " not deleted");
        } else {
            LOGGER.log(Level.INFO, book.getTitle() + " deleted. Book repository size = " +
                    bookRepository.count());
        }
```

**Comment by Ruchika8** [comment]
I would like to work on this issue. Please assign it to me thanks

**Comment by charchithere** [comment]
I would like to Work on this. Pls assign it to me

**Comment by knjk04** [comment]
@Ruchika8 Thanks! I'll assign you

**Comment by knjk04** [comment]
@charchithere Sorry, @Ruchika8 asked first!

**Comment by knjk04** [comment]
@Ruchika8 If you need anything, we'll be happy to help over [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-h6vx3n8l-KN8QnO50r7QWZHgHFnFdPw)

**Comment by Ruchika8** [comment]
Thanks Karan!
