### ISSUE TITLE
Book can be both the most liked book and the least liked book

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#371]
![Screenshot 2020-09-30 23-16-58](https://user-images.githubusercontent.com/753350/94740522-201fa800-0373-11eb-875b-6b65d7cd5f03.png)

In this scenario, neither statistic should show. This seems to happen when there is only one rated book.

**Comment by pklink** [comment]
I would like to work on this issue. Can you assign it to me, please?

**Comment by knjk04** [comment]
Sure, thanks!
