### ISSUE TITLE
Add headings in settings

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#373]
**Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/11173328/94776388-8d562c00-03b9-11eb-940f-1509f7378b03.png)

Add subheadings to separate the different sections:

- An 'Appearance' heading that contains the dark mode toggle
- A 'My books' heading that contains the 'reset shelves' and export button

**Comment by vvkpd** [comment]
I would like to work on this card, could you please assign to me

**Comment by knjk04** [comment]
Sure, thanks
