### ISSUE TITLE
Test whether a saved ReadingGoal can be deleted

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#374]
Test that after saving a `ReadingGoal`, it can then be deleted

**Additional context**

- Method to test: `delete()` in `ReadingGoalService`

- Test file to add to: `ReadingGoalServiceTest`

As ever, if you need anything, feel free to get in touch with us over [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-h6vx3n8l-KN8QnO50r7QWZHgHFnFdPw)

**Comment by patrickjkennedy** [comment]
Hi @knjk04, is it OK if I work on this issue?

**Comment by knjk04** [comment]
Hi @patrickjkennedy, 

Sure, thanks! I'll assign you to the issue.

If you need anything, feel free to get in touch with us over [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-h6vx3n8l-KN8QnO50r7QWZHgHFnFdPw)

**Comment by patrickjkennedy** [comment]
Hi @knjk04, I've submitted my PR. This is my first open-source PR so please let me know if I need to make any changes and I will be more than happy to do so.

All the best,
Patrick

**Comment by knjk04** [comment]
Hi @patrickjkennedy,

Thanks for the quick turnaround in creating the PR! We'll review your code shortly and provide suggestions for changes if necessary
