### ISSUE TITLE
Test that a null ReadingGoal can not be saved

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#375]
Test that a null `ReadingGoal` cannot be saved

**Additional context**

- Method to test: `save()` in `ReadingGoalService`

- Test file to add to: `ReadingGoalServiceTest`

As ever, if you need anything, feel free to get in touch with us over [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-h6vx3n8l-KN8QnO50r7QWZHgHFnFdPw)

**Comment by dmitraver** [comment]
hi, can pick this one

**Comment by knjk04** [comment]
Sure, thanks!
