### ISSUE TITLE
Test whether a null PredefinedShelf can be saved

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#376]
**Describe the test you would like to add or modify**

Test whether a null ``PredefinedShelf` can be saved. The expectation is that it should not be possible.

**Additional context**

Method and class that is being tested: `save()` in `PredefinedShelfService`

---

If you need anything, feel free to get in touch with us over [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-h6vx3n8l-KN8QnO50r7QWZHgHFnFdPw)

**Comment by BoJacobs** [comment]
Hi @knjk04, I would like to tackle this one as well!

**Comment by knjk04** [comment]
Sure, go for it! Thanks!
