### ISSUE TITLE
Test whether a valid PredefinedShelf can be saved

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#377]
**Describe the test you would like to add or modify**

Test whether a valid (i.e. non-null) `PredefinedShelf` can be saved. The expectation is that this should pass.

**Additional context**

Method and class that is being tested: e.g. `save()` in `PredefinedShelfService`]

---

If you need anything, feel free to get in touch with us over [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-i7lept44-rgJ9yB0A2vedJTLyyfkjKQ)

**Comment by sreejithsev** [comment]
Hi @knjk04,

I would like to work on this. Can I pick this one.

**Comment by knjk04** [comment]
Sure, thanks!

**Comment by knjk04** [comment]
@sreejithsev 
How are you getting on with this issue? If you need more time or need some help, feel free to let us know

**Comment by sreejithsev** [comment]
@knjk04,
Is this issue already resolved in #376 ? Could you please confirm?
This is the first time I am trying to contribute to a project. Kindly guide me, if I am wrong.

**Comment by knjk04** [comment]
@sreejithsev No, that's testing whether a null predefined shelf can be saved. This issue is for testing whether a valid predefined shelf can be saved

**Comment by sreejithsev** [comment]
@knjk04 
Kindly note, I have unassigned myself from #377.

**Comment by knjk04** [comment]
@sreejithsev Thanks for letting us know

**Comment by CGAura** [comment]
Hi I can pick this up if still needing done

**Comment by knjk04** [comment]
@CGAura Sure, I'll assign you to the issue. Thanks!

**Comment by CGAura** [comment]
@knjk04 perfect thanks.
