### ISSUE TITLE
Genre can be both most liked & least liked genre

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#389]
**Describe the bug**

A genre can be both the most liked and least liked at the same time (when only one read book exists).

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'my books'
2. Ensure there is only one read book with a date finished field that is in the current year, a genre specified and a rating
3. Go to 'statistics'

**Expected behaviour**

The most liked genre and least liked genre statistics should not show when there is only one book

**Screenshots**

![image](https://user-images.githubusercontent.com/11173328/94987364-dfd04d80-055d-11eb-8b75-38a6635d08d0.png)

**Additional context**

There should also be an accompanying test to ensure this doesn't happen again and the fix works as intended

---

If you need anything, feel free to get in touch with us over [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-h6vx3n8l-KN8QnO50r7QWZHgHFnFdPw)

**Comment by phylyps-trak** [comment]
Hello, can I work on this?

**Comment by knjk04** [comment]
Sure, thanks!

**Comment by knjk04** [comment]
@phylyps-trak How are you getting on with this issue? If you need more time or need some help, feel free to let us know

**Comment by lpegoraro** [comment]
Hey, I have a good idea how to fix this, can I get. I will open a PR soon. If @phylyps-trak don't mind.

**Comment by knjk04** [comment]
@phylyps-trak Unfortunately, as we have not heard from you a in a while, I am going to unassign you from this issue. This is in accordance with our contributing guidelines

**Comment by knjk04** [comment]
@lpegoraro Thanks for taking an interest in this issue. I'll assign you to it!

**Comment by lpegoraro** [comment]
@knjk04 thanks!
