### ISSUE TITLE
Convert integer division to floating point division (CalculateReadingGoal)

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#391]
**Context**

In `CalculateReadingGoal.java`, we have the following method:

```java
    public static int booksToReadFromStartOfYear(int booksToReadThisYear) {
        return ((int) Math.ceil(booksToReadThisYear / WEEKS_IN_YEAR));
    }
```

Both `booksToReadThisYear` and `WEEKS_IN_YEAR` are ints. Hence, as it stands, the cast is not needed as the result is an `int`, anyway. 

**What we want**

- Cast one of the operands to a `float`. This will allow us to first round up and then truncate
- Add an accompanying test to ensure this works

We recommend approaching this in a test-driven development (TDD) fashion

**Comment by bharatbahl** [comment]
Hi @knjk04,

Can I be assigned to this issue?

**Comment by knjk04** [comment]
Sure, I've assigned you to the issue.

**Comment by anursaxe25** [comment]
can i work on this issue ?

**Comment by knjk04** [comment]
@anursaxe25 Sorry, this issue has already been assigned. Feel free to request to be assigned to an issue that's both unassigned and unblocked
