### ISSUE TITLE
Find all the books for a particular author

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#394]
**Describe the solution you'd like**
Using `findByAuthor()` in the `BookRepository`.

**Additional context**
More information to follow on where to add this once we have designed the UI for this.

---

If you need anything, feel free to get in touch with us over [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-h6vx3n8l-KN8QnO50r7QWZHgHFnFdPw)

**Comment by QasimKhan5x** [comment]
I'd like to do this.

**Comment by knjk04** [comment]
@QasimKhan5x Sorry, this issue is blocked. Feel free to request to be assigned to an unblocked and unassigned issue
