### ISSUE TITLE
Add tests for SettingsView

### ISSUE THREAD

**Issue by amit1307** [Project-Books/book-project#395]
**Describe the test you would like to add or modify**

Add tests for SettingsView class, the tests should capture the below functionalists:
1. Click of reset shelves shows a confirmation dialog
2. Export works as expected by exporting the book info in json format 

**Additional context**

Method and class that is being tested: [e.g. `configureExportBooksAnchor` in `SettingsView` via constructor]

---

If you need anything, feel free to get in touch with us over [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-h6vx3n8l-KN8QnO50r7QWZHgHFnFdPw)

**Comment by mofiebiger** [comment]
Hi @amit1307, can I work on this issue? Thanks! 😊

**Comment by djnautiyal** [comment]
Hey, Is this good for first timers? May I take this up?

**Comment by knjk04** [comment]
@djnautiyal Sorry, we should have added the blocked label sooner. We're still figuring out the details for this one. 

Please also note that we only [assign one issue at a time to new contributors](https://github.com/Project-Books/book-project/blob/master/CONTRIBUTING.md#new-contributors-assigned-to-at-most-one-issue-at-a-time).
