### ISSUE TITLE
Rename to avoid variable shadowing

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#397]
Currently, we have the following in `findBooksWithPageCountSpecified()` in `PageStatistics.java`:

```java
    private List<Book> findBooksWithPageCountSpecified() {
        List<Book> booksWithPageCount = new ArrayList<>();
        // ...
```

The `booksWithPageCount` variable overshadows a field. Rename this local variable to something descriptive so that there is no overshadowing.

**Comment by matheuscr30** [comment]
Can u assign it to me?

**Comment by knjk04** [comment]
Sure, thanks!

**Comment by davidlevinwork** [comment]
This is still an isuue?
If so, pliz assign me

**Comment by knjk04** [comment]
@davidlevinwork Sorry, this has already been assigned. Feel free to request to be assigned to an open, unblocked issue that is unassigned

**Comment by knjk04** [comment]
@matheuscr30 How are you getting on with this issue? If you need more time, that's fine, but please let us know.

If you need any help on this, feel free to reach out to us on [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-h6vx3n8l-KN8QnO50r7QWZHgHFnFdPw)

**Comment by matheuscr30** [comment]
Sorry, I totally forgot about this. Can u reassign this to another person?

**Comment by knjk04** [comment]
@matheuscr30 That's fine. I'll unassign you

**Comment by LieT13** [comment]
Hi, I want to contribute to the project and I thin this could be a good first issue to work. Can you assing it to me? Thanks!

**Comment by knjk04** [comment]
@LieT13 Sure, I'll assign you to the issue. Thanks!
