### ISSUE TITLE
 Convert integer division to floating point division (PageStatistics)

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#399]
**Context**

In `calculateAveragePageLength()` in `PageStatistics.java`, we have the following:

```java
    public Integer calculateAveragePageLength() {
        // ...
        return (booksWithPagesSpecified == 0) ? 0 :
                (int) Math.ceil(totalNumberOfPages / booksWithPagesSpecified);
    }
```

Both `totalNumberOfPages` and `booksWithPagesSpecified` are ints. Hence, the cast to an `int` is redundant. 

**What we want**

- Cast one of the operands to a float so that we can first get the result, round up and then truncate.
- Add an accompanying test to ensure this works as intended

**Comment by ShreyaPrabhu** [comment]
@knjk04 Can you assign this to me?

**Comment by knjk04** [comment]
Sure, thanks!
