### ISSUE TITLE
Refactor autowiring to constructor

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#402]
In `AuthorTest`, we currently autowire the services via the `BeforeAll`. It would be better if this was in the constructor.

By doing this, we can also:
- Remove the `@BeforeAll` method entirely
- Move the initialisations in `reset()` to the constructor
- Make the `BookService` and `AuthorService` final
- Rename the `reset()` method to `setUp()`

**Comment by Pinkolik** [comment]
Please assign me. I have one year experience developing with spring boot

**Comment by Pinkolik** [comment]
I've already done this and ready to make pull request! :) Just waiting for you to assign me

**Comment by knjk04** [comment]
Sure, I'll assign you to the issue
