### ISSUE TITLE
Refactor PredefinedShelfServiceTest

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#403]
What we need:
- Create a constructor and autowire the `BookService` (we don't want to use field injection) and the `PredefinedShelfService`
- Replace `shelves.size()` with checking that the `predefinedShelfService.count()` is zero (use AssertJ)
   - A count() method needs to be defined in `PredefinedShelfService`. For an example of something similar, see the `CustomShelfService`.

**Comment by Pinkolik** [comment]
Hello! I'm ready to take this task. Please assign me :)

**Comment by knjk04** [comment]
Hello @Pinkolik,

Unfortunately. we [only assign one issue at a time to new contributors](https://github.com/Project-Books/book-project/blob/master/CONTRIBUTING.md#new-contributors-assigned-to-at-most-one-issue-at-a-time). Once you've completed, #402, if this issue is still unassigned, feel free to request it

**Comment by jhanna60** [comment]
Hey I'd like to have a look at this please

**Comment by knjk04** [comment]
Thanks, @jhanna60! I'll assign you to the issue
