### ISSUE TITLE
Refactor to use AssertJ

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#409]
**Context**
We're currently using both JUnit's and AssertJ's assertions and assumptions. We've recently changed our style guide to require the use of AssertJ only (for consistency and readability) -- see #408.

**What we want**
Where we're currently using JUnit assertions and assumptions, refactor it to use AssertJ instead. Static imports should still be used.

**Comment by P3trur0** [comment]
Hi, I'd like to take this.

**Comment by knjk04** [comment]
Sure, I'll assign you to the issue. Thanks!

**Comment by P3trur0** [comment]
hi @knjk04, please have a look at #414.
