### ISSUE TITLE
Refactor tests to include DisplayNames for classes and better method names

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#411]
In line with our recent change to our style guide, [all classes should be annotated with a display name](https://github.com/Project-Books/book-project/blob/master/STYLEGUIDE.md#using-displayname).

Implement this change. For example, `AuthorTest` would have the display name `@DisplayName("Author should")`.

In addition to adding a display name, refactor the method names so they read nicer as a sentence. For example, in `PredefinedShelfUtilsTest`, the method `testGetPredefinedShelfNamesAsStrings()` could become `returnsCorrectPredefinedShelfNames()`. This way, the 'sentence' would be "PredefinedShelfUtilsTest should returnCorrectPredefinedShelfNames()`.

**Comment by mothinx** [comment]
Hi ! Would love to work on this. Can you assign me ?

**Comment by knjk04** [comment]
Sure, I'll assign you to the issue. Thanks!

**Comment by mothinx** [comment]
I already setup the app.
I see that all unit tests are in src/test/java/com/karankumar/bookproject/backend.  I will implement the changes accordingly to your guideline.
Do you want me to take care of integration tests in src/test/java/com/karankumar/bookproject/ui/  ?

**Comment by knjk04** [comment]
Yes, please!

**Comment by knjk04** [comment]
#421 did a lot of the work for this, so it can be used

**Comment by schrothbn** [comment]
Would work on this if no one else wants that

**Comment by knjk04** [comment]
@schrothbn Thanks again!
