### ISSUE TITLE
Refactor events to new package

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#416]
The following event classes are within `ReadingGoalForm`:

```java
    public <T extends ComponentEvent<?>> Registration addListener(Class<T> eventType,
                                                                  ComponentEventListener<T> listener) {
        return getEventBus().addListener(eventType, listener);
    }

    /**
     * Vaadin's event bus system. A registered listener can be notified when a save or delete event
     * is fired
     */
    public abstract static class GoalFormEvent extends ComponentEvent<ReadingGoalForm> {
        private final ReadingGoal readingGoal;

        protected GoalFormEvent(ReadingGoalForm source, ReadingGoal readingGoal) {
            super(source, false);
            this.readingGoal = readingGoal;
        }

        public ReadingGoal getReadingGoal() {
            return readingGoal;
        }
    }

    public static class SaveEvent extends GoalFormEvent {
        SaveEvent(ReadingGoalForm source, ReadingGoal readingGoal) {
            super(source, readingGoal);
        }
    }

    // TODO: implement deleting reading goal
    public static class DeleteEvent extends GoalFormEvent {
        DeleteEvent(ReadingGoalForm source, ReadingGoal readingGoal) {
            super(source, readingGoal);
        }
    }
```

Refactor this into a new `events` package inside the `ui/goal` package. Each class should be in its own file.

**Comment by harshiniwho** [comment]
Hi! I would like to work on this!

**Comment by knjk04** [comment]
Sure, I'll assign you to the issue. Thanks!

**Comment by harshiniwho** [comment]
Hey! Sorry, but there is something wrong with my local maven configuration/eclipse (it has been a while since I used it). You can un-assign me, so that someone else can work on this!

**Comment by knjk04** [comment]
@harshiniwho OK, thanks for letting us know

**Comment by mareksmelko777** [comment]
Hello, I would like to contribute on this issue. Thanks @knjk04

**Comment by knjk04** [comment]
@mareksmelko777 Sure, I'll assign you to the issue. Thanks!

**Comment by knjk04** [comment]
@mareksmelko777 
How are you getting on with this issue? If you need more time, that's fine, but please let us know.

If you need any help on this, feel free to reach out to us on [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-i7lept44-rgJ9yB0A2vedJTLyyfkjKQ)

**Comment by mareksmelko777** [comment]
@knjk04 I will pull it tonight, thanks for the patience.
