### ISSUE TITLE
Fix orphanAuthorsRemoved() test

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#417]
**Context:**

In `AuthorTest`, this is our current implementation for `orphanAuthorsRemoved()`:

```java
    @Test
    void orphanAuthorsRemoved() {
        Author orphan = new Author("Jostein", "Gardner");
        Book book = new Book("Sophie's World", orphan, toRead);

        bookService.delete(book);

        assertAll(
                () -> assertThrows(RuntimeException.class, () -> authorService.findById(orphan.getId())),
                () -> assertTrue(authorService.findAll().isEmpty())
        );
    }
```

As @schrothbn right pointed out, this test isn't doing anything. 

**What we want to test:**

An `Author` without any books shouldn't exist (i.e. if there an author has one book and that book is deleted, the author should also be deleted).

This test method isn't actually saving `book`. After saving `book`, the `book` should then be deleted. Searching for that `author` should not work and throw an exception (we can remove the second assertion).

**Comment by jhanna60** [comment]
Hey @knjk04  can you set the topic of this repo to Hacktoberfest please? - https://hacktoberfest.digitalocean.com/hacktoberfest-update
Looks like they need that now to be a valid repo.
Many thanks.

**Comment by knjk04** [comment]
@jhanna60 Thanks for bringing this to my attention, I wasn't aware of this change. I've added the topic

**Comment by schrothbn** [comment]
Hey @knjk04  
Sorry, I might miss something, but what should that test actually do? The exception is an IllegalArgumentException because the Author never got saved, so the findById-Method is called with 'null'. So if I don't miss anything important that test is not actually testing anything. If I would try and save the book before the delete-call, I get exceptions from not properly detached Books by the shelf (EntityNotFoundExceptions on already deleted Books, that are still referenced in the shelf) and the Author is still saved (don't know why it would be deleted anywhere). Am I missing something here? To just change the Exception in the assertion to an IllegalArgumentException seems not right to me.
Thanks for clarification.

**Comment by knjk04** [comment]
Hey @schrothbn.

> Sorry, I might miss something, but what should that test actually do?

In our context, an `Author` without a `Book` shouldn't exist. So if we delete a `Book` that has an `Author` without any other books, that `Author` should be deleted.

> So if I don't miss anything important that test is not actually testing anything

You're right. I thought this was first saving the book (which also saved the author), but this isn't the case.

Thanks a lot for bringing this up. I'm going to change this issue. Let us know if you have any other feedback

**Comment by schrothbn** [comment]
I would like to fix that. As far as I see that needs changes in the test-setup (which would probably also fix the todo in that test) as well as changes in the BookService because the Author is not automatically removed with the Book.

**Comment by knjk04** [comment]
Sure, I'll assign you this issue. Thanks! 

> changes in the BookService because the Author is not automatically removed with the Book

I'll need to double-check, but I think we can achieve this using `orphanRemoval`

If you need a hand with this, feel free to get in touch with us over Slack (I saw that you recently joined)

**Comment by schrothbn** [comment]
Hey @knjk04 did you get some time to look into this or should i just PR my changes?

**Comment by knjk04** [comment]
@schrothbn Thanks for following up on this. Honestly, I completely forgot, but I'll take a look today.
