### ISSUE TITLE
Refactor findByPredefinedShelfName() query to return one row

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#418]
**Context**

In `PredefinedShelfRepository`, we currently have

```java
    List<PredefinedShelf> findByPredefinedShelfName(PredefinedShelf.ShelfName shelfName);
```

**What we want**

- Change the return type to return a `PredefinedShelf` (we only want one row back).

- Create a wrapper method (called `findFirstByPredefinedShelfName`) in `PredefinedShelfService` that calls this new repository method

- Then, refactor to remove the now redundant `findPredefinedShelf()` in `PredefinedShelfUtils`. Anything that was calling it can now call the service wrapper, instead

- `findToReadShelf()`, `findReadingShelf()` and `findReadShelf()` can also be removed.

**Comment by YvesBos** [comment]
Hi, I'm willing to work on this one.

**Comment by knjk04** [comment]
Sure, I'll assign you to the issue. Thanks!
