### ISSUE TITLE
Unable to change the name of an author

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#427]
**Describe the bug**

An exception is thrown when there is an attempt to try to change the name of an author.

**To Reproduce**
Steps to reproduce the behaviour:
1. Log in 
2. Go to 'My books'
2. Select a shelf
3. Click on a row
4. Change the name of an author's first or last name
5. See error

**Expected behaviour**

The name should be changed and the grid should update to show the new name.

**Additional context**

Stack trace: https://gist.github.com/knjk04/360e5f6acd35dedaa3c2c26b4d1bd2c3

---

If you need anything, feel free to get in touch with us over [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-h6vx3n8l-KN8QnO50r7QWZHgHFnFdPw).

Please note that this may be tricky to debug and fix

**Comment by Baibhab97** [comment]
@knjk04  I would like to take this up.

**Comment by knjk04** [comment]
Sure, I'll assign you to the issue. Thanks!

**Comment by schrothbn** [comment]
Since my other assigned issue is on hold for now, I can take a look into this one if wanted?

**Comment by knjk04** [comment]
@schrothbn Sure, that would help a lot! Thanks!

**Comment by schrothbn** [comment]
@knjk04 I can't reproduce the exact same stacktrace. The stacktrace suggests that the binder in BookForm is null according to line numbers. I can reproduce wrong behavior though, with different causes/errors.

Can you make sure, that you can still produce that stacktrace with the steps mentioned above on current master version? Just so i know if that specific Exception is os-specific or fixed already or something else.

Thank you.

**Comment by knjk04** [comment]
@schrothbn Thanks for bringing this up. I'll take a look this weekend

**Comment by knjk04** [comment]
@schrothbn Yes, I'm still getting this on master. Which OS, JDK type (e.g. Oracle or Open) and JDK version are you using? Also, could you please post the stack trace that you're seeing

**Comment by schrothbn** [comment]
@knjk04 Ahh i see now. That seems a linux-specific problem then. Initially i tested it on Windows with OpenJDK11 and i didn't get a stacktrace at all, just the wrong behavior and an error popup from Vaadin, that was solved by my commit as well.

On my linux machine i get your stacktrace, will try to figure out how that NPE can happen now.
