### ISSUE TITLE
Refactor the BaseService

### ISSUE THREAD

**Issue by jhanna60** [Project-Books/book-project#429]
Hi there,

As described in the Slack channel I have identified that the BaseService is no longer fit for purpose and propose to refactor this to split up the functionality in the services into relevant Interfaces that the services can then implement. This will support composition over inheritance and better serve the current services.

I'm happy to pick this one if you wish to assign it back to me please.

John

**Comment by knjk04** [comment]
Thanks, @jhanna60!

**Comment by knjk04** [comment]
As discussed in #433, we'll be removing the `BaseService` but not replace it with anything
