### ISSUE TITLE
Refactor book & author filter to use derived query

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#430]
Update: we also need to filter by the chosen shelf

If a user passes in an author or book to filter by, we should use a derived query. This derived query would be implemented in `BookRepository` and there will be a wrapper in `BookService`. It should something like:

```java
List<Book> findByTitleOrAuthorContains(String title, Author author);
```

There should also be accompanying tests to ensure this works as intended. We recommend approaching this using test-driven development.

The filter `filterShelf` in `BookGrid` can be refactored. If no filters are passed in, as before, all books in the chosen shelf should show.

---

If you need anything, feel free to get in touch with us over [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-h6vx3n8l-KN8QnO50r7QWZHgHFnFdPw)

**Comment by esalcidom** [comment]
Hi @knjk04, I would like to help on this.

**Comment by knjk04** [comment]
Sure, I'll assign you to the issue. Thanks!

**Comment by pnpninja** [comment]
Can I work on this? And if i complete before @esalcidom , can you assign me on this and accept my pull request?

**Comment by knjk04** [comment]
@pnpninja Sorry, it's already assigned. 

> And if i complete before @esalcidom , can you assign me on this and accept my pull request?

Sorry, that's not the way we work.

**Comment by knjk04** [comment]
@esalcidom 
How are you getting on with this issue? If you need more time, that's fine, but please let us know.

If you need any help on this, feel free to reach out to us on [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-i7lept44-rgJ9yB0A2vedJTLyyfkjKQ)
