### ISSUE TITLE
Refactor CustomShelfUtils to have static methods

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#434]
Currently, `CustomShelfUtils` is a utility class that needs to be instantiated. Refactor this so that it cannot be instantiated and its methods are all static

---

If you need anything, feel free to get in touch with us over [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-h6vx3n8l-KN8QnO50r7QWZHgHFnFdPw)

**Comment by tw-ayush** [comment]
I can check this.

**Comment by richnavska** [comment]
Hello, this issue is interesting to me and I would like to contribute on it. Thank you!

**Comment by pnpninja** [comment]
Hi, Please assign me the issue as I have already written the fix for it

**Comment by knjk04** [comment]
@tw-ayush Thanks, I'll assign you to the issue!

**Comment by knjk04** [comment]
@richnavska Sorry, this issue has already been requested

**Comment by knjk04** [comment]
@pnpninja  Sorry, this issue has already been requested

**Comment by tw-ayush** [comment]
@knjk04 you mind adding the hacktoberfest-accepted label as well?

**Comment by knjk04** [comment]
@tw-ayush Oops, I've added it to the PR
