### ISSUE TITLE
Update table of contents in contributing document

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#442]
New sections have been added to the contributing document that needs to be added to the table of contents with links. They also need to be correctly indented in the table of contents.

**Comment by Meena-dev** [comment]
I would like to work on this issue.

**Comment by knjk04** [comment]
Sure, I'll assign you to the issue. Thanks!

**Comment by Meena-dev** [comment]
Thank you. Working on this.
Found below sections to included in contents with links.
**Open-ended discussions
New contributors assigned to at most one issue at a time
Ensure your email address on your commits are correct
Rewriting pushed commits with a different email address
squashing commits
new files
Merge Conflicts
Resolving conversations**

Confirm if anything is missing ? 
Do I need to create a new branch for this change and commit or I can commit to master branch?

**Comment by Meena-dev** [comment]
I have done the changes and created pull request. Please verify and let me know if anything is required.

**Comment by knjk04** [comment]
@Meena-dev Thanks, we'll review your pull request shortly. I noticed that you included all of the sections that need to be added to the table of contents, so that's good
