### ISSUE TITLE
Create wireframes for homepage

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#449]
Create a mockup design for the homepage that uses [Material UI](https://material-ui.com/) React components.

This may require lots of toing and froing, so feel free to go through this process on Slack.

**Comment by ofvoler** [comment]
I'd like to be assigned to this!

**Comment by knjk04** [comment]
Thanks! As discussed offline, I'll block this issue until we come up with some requirements

**Comment by knjk04** [comment]
Closing as we're now using Jira for design
