### ISSUE TITLE
Update Slack invite links

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#454]
The Slack invite links have expired, so they need to be updated with a new link

**Comment by awkwardblackcoder** [comment]
> The Slack invite links have expired, so they need to be updated with a new link

Hi, I would like to work on this issue but would need more information. Where can I find the new Slack invite links?

**Comment by knjk04** [comment]
Hi. Unfortunately, I'm already assigned to this issue (and I'm working on this). Feel free to request to be assigned to an unblocked and unassigned issue
