### ISSUE TITLE
Add publisher entity

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#455]
**Describe the solution you'd like**
Add a publisher entity. There should be a one-to-many relationship between a `Publisher` and a `Book` (where a `Publisher` is the owner).

For now, the publisher entity should contain only one field (besides an ID that is inherited from `BaseEntity`): a name.

There only needs to be a respective repository and service.

**Additional context**
This is a backend-only change.

Update: there should be a many-to-many relationship

**Comment by jhanna60** [comment]
Hey can I take this one please

**Comment by pnpninja** [comment]
can i take this pleae?

**Comment by knjk04** [comment]
@jhanna60 Thanks for expressing an interest in this. Unfortunately, we only [assign one issue at a time to new contributors](https://github.com/Project-Books/book-project/blob/master/CONTRIBUTING.md#new-contributors-assigned-to-at-most-one-issue-at-a-time). Once you've completed your other issue, if this issue is still unassigned (e.g. if the person that this is assigned to drops out), feel free to request to be assigned

**Comment by knjk04** [comment]
@pnpninja Sure, I'll assign you to the issue

**Comment by pnpninja** [comment]
Delivery time - 24 hours from now

**Comment by pnpninja** [comment]
Hey, I added the model, repo and service.

I'll add the tests and then we can merge

**Comment by pnpninja** [comment]
Hey - i needed some clarifications about the tests.

I see that Book takes the Author in its constructor. What about Publisher? Do we take that in the constructor? Or do we just keep that an optional parameter?

**Comment by pnpninja** [comment]
Please review PR

**Comment by knjk04** [comment]
> I see that Book takes the Author in its constructor. What about Publisher? Do we take that in the constructor? Or do we just keep that an optional parameter?

Having it as an optional parameter would be good for now. Thanks!

**Comment by knjk04** [comment]
@jhanna60 Are you still interested in working on this?

**Comment by abhity16** [comment]
Is this still open ?
Also, slack link is expired

**Comment by knjk04** [comment]
@abhity16 Yes, this is still available. Would you be interested in picking this up? 

Thanks for the heads-up. I've deleted the Slack link from the post. You can find the Slack link by clicking on the 'chat on slack' badge in the README

**Comment by abhity16** [comment]
Thanks @knjk04 . I'll take up this task. 
Also, chat on slack badge link (https://teambookproject.slack.com/join/shared_invite/zt-i7lept44-rgJ9yB0A2vedJTLyyfkjKQ#/) is also expired.

**Comment by knjk04** [comment]
@abhity16 Thanks, I'll assign you to the issue.

Apologies, I have updated it now on the README. Here's the link: https://join.slack.com/t/teambookproject/shared_invite/zt-jcijyenp-JiKFGBv62FIPoFnvOW6Ubg
