### ISSUE TITLE
Add Book format

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#456]
**Describe the solution you'd like**

A user may want to keep track of different types of books. The `Book` entity should have a `BookFormat` enum as a member. For now, the `BookFormat` enum should contain the following values:

- Hardback
- Paperback
- eBook

---
If you need a hand with this, feel free to get in touch with us over our [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-i7lept44-rgJ9yB0A2vedJTLyyfkjKQ) workspace

**Comment by GxPinheiro** [comment]
Could I get this issue ?

**Comment by knjk04** [comment]
Sure, I'll assign you to the issue. Thanks!

**Comment by GxPinheiro** [comment]
Finished could you check please? 
If everything is fine will check other issues
