### ISSUE TITLE
Add ISBN to book

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#457]
**Describe the solution you'd like**
Add a member for the `Book` entity to store ISBN (13). This should be stored as a String.

**Additional context**
This is a backend-only change.

---

If you need a hand with this, feel free to get in touch with us over our [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-i7lept44-rgJ9yB0A2vedJTLyyfkjKQ) workspace

**Comment by Anca07** [comment]
Hi! I would like to work on this issue :)

**Comment by shwhite17** [comment]
I would like to work on this issue, assign to me.

**Comment by knjk04** [comment]
@Anca07 Sure, I'll assign you to the issue. Thanks!

**Comment by knjk04** [comment]
@shwhite17 Sorry, Anca got there before you. Feel free to request to be assigned to another unblocked and unassigned issue
