### ISSUE TITLE
Add Language enum

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#458]
**Describe the solution you'd like**
Add a `Language` enum that contains a list of different languages that a book can be in. 

More details to follow on what languages we want to initially include soon

**Comment by tw-ayush** [comment]
One option is - With MySQL you can actually create a type enum in db and JPA allows to enumerate a value in code (implies easy ORM).
But if the number of languages grow beyond let say 10 or 15 creating a type enum will not be good option, also each book in a different language will become a new entry in DB and thus not very user friendly.

What can be done here is adding another table like stock table with many-to-one mapping on books table. With a column named language being a foreigner key from language table this gives scalability and also Language wise in stock value can be maintend.

**Comment by tw-ayush** [comment]
@knjk04 any thoughts?

**Comment by pnpninja** [comment]
@tw-ayush I agree with your opinion. @knjk04 needs to sign off. @knjk04 can I take this?

**Comment by knjk04** [comment]
@tw-ayush Thanks for your suggestion. I'll look into this over the weekend

**Comment by tw-ayush** [comment]
> @tw-ayush Thanks for your suggestion. I'll look into this over the weekend

@knjk04 Cool lemme know once done.
@pnpninja actually i wanted to sign-up for this if you don't mind.

**Comment by knjk04** [comment]
@tw-ayush Apologies, I completely forgot about this. I've made a note to look into this

**Comment by knjk04** [comment]
@tw-ayush Apologies, I completely forgot about this. What if we were to have an enum in Java to represent the languages and have each book contain a set of languages?

**Comment by tw-ayush** [comment]
> @tw-ayush Apologies, I completely forgot about this. What if we were to have an enum in Java to represent the languages and have each book contain a set of languages?

Hey I was thinking of the solution from a different prospective.
Using a Language table maybe more useful. 'cause instead of repeating the whole book information multiple times (for say a million books with on average 4 languages means 4 million complete information or instead we can have 4 million mappings entry). IMO we can create a table for languages, a relationship mapping and definitely the book can have a set of languages in the entity, and an enum for each language.

**Comment by knjk04** [comment]
@tw-ayush I'm so sorry, I missed your message again. I didn't get notified for some reason.

I think the language table is a good idea.
