### ISSUE TITLE
Add a new REST endpoint to manage Book resource

### ISSUE THREAD

**Issue by amit1307** [Project-Books/book-project#463]
**This feature is to enable the UI migration from Vaadin to JS**
A new REST endpoint should be able to:

- Add a new book
- Update an existing book
- Get an existing book
- Delete an existing book

**Describe the solution you'd like**
The solution would be to introduce a new REST endpoint for managing Book resource. The endpoint would expose the APIs to achieve below:

- Save a new book into the db
- Update an existing book
- Search a book by some criteria
- Delete and existing book

The media type for request and response should be in JSON format. There shouldn't be any breaking changes in service and dao layer so that there is no impact on the existing Vaadin UI.

**Comment by tw-ayush** [comment]
I guess on the back end it can be achieved by just adding CRUD methods on BookRepo.

**Comment by knjk04** [comment]
@tw-ayush I was thinking we could add the new mappings in a new class within a new controller package. What do you think, @amit1307?

**Comment by amit1307** [comment]
Sorry I didn't get both the comments. 
> I guess on the back end it can be achieved by just adding CRUD methods on BookRepo.

What do we exactly mean by that? Are we saying by doing that we don't need to expose the APIs? 

>I was thinking we could add the new mappings in a new class within a new controller package.

What do we mean by mappings here?

**Comment by amit1307** [comment]
> > What do we mean by mappings here?
> 
> Mapping request methods onto methods, e.g. the `@GetMapping`, `@RequestMapping` and `@DeleteMapping` annotations.

Oh okay got it now, I think we should have a separate class for that which just defines all our exposed end points and what they return/accept/query params etc. That class should receive the client request and convert it into our domain object and delegate the request to our service layer for further processing. In future we would also want to include some security for our APIs. Having them in a dedicated class can avoid any regression in any app layer when there are changes specific to the exposed APIs.

**Comment by tw-ayush** [comment]
> Oh okay got it now, I think we should have a separate class for that which just defines all our exposed end points and what they return/accept/query params etc. That class should receive the client request and convert it into our domain object and delegate the request to our service layer for further processing. In future we would also want to include some security for our APIs. Having them in a dedicated class can avoid any regression in any app layer when there are changes specific to the exposed APIs.

yup this is what i was talking about.
Adding a controller, service/business and then a DAO/Repo/IO layer.

**Comment by tw-ayush** [comment]
I can sign up for this.

**Comment by amit1307** [comment]
> I can sign up for this.

Hey sorry but this issue is already assigned, would you like to have a look at other issues (there are plenty of them!)

**Comment by tw-ayush** [comment]
> Hey sorry but this issue is already assigned, would you like to have a look at other issues (there are plenty of them!)

oh i didn't know you were gonna work on it. But yes i'll have a checkout on other issues.

**Comment by knjk04** [comment]
This is blocked while we look into whether we want to use REST or GraphQL

**Comment by knjk04** [comment]
Closing as we'll be using GraphQL

**Comment by knjk04** [comment]
Re-opening as we'll be using REST for the time being (better and more documentation available, but we'll continue to use GraphQL for the Books API).

@amit1307 Are you still happy to work on this?

**Comment by knjk04** [comment]
@amit1307 I'll assign you as we need to work on this now.

@tw-ayush Are you still interested in working on this issue?

**Comment by kateerfle** [comment]
Hi Karan, could I work on this issue?

**Comment by knjk04** [comment]
Hi Kate, sure. Thanks!
