### ISSUE TITLE
Design a new logo

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#464]
Our logo is good, but it could be better. Design a logo that's a calligraphy drawing. It should contain the name 'Book Project' and be clearly legible.

The background should be transparent. 

Deliverables: png at a fairly high resolution so that we can downscale it as needed.

**Comment by ofvoler** [comment]
I'd like to do this one!

**Comment by knjk04** [comment]
Thanks!

**Comment by knjk04** [comment]
(Discussed over Slack)
