### ISSUE TITLE
Fix serialize-javascript vulnerability

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#468]
serialize-javascript has a vulnerability on versions before 3.1.0. This should be updated without breaking anything.

For information on why this is an issue: https://github.com/advisories/GHSA-hxcc-f52p-wc94

**Comment by tmrd993** [comment]
`npm audit` shows several additional errors for me. I fixed all of them along with the serialize-javascript vulnerability.

These are the errors shown. Can you verify if you get the same errors?
```PS C:\Users\Timucin\maven procs\book-project> npm audit
npm ERR! code ELOCKVERIFY
npm ERR! Errors were found in your package-lock.json, run  npm install  to fix them.
npm ERR!     Invalid: lock file's @vaadin/vaadin-core-shrinkwrap@14.3.7 does not satisfy @vaadin/vaadin-core-shrinkwrap@14.3.4
npm ERR!     Invalid: lock file's @vaadin/vaadin-dialog@2.4.5 does not satisfy @vaadin/vaadin-dialog@2.4.3
npm ERR!     Invalid: lock file's @vaadin/vaadin-radio-button@1.3.1 does not satisfy @vaadin/vaadin-radio-button@1.3.0
npm ERR!     Invalid: lock file's @vaadin/vaadin-text-field@2.6.3 does not satisfy @vaadin/vaadin-text-field@2.6.2
npm ERR!     Invalid: lock file's serialize-javascript@2.1.2 does not satisfy serialize-javascript@^5.0.1
npm ERR!     Invalid: lock file's webpack-dev-server@3.11.0 does not satisfy webpack-dev-server@3.10.3```

**Comment by wpater** [comment]
Hello, I would like to fix this issue. 
I know that you @tmrd993 were first, if you want you can take it.

**Comment by knjk04** [comment]
@tmrd993 Do the errors go away if you run `npm install`? 

Also, would you be interested in picking up this issue?

**Comment by tmrd993** [comment]
> 
> 
> @tmrd993 Do the errors go away if you run `npm install`?
> 
They do.
> Also, would you be interested in picking up this issue?
Sure but since @wpater already made a commit, I'll let him take this one.
