### ISSUE TITLE
Make password strength tests parameterized

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#479]
In `UserTest.java` , we have the following three tests:

```java
void testWeakPasswordIsInvalid() {
    // given
    User user = userWithoutPassword().password("123456789")
                                     .build();
    // when
    tryToSaveInvalidUser(user);
    // then
    assertThat(userRepository.count()).isEqualTo(initialNumberOfUsers);
}
@Test
void testFairPasswordIsInvalid() {
    // given
    User user = userWithoutPassword().password("aPassWorD")
                                     .build();
    // when
    tryToSaveInvalidUser(user);
    // then
    assertThat(userRepository.count()).isEqualTo(initialNumberOfUsers);
}
@Test
void testGoodPasswordIsInvalid() {
    // given
    User user = userWithoutPassword().password("testPa$$123")
                                     .build();
    // when
    tryToSaveInvalidUser(user);
    // then
    assertThat(userRepository.count()).isEqualTo(initialNumberOfUsers);
}
```

**Context:**

'Weak', 'fair' and 'good' refer to password strengths (you can try this out by running the app). The problem here is that the shape of each of these three tests are the same: we construct an invalid user, try to save it and then assert that the number of users saved (userRepository.count()) has not changed (== initialNumberOfUsers).

**What we want:**

We want to eliminate the code duplication. As you may have noticed, the only thing that's changing is the password. We can combine these three tests into one and pass in as input strings that correspond to a weak, fair and good password. The way we do this in JUnit is by creating a parameterised test

**Comment by knjk04** [comment]
This issue has already been offered to someone. If they do not claim it within seven days, we will open this up to everyone else

**Comment by SeonghoLee4** [comment]
I would like to be assigned to this one!

**Comment by knjk04** [comment]
@SeonghoLee4 Thanks!

**Comment by knjk04** [comment]
@SeonghoLee4 Just checking up again -- how are you getting on with this? I think the changes should be relatively quick and straightforward, but feel free to reach out on Slack if you need a hand

**Comment by SeonghoLee4** [comment]
> @SeonghoLee4 Just checking up again -- how are you getting on with this? I think the changes should be relatively quick and straightforward, but feel free to reach out on the #help channel on Slack if you need a hand

checked! I will update you soon.

**Comment by knjk04** [comment]
@SeonghoLee4 I know you said you'll update us soon, but in line with our contributing guidelines (see [here](https://github.com/Project-Books/book-project/blob/master/CONTRIBUTING.md#stale-issues--pull-requests)), I'm just checking up again after seven days of inactivity. How are you getting on with this?

**Comment by knjk04** [comment]
(Discussed on Slack. PR expected by the end of the week)
