### ISSUE TITLE
'Good' password is valid

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#481]
**Describe the bug**

In `UserTest.java`, a user with a 'good' password is saved in `testValidUserSaved()`. 

This appears to only affect the backend.

**Expected behaviour**

We should only allow strong and very strong passwords on the backend.

We also need to update the test so that it still passes (i.e. a 'strong' password is passed in)

**Additional context**

- [Test zxcvbn](https://lowe.github.io/tryzxcvbn/)
- [zxcvbn4j](https://github.com/nulab/zxcvbn4j): The Java port of zxcvbn we are using

---

If you need a hand with this, feel free to get in touch with us over our [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-i7lept44-rgJ9yB0A2vedJTLyyfkjKQ) workspace

Update: the method was renamed to `beSavedIfValid()`

**Comment by shreyanshrs44** [comment]
@knjk04 I would like to work on this issue, can you please assign this to me ? Thanks

**Comment by knjk04** [comment]
@shreyanshrs44 Sure, I'll assign you to the issue. Thanks!

**Comment by shreyanshrs44** [comment]
@knjk04 
1. We need to write test-case to check for Strong passwords.
2. In test testValidUserSaved() we should only allow user with Strong passwords to be saved.
Am I correct ?

**Comment by knjk04** [comment]
@shreyanshrs44 I've updated the issue description (the method name has changed).

> We need to write test-case to check for Strong passwords.

We have a test for that `beSavedIfValid()` (formerly `testValidUserSaved()`, but it's currently accepting a 'good' password, which should not be allowed.

> In test testValidUserSaved() we should only allow user with Strong password to be saved. Am I correct ?

Correct. We'll need to modify the backend to not allow 'good' passwords

**Comment by knjk04** [comment]
@shreyanshrs44 As we're nearing the end of the month, I think it's unlikely we'll be able to review & merge your PR in before the end of Hacktoberfest. I'll remove the 'hacktoberfest' label. 

Are you still interested in working on this? If so, could you please let us know when this will be completed by? As it is a high-priority bug, we need to get this fixed as soon as possible

**Comment by knjk04** [comment]
@shreyanshrs44 
How are you getting on with this issue? If you need any help on this, feel free to reach out to us on [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-i7lept44-rgJ9yB0A2vedJTLyyfkjKQ)

If you need more time, that's fine, but please let us know.

**Comment by shreyanshrs44** [comment]
@knjk04 Sorry for not responding back :( . TBH I am still half way in looking into this issue.

**Comment by knjk04** [comment]
@shreyanshrs44 That's fine. Thanks for letting us know

**Comment by knjk04** [comment]
@shreyanshrs44 Just checking up again -- how are you getting on with this? Also, could you please let us know when you have this finished by?

**Comment by knjk04** [comment]
@shreyanshrs44 Unfortunately, as we have not heard back from you in a while, I will unassign you from the issue. This is in line with our contributing guidelines.

**Comment by ofvoler** [comment]
I'm not sure if I can commit to working on this, but I was looking into code issues and this one seems like it should be fairly easy. Do you know off the top of your head if this is just an issue with UserTest.java, or is it something with User.java as well? In User it looks like we're already checking to make sure the password strength is strong.

**Comment by knjk04** [comment]
@ofvoler I don't think the test is wrong. My hunch is that something's wrong with the strength validation

**Comment by ofvoler** [comment]
Okay, I don't think that's something I'm equipped to take on then. Thanks for your response though!

**Comment by shubhamsinghrathi** [comment]
I just checked that "password_12345" is considered as Strong password but "password@12345" as Good and "password$12345" as Fair. I have already raised an issue regarding this on Zxcvbn (https://github.com/nulab/zxcvbn4j/issues/77).
In my opinion, we can either wait for the fix from Zxcvbn or go with some other library.

**Comment by knjk04** [comment]
@shubhamsinghrathi Thanks for checking this. We'll wait to see what they say first

**Comment by knjk04** [comment]
@shubhamsinghrathi It looks like this isn't an issue, so I'll close this
