### ISSUE TITLE
Add instructions for upstream

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#486]
Add instructions to the contributing document that link to GitHub's documentation on creating an upstream remote so that contributors can keep their fork in sync with this repository

**Comment by arjunrc143** [comment]
Hi @knjk04 Can I take this up?

**Comment by arjunrc143** [comment]
Created a PR: Please review: https://github.com/Project-Books/book-project/pull/497

**Comment by knjk04** [comment]
@arjunrc143 Unfortunately, this issue is unassigned. Feel free to request to be assigned to an unblocked and unassigned issue.

**Comment by arjunrc143** [comment]
@knjk04 Can you please assign this to me?

**Comment by knjk04** [comment]
@arjunrc143 Unfortunately, as I have already mentioned, this issue is assigned

**Comment by arjunrc143** [comment]
Ok cool. I think there is a typo in the other comment, assigned to unassigned :P. Will check other issues. Thanks
