### ISSUE TITLE
Add year of publication to the Book entity 

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#493]
**Describe the solution you'd like**
Add a year of publication attribute to the `Book` entity. This should be an optional field.

---

If you need a hand with this, feel free to get in touch with us over our [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-i7lept44-rgJ9yB0A2vedJTLyyfkjKQ) workspace

**Comment by michiboo** [comment]
Hi Can I have a go at this issue?

**Comment by knjk04** [comment]
@michiboo Sure, I'll assign you to the issue. Thanks!

**Comment by spinnycodess** [comment]
can i try this? hopefully i will know what to do, total n00b

**Comment by knjk04** [comment]
@spinnycodess Sorry, this is already assigned. Feel free to request to be assigned to an unblocked and unassigned issue
