### ISSUE TITLE
Replace deprecated class

### ISSUE THREAD

**Issue by QasimKhan5x** [Project-Books/book-project#494]
Upon building the project, I got two warnings of a deprecated class in [SecurityUtils.java](https://github.com/Project-Books/book-project/blob/master/src/main/java/com/karankumar/bookproject/security/SecurityUtils.java). The ServletHelper class was being used, which is deprecated as per [Vaadin guidelines](https://vaadin.com/api/platform/14.4.1/deprecated-list.html). I have replaced it and its usages with the HandlerHelper class as recommended in the Vaadin documentation.
Now, building the project doesn't result in any warnings.

**Comment by knjk04** [comment]
@QasimKhan5x Thanks for bringing this to our attention. Would you be interested in creating a pull request for this?

**Comment by QasimKhan5x** [comment]
> @QasimKhan5x Thanks for bringing this to our attention. Would you be interested in creating a pull request for this?

yes

**Comment by QasimKhan5x** [comment]
@knjk04 can I be assigned this issue, please?

**Comment by knjk04** [comment]
@QasimKhan5x Thanks, I've assigned you to the issue
