### ISSUE TITLE
Unable to change the name of an author

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#500]
**Describe the bug**

Unable to change the name of an author.

**To Reproduce**
Steps to reproduce the behaviour:
1. Log in
2. Go to 'My books'
3. Select 'All books'
4. Select an author
5. Change the first name
6. See error

**Expected behaviour**

The author name changes

**Additional context**

[Stack trace](https://gist.github.com/knjk04/1ec9ca9d9a02f1ff3e61e75deefb905a)

**Comment by elpsio** [comment]
Hello, I would love to tackle this issue. Gonna look into it starting from tomorrow. Would you be okay with that?

**Comment by knjk04** [comment]
@elpsio Thanks for taking an interest in this issue!

As this is a high-priority issue, we're looking to have this completed as soon as possible -- ideally within a week after being assigned.

Are you fine with this? If so, I can assign you to the issue

**Comment by elpsio** [comment]
@knjk04 yea I am fine with that. :) Thank you!

**Comment by knjk04** [comment]
@elpsio Great, thanks!

If you need a hand with this, feel free to get in touch with us over our [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-i7lept44-rgJ9yB0A2vedJTLyyfkjKQ) workspace
