### ISSUE TITLE
Replace NotEmpty annotations with NotBlank

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#508]
Replace `NotEmpty` annotations with `NotBlank` (or add the annotation for the fields that don't have a `NotEmpty` annotation) for the following fields:
- Author `firstName`
- Author `lastName`
- Book `title`
- Shelf `shelfName`
- Tag `name`

There should also be accompanying tests so that if an annotation were to be removed, we got informed by virtue of a failing test.

**Comment by knjk04** [comment]
This has been offered to someone on Slack. However, if they don't wish to pick this up, this issue will be offered to everyone else

**Comment by kateerfle** [comment]
Hi, I would like to be assigned to this issue!

**Comment by knjk04** [comment]
@kateerfle Thanks! Feel free to reach to us on Slack if you need anything

**Comment by knjk04** [comment]
@kateerfle Could you please skip the `CustomShelf`/`Shelf` class? I forgot to mention this earlier. We shouldn't have the `@NonNull` annotation in `CustomShelf`

**Comment by knjk04** [comment]
@kateerfle How are you getting on with this?
