### ISSUE TITLE
Do not allow pages read to be > number of pages

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#517]
**Describe the bug**

For the did not finish shelf, we have both the 'pages read' and the 'number of pages' form fields. The 'pages read' value can be greater than the 'number of pages' value.

**To Reproduce**
Steps to reproduce the behaviour:
1. Log in
2. Go to 'my books'
2. Click on 'add book'
3. Select the 'did not finish' primary shelf
4. Enter in a value for the number of pages field
5. Enter in a value for the pages read field that is strictly greater than the value entered in for the number of pages field
6. See error (book saved)

**Update:** a custom shelf will also need to be chosen (you'll need to create one first). There's an open bug issue for this

**Expected behaviour**

If the user has entered in a value for the 'number of pages' form field, this should be strictly greater than the number entered into the 'number of pages' form field (since the user has not finished reading the book).

**Comment by vvkpd** [comment]
I would like to work on this card, could you please assign to me.
Thanks

**Comment by knjk04** [comment]
@vvkpd Sure. Thanks again, Vivek!

**Comment by knjk04** [comment]
@vvkpd How are you getting on with this?

**Comment by vvkpd** [comment]
last week I was not feeling well. I started working on it. I need some time @knjk04

**Comment by ZackHollander** [comment]
IS this still available to take?

**Comment by knjk04** [comment]
@ZackHollander Yes, it is. I'll assign you to it. Thanks
