### ISSUE TITLE
Add tests to CustomShelfService

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#525]
The following methods/functionality need to be tested:
- Test that `findById()` successfully returns the correct `CustomShelf` when a valid ID is passed in 
- A custom shelf can be successfully deleted
- `findAll(String shelfName)` returns a list of all custom shelves if the parameter is null

**Comment by knjk04** [comment]
This issue has been offered to someone as their issue was accidentally duplicated. If they do not respond or wish to pick this up, this will be offered to everyone else

**Comment by sdahule** [comment]
@knjk04  can you assign this issue to me if its still pending.

**Comment by knjk04** [comment]
@sdahule Sure, I'll assign you to the issue. Thanks!

**Comment by knjk04** [comment]
@sdahule How are you getting on with this issue? If you need any help on this, feel free to reach out to us on [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-i7lept44-rgJ9yB0A2vedJTLyyfkjKQ)

If you need more time, that's fine, but please let us know.

**Comment by sdahule** [comment]
Hi karan,
Yes i am working on it. Need some time. Should br able to push the changes
by next week.

**Comment by knjk04** [comment]
@sdahule That's fine. Thanks for the update

**Comment by knjk04** [comment]
@sdahule Just checking up again. How are you getting on with this?

**Comment by knjk04** [comment]
@sdahule As we have not heard back from you in a while, despite following up, I will unassign you from the issue. This is in line with our contributing guidelines
