### ISSUE TITLE
Move methods from PredefinedShelf utility class to service

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#533]
Move the methods in `PredefinedShelfUtils` that use the service method and remove the `predefinedShelfService` member. The remaining methods can be made static. It should be possible to use this class without needing to instantiate it

**Comment by Artamm** [comment]
Hello, I would like to assign for this issue, if it's possible.

**Comment by knjk04** [comment]
@Artamm Sure, I'll assign you to the issue. Thanks!
