### ISSUE TITLE
Add more DateUtil tests

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#535]
Add tests for:
- calculateWeeksLeftInYearFromCurrentWeek
- dateIsInCurrentYear()

Edge cases should also be handled

**Comment by loganrouleau** [comment]
Can I take this as a first issue? I just got my dev setup running, and it looks like a good place to jump in.

I'll review the 2 existing DateUtil tests as well. They pass when you unignore them but they might be missing edge cases.

**Comment by knjk04** [comment]
@loganrouleau Sure, I'll assign you to the issue. Thanks!

What OS are you using?

**Comment by loganrouleau** [comment]
Thanks. I'm on Windows.

**Comment by knjk04** [comment]
On Windows, some of the date tests were failing for me. They worked fine in my IDE (IntelliJ), but not when I run the app with Maven or if I ran `mvn test`. Could you also try this to ensure it works?

**Comment by loganrouleau** [comment]
Ah, ok. I'm also using IntelliJ. I'll run them through maven tomorrow and report back.

**Comment by knjk04** [comment]
Thanks. Also, if you haven't already, see #311 for some more information on the failing date util tests

**Comment by loganrouleau** [comment]
I left a comment on 311. I've Disabled the new tests here for now.
