### ISSUE TITLE
Form validation errors shown prematurely

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#54]
**Describe the bug**

After clicking on the 'add book' button, the form validation errors show when before the user has done anything. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on 'add book'
2. See error

**Expected behaviour**

A blank form (without any validation errors) should show when the form is first presented to the user.

**Screenshots**

![image](https://user-images.githubusercontent.com/11173328/85138474-bbfd2c00-b23a-11ea-902f-62d40c235678.png)

**Comment by Anu-123-gif** [comment]
I would like to work on this issue , please assign it to me

**Comment by knjk04** [comment]
Unfortunately, as per our [contributing guidelines](https://github.com/Project-Books/book-project/blob/master/CONTRIBUTING.md#tell-us-which-issue-you-want-to-work-on), we only assign one issue at a time for new contributors. 

If after completing your currently assigned this issue is still available, feel free to request to be assigned to it!

**Comment by shreyamodi1999** [comment]
Hey! Can I work on this?

**Comment by knjk04** [comment]
@shreyamodi1999 Apologies for the delay, this slipped past me. Sure, I'll assign you to the issue! 

If you need a hand with this, feel free to get in touch with us over our [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-i7lept44-rgJ9yB0A2vedJTLyyfkjKQ) workspace

**Comment by knjk04** [comment]
@shreyamodi1999 
How are you getting on with this issue? If you need more time, that's fine, but please let us know.

If you need any help on this, feel free to reach out to us on [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-i7lept44-rgJ9yB0A2vedJTLyyfkjKQ)

**Comment by Anu-123-gif** [comment]
@knjk04 is this issue still open ,if so can I work on this now?

**Comment by knjk04** [comment]
@Anu-123-gif For now, this is closed. In line with our contributing guidelines, if Shreya does not respond in five more days, I'll unassign Shreya. Only then can I assign it to you

**Comment by knjk04** [comment]
@shreyamodi1999 Unfortunately, as we have not heard back from you in a while, I will unassign you from the issue. This is in line with our contributing guidelines.

**Comment by knjk04** [comment]
@Anu-123-gif It's all yours

**Comment by knjk04** [comment]
@Anu-123-gif How are you getting on with this issue? If you need any help on this, feel free to reach out to us on [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-i7lept44-rgJ9yB0A2vedJTLyyfkjKQ)

If you need more time, that's fine, but please let us know.

**Comment by Anu-123-gif** [comment]
> .

Yes please give me more time I was a bit busy

**Comment by knjk04** [comment]
@Anu-123-gif Sure, no problem. Could you please give us an idea of when you'll have this finished?

**Comment by knjk04** [comment]
Unassigning at your request
