### ISSUE TITLE
Statistic Page get NullpointerException for newly registered user

### ISSUE THREAD

**Issue by zoyolet** [Project-Books/book-project#543]
**Describe the bug**
when I register and try to enter the statistic page it shows nullpointer exception

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Home page' after login
2. Click on 'Statistic page'
3. See error

**Expected behaviour**

this page should show empty data

**Comment by knjk04** [comment]
@zoyolet Thanks for bringing this up! We'll look into this

**Comment by zoyolet** [comment]
could you assign me to solve this issue?

**Comment by knjk04** [comment]
@zoyolet Sure, thanks! If there's no statistics available, could you please show a heading that says 'No statistics available. Try adding some books'

**Comment by zoyolet** [comment]
ok I will do that
