### ISSUE TITLE
Add show/hide password toggle

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#560]
**Describe the solution you'd like**
Add an input adornment that's an icon to toggle showing and hiding the password. We need to use the icon in Material UI

**Additional context**
See [input adornments](https://material-ui.com/components/text-fields/#input-adornments)

**Comment by wesleynepo** [comment]
Are this issue available?

**Comment by knjk04** [comment]
@wesleynepo You can take this issue as I haven't finished it yet. Could you please create your branch from the `0.2.0` branch? Feel free to reach out to us on Slack if you need anything

**Comment by knjk04** [comment]
@wesleynepo How are you getting on with this?

**Comment by knjk04** [comment]
Unassigning at your request (privately on Slack)

**Comment by RivaD2** [comment]
@knjk04, hi again!
  Looks like this issue is available. I'd be happy to take this one on  :)

**Comment by knjk04** [comment]
@RivaD2 Hi, thanks!

**Comment by RivaD2** [comment]
@knjk04 It looks like this could be done in the Login component or in the Password component. My approach would probably be to do this in the Password component and add a passwordToggle method. I would then pass it into the `onClick()` prop. 

Using material UI I would bring in the `Input Adornment` (which it looks like is already imported in), add the icon then give it some styles so it sits in the right place.I can do this inline or I can create a css file. I will probably choose the small/medium icon as well.

So for this issue, I am under the impression I need to focus on just the icon and password toggle. From what I remember, the form itself was already built out.

Thanks for your input on this, I want to make sure I am headed in the right direction :)

**Comment by knjk04** [comment]
@RivaD2 Your implementation approach sounds good. By having the toggle in the password component, we will also have it in other components that use the password component (the register view and the login view).

**Comment by RivaD2** [comment]
@knjk04 I received your message about rebasing/bringing my branch up-to-date with 0.2.0. I am on it :)

**Comment by RivaD2** [comment]
@knjk04 hello there! :)  I was looking around fo new issues and saw this one is open still. Shall I close it?

**Comment by knjk04** [comment]
@RivaD2 Yes, please. Thanks for staying around to help more!

**Comment by RivaD2** [comment]
@knjk04 Looks like I am unable to close the issue:) Perhaps because I am not yet a collaborator or something of the sort.

**Comment by knjk04** [comment]
Oh, I'll close it then
