### ISSUE TITLE
Create login controller

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#563]
**Describe the solution you'd like**
Create a REST endpoint that takes in a username and a password and returns back whether it is associated to an account

**Comment by tw-ayush** [comment]
Do you plan to use a JWT token or some other auth methods.

**Comment by knjk04** [comment]
We're using JWT, see #591

**Comment by tw-ayush** [comment]
Then what is the scope of this API, i guess you are not expecting a token in response.

**Comment by knjk04** [comment]
I've blocked this for the time being. I can't quite remember why I made this issue as I know there's already a /login endpoint. 

We are expecting a token back, but that should be set up.
