### ISSUE TITLE
Create endpoint for creating a new account

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#564]
**Describe the solution you'd like**
In a new controller, create an endpoint that allows a user to POST a username/email address and a password to create a new account. We need to send back an error if the password strength is not sufficiently strong or if the username/email address is already is use.

**Comment by abhity16** [comment]
Hi @knjk04 
Are you working on this?
If not, Can I take it up.

**Comment by knjk04** [comment]
Hi @abhity16,

Thanks for your interest! 

I've implemented this (it's merged in, but I was meant to close this). We need to create a lot more endpoints, however, so feel free to keep an eye out!
