### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#566]
**Describe the solution you'd like**
Replace the default React favicon with our favicon

**Additional context**
Branch from `0.2.0` and set the destination branch of your pull request back to `0.2.0`

[Favicon png](https://user-images.githubusercontent.com/11173328/103422792-16d4f000-4b9b-11eb-9cd9-eff98cee1ae9.png) (convert this to a `.ico` file and replace the existing `favicon.ico`)

**Comment by knjk04** [comment]
To add the icon to include in this issue soon

**Comment by ZackHollander** [comment]
I would like to take this.
