### ISSUE TITLE
Show error messages on log in clicked

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#567]
**Describe the solution you'd like**
When the user clicks on the 'log in' or 'create account' buttons, error messages should appear for password and confirm passwords fields if they were left blank (or if the confirmed password does not match the password entered when creating an account)

**Additional context**
Branch from `0.2.0` and create a pull request to go back into it

![image](https://user-images.githubusercontent.com/11173328/110237790-cb8de380-7f35-11eb-82d1-5a4b615d5d45.png)

When the password is left blank, there currently is no error message in red text.

![image](https://user-images.githubusercontent.com/11173328/110286200-6e993880-7fdc-11eb-9252-30618a6a0cfa.png)

The same applies to the create account screen.

We also need the error message text to be centred

**Comment by hsergiu** [comment]
Would you let me do this one?

**Comment by knjk04** [comment]
@hsergiu Sure, thanks! I've added more detail to the issue description. If you need a hand with anything, feel free to create a Q&A discussion on GitHub!

**Comment by knjk04** [comment]
@hsergiu If you've already started, I'd recommend rebasing from `0.2.0` to get some new changes to the create account page

**Comment by hsergiu** [comment]
I understand. Thank you for the info.
