### ISSUE TITLE
Extract username to its own component

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#568]
**Describe the solution you'd like**
Similar to the password component in `shared/form`, create a new component for a username that both the `Login` and `Register` components can use.

**Additional context**
Branch from `0.2.0`

**Comment by RivaD2** [comment]
Hello Karan,

  It would be my pleasure to resolve this issue. If it is still up for grabs, I will gladly take it!

**Comment by knjk04** [comment]
Hello Riva, 

This is still up for grabs, so I'll you to the issue. Thank you very much! Feel free to reach to us by creating a new discussion on GitHub or on Slack if you need any help

**Comment by RivaD2** [comment]
Perfect Karan, thank you so much! I'm not assigned to this issue yet, but I will go ahead and get to work. :)

**Comment by knjk04** [comment]
My bad, I've assigned you now :)

**Comment by RivaD2** [comment]
Thank you :)

**Comment by RivaD2** [comment]
@knjk04 My apologies, but I just realized you code in Java :) Unfortunately, I am a JS developer. Once again my apologies! When I was looking for open source the issue was listed under JS.

**Comment by knjk04** [comment]
@RivaD2 This is a React issue. On the `0.2.0` branch, we're designing the UI in React (we're currently migrating from Vaadin to React)

**Comment by RivaD2** [comment]
@knjk04 I put together a draft PR here: https://github.com/Project-Books/book-project/pull/581.

I took the `Password` component and modeled the `Username` component after it so that's my current approach.

I am still very new to open source work and didn't see your Code of Conduct docs until a bit later after working. I made sure to adhere to your style and named my branch accordingly. However, I put the issue number at the beginning of the branch :( 

I see that to submit the PR, tests have to pass. Should I write tests for this?
Thank you for your help and time!

**Comment by knjk04** [comment]
> I put together a draft PR here: #581. I am ready to merge but I see that to submit the PR, tests have to pass. Should I write tests for this?

Thanks for the PR, I'll review it shortly. If you can write tests, that would be great. 

Your approach sounds good.

That's fine. It doesn't matter so much as long as the branch name is there.

You're welcome!

**Comment by RivaD2** [comment]
@knjk04 Thank you for merging the code and for your help. It was super fun to get in there and work on React!
Would you like me to close the issue or do you do that? :)

**Comment by knjk04** [comment]
@RivaD2 I'm glad you had a good experience! If you're interested, we'll be adding a lot more React issues once we've settled on a new design.

I was expecting the issue to close automatically when the PR was merged in, but I'll close it now. Thanks for your help!

**Comment by RivaD2** [comment]
@knjk04 Awesome, I'm super interested! The more I can see other code and work in React, the more I will learn :)
