### ISSUE TITLE
Set up ESLint

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#572]
Install ESLint and configure it to adhere to our [TypeScript](https://github.com/Project-Books/book-project/blob/0.2.0/styleguides/TYPESCRIPT_STYLEGUIDE.md) & [React](https://github.com/Project-Books/book-project/blob/0.2.0/styleguides/REACT_STYLEGUIDE.md) styleguides

**Comment by knjk04** [comment]
We could also use this: https://github.com/yannickcr/eslint-plugin-react

**Comment by paralix0** [comment]
Hi @knjk04, I would like to work on this issue please.

**Comment by paralix0** [comment]
Hi, I worked on it the last two days and it was done quite fast so I allowed myself to create a pull request. I hope it is alright.

**Comment by knjk04** [comment]
@paralix0 That's great, thanks! Once assigned, you're free to make a pull request whenever you're ready. I'll review your PR shortly
