### ISSUE TITLE
Rename 'Setup' subheading to 'Getting started'

### ISSUE THREAD

**Issue by ryboh1** [Project-Books/book-project#576]
### Why?
When Downloading the "book-project" I didn't know how to get the book project up and running

### What to include?
This [Link](https://github.com/componentjs/guide/blob/master/component/getting-started.md) includes a good template for getting started

**Comment by ryboh1** [comment]
### Edit
I've just realised that in the README.md there is a "Setup", Instead I think you should change that to "Installation" as it's standard practice.

**Comment by knjk04** [comment]
Thanks for the suggestion! I appreciate 'Setup' may be a little cryptic and not clear for everyone.

Besides the prerequisites and any dependencies, I see the section more as instructions for anyone looking to set up their local development environment for contributing than installing. We can change the subheading to 'Getting started'.

Would you be interested in creating a PR for this?

**Comment by SomyaPadhy4501** [comment]
I would love to do it

**Comment by SomyaPadhy4501** [comment]
can i be assigned?

**Comment by knjk04** [comment]
@SomyaPadhy4501 Since this has already been offered to @ryboh1, we'll wait and see whether they'd like to pick this up first. If not, we'll assign you to it

**Comment by SomyaPadhy4501** [comment]
> @SomyaPadhy4501 Since this has already been offered to @ryboh1, we'll wait and see whether they'd like to pick this up first. If not, we'll assign you to it

ok sir 😄

**Comment by ryboh1** [comment]
Yep, I'm on it :smile:

**Comment by knjk04** [comment]
@ryboh1 How are you getting on with the changes I suggested?

**Comment by knjk04** [comment]
@ryboh1 Unfortunately, as we have not heard back from you in a while, I will unassign you from the issue. This is in line with our contributing guidelines.

**Comment by knjk04** [comment]
@SomyaPadhy4501 Are you still interested in working on this?

**Comment by SomyaPadhy4501** [comment]
> @SomyaPadhy4501 Are you still interested in working on this?

Sure

**Comment by SomyaPadhy4501** [comment]
> @SomyaPadhy4501 Are you still interested in working on this?

I have the changes ready I guess its just changing setup to getting started :) I have done it as soon as I get assigned i ll generate pull request

**Comment by knjk04** [comment]
@SomyaPadhy4501 How are you getting on with this?

**Comment by SomyaPadhy4501** [comment]
> @SomyaPadhy4501 How are you getting on with this?

Ohh I thought I did it as I created a pull req...can you please tell me what did I do wrong last time please.

**Comment by knjk04** [comment]
It was the branch name. See https://github.com/Project-Books/book-project/pull/597#issuecomment-764635756. You did not create a branch with a descriptive name and issue number (e.g. `rename-setup-to-getting-started-576`). If you need a hand with this, let us know

**Comment by SomyaPadhy4501** [comment]
> It was the branch name. See [#597 (comment)](https://github.com/Project-Books/book-project/pull/597#issuecomment-764635756). You did not create a branch with a descriptive name and issue number (e.g. `rename-setup-to-getting-started-576`). If you need a hand with this, let us know

ok thank you I will do it by tommorow

**Comment by SomyaPadhy4501** [comment]
> It was the branch name. See [#597 (comment)](https://github.com/Project-Books/book-project/pull/597#issuecomment-764635756). You did not create a branch with a descriptive name and issue number (e.g. `rename-setup-to-getting-started-576`). If you need a hand with this, let us know

Sir I have done it please check once :)
