### ISSUE TITLE
Design mockups for the 'my books' page

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#580]
Take a look at the current 'my books' page for v0.1.0 (see [live demo](http://bookprojectv010-env.eba-22zuiphf.eu-west-2.elasticbeanstalk.com/login)).

We're looking to redesign this with a better UI (following material design) and UX.

We're using [Material UI](https://material-ui.com/) for Material Design components.

**Comment by knjk04** [comment]
Closing as we're now using Jira for design

**Comment by knjk04** [comment]
Closing as we're now using Jira for design

**Comment by ofvoler** [comment]
A preview of these mockups is currently featured on the [README page](https://github.com/Project-Books/book-project/tree/0.2.0/#readme).
