### ISSUE TITLE
Make the login page responsive

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#599]
**Describe the bug**

The logo does not appear where want it to at different screen resolutions.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to `localhost:3000`
2. See error

**Expected behaviour**

**Screenshots**

Fine at 2560x1440. This is what we want it to look at different resolutions:
![image](https://user-images.githubusercontent.com/11173328/105573297-6e0e5080-5d54-11eb-9f5c-2ec0c559e649.png)

1920x1080. The logo is slightly too far to the right and too close to the 'username' field
![image](https://user-images.githubusercontent.com/11173328/105573329-a0b84900-5d54-11eb-92a4-bd6c8d013cbc.png)

Too far to the right and overlaps with the username text field 
![image](https://user-images.githubusercontent.com/11173328/105573346-c47b8f00-5d54-11eb-852d-ef1018fc9180.png)

**Additional context**

Branch: `0.2.0`

**Comment by Kirill-frontend** [comment]
Hi i ready work on this issue.

**Comment by knjk04** [comment]
@Kirill-frontend Hi and thanks! I'll assign you to it

**Comment by Kirill-frontend** [comment]
Ok I'll try

**Comment by Kirill-frontend** [comment]
Sorry, I can't fix the bug, there were problems while editing.

**Comment by knjk04** [comment]
@Kirill-frontend That's OK

**Comment by ofvoler** [comment]
Can I try this? I think a combination of top and left positioning might work

**Comment by knjk04** [comment]
@ofvoler Sure, thanks! If you'd like, you can also increase the size of everything (something we previously discussed).

When working on this, could you please ensure that it also looks good on mobile devices?

**Comment by knjk04** [comment]
@ofvoler How are you getting on with this?

**Comment by ofvoler** [comment]
I've just started with it this weekend. I was having lots of issues with the virtual machine I have the project on and was also trying to read up more about React before I started. I'm hoping to have it done this week but will update you if I'm having any issues
