### ISSUE TITLE
Integrate zxcvbn on the frontend

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#607]
**Is your feature request related to a problem? If so, please describe.**
We currently only run [zxcvbn ](https://github.com/dropbox/zxcvbn)on the server, but it would be good to also have this on the client-side. This will allow us to provide quick feedback to a user on the password strength when they are registering.

**Describe the solution you'd like**

Similar to in [v0.1.0](http://bookprojectv010-env.eba-22zuiphf.eu-west-2.elasticbeanstalk.com/register), we would like a progress bar that has different colours and progress levels that correspond to password strengths (e.g. red for weak, yellow/amber for fair, green for strong and dark green for very strong)

**Additional context**

`0.2.0` branch.

**Comment by danielhoeller** [comment]
Hey @knjk04, I would like to work on this issue

**Comment by knjk04** [comment]
Hey @danielhoeller, thanks! I'll assign you to the issue. Feel free to reach out via a GitHub discussion or on the #help channel on Slack if you need anything

**Comment by danielhoeller** [comment]
Thanks!

Here's my approach (I hope it's okay if i post that here. instinctively i chose the issue over slack :)):

I will install the [zxcvbn npm package](https://www.npmjs.com/package/zxcvbn) and use it in the [Register component](https://github.com/Project-Books/book-project/blob/0.2.0/frontend/src/register/Register.tsx) to determine the score on password change. In the old UI there is validation involved, so I will make the score part of the component state for further validation later on.

Also, I will create a new stateless component with the score as an input property that displays a [LinearProgress](https://material-ui.com/components/progress/) in the right color and a corresponding text.

**Comment by knjk04** [comment]
> I hope it's okay if i post that here

That's fine.

> I will install the zxcvbn npm package and use it in the Register component to determine the score on password change. In the old UI there is validation involved, so I will make the score part of the component state for further validation later on.
Also, I will create a new stateless component with the score as an input property that displays a LinearProgress in the right color and a corresponding text.

We're using Yarn, so could you instead install the [yarn package](https://yarnpkg.com/package/zxcvbn)? Otherwise, that's great, thanks!
