### ISSUE TITLE
Connect the login view to the backend

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#608]
**Describe the solution you'd like**
Send a GET request to the server when the user tries to the login with the values passed into the email address and password fields.

If the server does not authorise the client, show an error message. If the server does authorise the client, however, route the user to the 'my books' page.

**Additional context**
Branch: `0.2.0`

Note that you'll need to run the backend locally

**Comment by knjk04** [comment]
Hey @danielhoeller, thanks! I'll assign you to it

**Comment by danielhoeller** [comment]
Similar to the Register component I will send an http request to the /login endpoint, if credentials are valid.
If the request is successful, I will use the history prop to route to /my-books

If the request fails, I am thinking to display a red [Alert](https://material-ui.com/components/alert/) below the **Create account** button

I am not sure what error message to display, exactly

**Comment by knjk04** [comment]
Sounds good, thanks!

Something like 'Your email or password is incorrect. Please try again' would be good.

**Comment by danielhoeller** [comment]
I realized that the **Alert** component is part of the [Lab](https://material-ui.com/components/about-the-lab/) package (incubating components not yet ready to move to the core). So, I am not sure what to do exactly. I could
* Install the lab package
* just display text, unstyled
* just display text, but styled

I am thinking I'll just display a red text if that's okay

**Comment by knjk04** [comment]
Red text is perfect, thanks!
