### ISSUE TITLE
Only call API if the password strength is 'very strong'

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#613]
**Describe the solution you'd like**
We're using [zxcvbn](https://github.com/dropbox/zxcvbn) as our password strength estimator. We only want to call `sendRegisterRequest()` in `onCreateAccountClicked()` if the password strength is 'very strong'.

```ts
  onCreateAccountClicked() {
    // ...

    if (!this.state.areCredentialsInvalid) {
      this.sendRegisterRequest()
    }
  }
```

**Additional context**
`0.2.0 branch`

**Comment by AdarshChandran2000** [comment]
I will work on it.

**Comment by AdarshChandran2000** [comment]
Can I work on it?  This is my first open-source contribution, so I will be needing some help.

**Comment by knjk04** [comment]
Sure, thanks. That's completely fine. Feel free to reach out by creating a discussion on GitHub or asking on the #help channel on Slack should you need anything.

**Comment by AdarshChandran2000** [comment]
Should I clone and work on the master branch or the 0.2.0 branch? I cloned master but got confused about whether should I do it on the 0.2.0 branch because of the milestone.

**Comment by knjk04** [comment]
When you clone the repository, you clone the entire repository, not a specific branch (although, you'll get `master`). You can then checkout `0.2.0` and then checkout another branch again. In other words, you'll need to create a branch from `0.2.0`.

Here's a broad list of steps:
1. Clone the repository
2. Switch to the `0.2.0` branch
3. Create a new branch from `0.2.0`

Hopefully, that helps

**Comment by AdarshChandran2000** [comment]
Yes. This helps a lot. Thank you  @knjk04

**Comment by AdarshChandran2000** [comment]
I am not able to run the application on my device. I don't know what's the bug.  Also, I went through the code and just noticed that its React, which I actually don't know. I can fix the issue with some help but might take a lot of time (more than a week or two). So if someone else is ready to do, its better to assign him/her.  I found few typos in the documentation section. I think I will be able to fix those issues and is more beginner friendly I guess.  Is that fine? @knjk04

**Comment by knjk04** [comment]
@AdarshChandran2000 That's fine, thanks for letting us know

**Comment by osopromadze** [comment]
Hey @knjk04 , I would like to work on this issue.

**Comment by knjk04** [comment]
Hey @osopromadze, thanks!
