### ISSUE TITLE
Fix running app using docker-compose build

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#632]
**Describe the bug**

Step 2 in the setup instructions in the README does not work on Windows. 

```
2. Start using docker-compose in production mode

    In the backend/ directory, build the project in production mode using one of the following commands
        ./mvnw clean package -Pproduction (Unix), or
        mvnw.cmd clean package -Pproduction (Windows)
    Start the MySQL Database and book project app using docker-compose up --build
        May need to add sudo to this command on Unix
```

The app should run the dev profile, not production.

**Comment by knjk04** [comment]
@amit1307 How are you getting on with this?

**Comment by knjk04** [comment]
(Discussed offline)

**Comment by dchhatani** [comment]
Hi, can I be assigned this issue.

**Comment by knjk04** [comment]
Thanks!

**Comment by knjk04** [comment]
@dchhatani Hi Deepak, how are you getting on with this?

**Comment by dchhatani** [comment]
Hi @knjk04 , I am yet to get started with this as something else came up. I'll target for this weekend.

**Comment by knjk04** [comment]
@dchhatani How are you getting on with this?

**Comment by knjk04** [comment]
@dchhatani Unassigning due to no response
