### ISSUE TITLE
Broken link in Contribution.md file.

### ISSUE THREAD

**Issue by vAdyar** [Project-Books/book-project#641]
**Describe the bug**
https://github.com/Project-Books/book-project/blob/main/CONTRIBUTING.md

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://github.com/Project-Books/book-project'
2. Scroll down to 'Contribution'
3. Click on 'contributing document'
4. Scroll down to 'New Files' under '6. Code Contribution'
5. Click on the 'copyright file' link.
5. Lands into a 404 error [page](https://github.com/Project-Books/book-project/blob/main/docs/COPYRIGHT). 

**Expected behaviour**
Should land on the right Copyright page.

**Additional context**
The hyperlink needs to be modified from 
'https://github.com/Project-Books/book-project/blob/main/docs/COPYRIGHT' 
to 
'https://github.com/Project-Books/book-project/blob/main/COPYRIGHT'

**Comment by knjk04** [comment]
Thanks for bringing this up! Would you be interested in creating a pull request for this?

**Comment by vAdyar** [comment]
Yea sure. You can assign it to me.
