### ISSUE TITLE
Fix Transient Property Value Exception for Predefined Shelf when Adding New Book

### ISSUE THREAD

**Issue by kateerfle** [Project-Books/book-project#654]
**Describe the bug**

When sending a POST request to the server to add a Book, the predefinedShelf field is throwing a TransientPropertyValueException.  

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://github.com/kateerfle/book-project/tree/add-rest-endpoint-463
2. Fork and run the application as usual for the 0.2.0 branch
3. With both the backend, frontend, and database running, send a POST request to localhost:8080/api/my-books with the body containing a Book in JSON format (will need to authenticate/login and get JWT token before this step, if not already done)

**Expected behaviour**

Book should be added (saved) to the database.  201 Created HTTP response returned.

**Screenshots**

https://slack-files.com/T01AA7VA57U-F01Q0M4J6P5-8dffcd29ca

**Additional context**

Stack trace: https://pastebin.com/vW9hVKNr

**Comment by VikramSitaram** [comment]
@knjk04 - Can i take a shot at this?

**Comment by knjk04** [comment]
@kateerfle Thanks for bringing this up! I think this is no longer an issue now, right?

**Comment by kateerfle** [comment]
@knjk04 @VikramSitaram yes, now that we have changed our approach for the @PostMapping, this is no longer an issue.  I can delete it now then.  Thanks for offering to help though!
