### ISSUE TITLE
Create Shelf carousel component

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#656]
**Describe the solution you'd like**
Create a new shelf carousel component to go on the 'my books' page. It should have the following:
- Name of the shelf
- A 'VIEW ALL' link next to the shelf name
- A white shelf with a shadow
- Equally sized and spaced apart slots for books (a simple rectangle will suffice for now as placeholders). There should be at most six slots
- An 'Add book' slot at the end of the shelf

This should be a reusable component as it will also be used on other pages.

**Additional context**

![image](https://user-images.githubusercontent.com/11173328/113743971-2749b900-96fc-11eb-87e6-da7bc5f7339c.png)

The shelf carousel should look like the above image

![image](https://user-images.githubusercontent.com/11173328/113743919-19943380-96fc-11eb-85d6-f5772e4ff15b.png)

The image above represents the placement of the shelves

**Comment by ofvoler** [comment]
Can I try this?

**Comment by knjk04** [comment]
@ofvoler How are you getting on with this?

**Comment by ofvoler** [comment]
Good! I mocked it out in HTML, and I've been catching up on React this week. I think I'll get started with the component on Monday.
