### ISSUE TITLE
Replace Author first and last name with full name field

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#661]
```java
    @NotBlank
    private String firstName;

    @NotBlank
    private String lastName;
```

Instead of having separate fields for an `Author`'s first and last name, it should be one field called `fullName`. This is in line with a future frontend change we will be making.

Branch from `0.2.0` and create a branch to go back into it

**Comment by hieu-t-tran** [comment]
Hi Karan! Could I try working on this issue?

**Comment by knjk04** [comment]
Hi Hieu, sure. Thanks!

**Comment by knjk04** [comment]
@hieu-t-tran How are you getting on with this?

**Comment by hieu-t-tran** [comment]
Hi Karan! I am still working on the issue and I plan to make an initial draft PR in the next few days. Thank you for checking in.

**Comment by knjk04** [comment]
Hi Hieu, no problem. Thanks for the update. Let us know if you need a hand

**Comment by hieu-t-tran** [comment]
Hi Karan, just a question. Previously, we will not allow an `Author` with either null/blank `firstName` or null/blank `lastName`. Now that we combine the 2 fields into `fullName`, do we allow an `Author` with only one word in this field? For example, `"Hieu"` instead of `"Hieu Tran"`

**Comment by knjk04** [comment]
Hi Hieu. Yes, one word is fine

**Comment by hieu-t-tran** [comment]
Hi Karan! Sorry for taking longer than needed with this issue. Let me know if you have any feedback for me to address.

**Comment by knjk04** [comment]
Hi Hieu, no problem!
