### ISSUE TITLE
Create forgot password modal

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#664]
**Describe the solution you'd like**

Create a forgot password modal as shown in the screenshot below.

It should be centred in the middle of the screen and be responsive.

The modal component should be generic as it'll be used in other places

**Additional context**

![image](https://user-images.githubusercontent.com/11173328/112270520-aefde500-8c71-11eb-897f-6c60a150aead.png)

**Comment by RivaD2** [comment]
@knjk04,
  Hello, I hope all is well. May I give this issue a try?

Thank you :)

**Comment by knjk04** [comment]
Hi Riva, sure! Thanks again for the help!

**Comment by RivaD2** [comment]
@knjk04 I have some questions for you as I'm planning out the best way to build the modal. 
For the modal:
  - What is the parent container? I know that we have the settings page and the login page. Who would trigger the modal?
  -  You mentioned that you want a generic modal so it can be used elsewhere. Does this mean you don't want it hooked up to anything quite yet? If that is the case, then the parent container or who triggers it doesn't matter as much I suppose. 
  
  My plan thus far is to figure out where in the file structure this modal component would belong. I can create a separate 'modal' folder or I can add it to a folder that it will relate to at some point in time. I am also looking into:
  -  a) building it out from scratch(Create `Handle show/hide` modal methods, Implement some sort of `onClose` event. `Close modal` by outside click etc.) This way will take me a bit longer...
  -  b) using [React.portal()](https://reactjs.org/docs/portals.html) 
 
Thank you for your input!

**Comment by knjk04** [comment]
> Who is the parent component? I know that we have the settings page and the login page, but I am wondering who would trigger the modal.App.tsx ?.

![image](https://user-images.githubusercontent.com/11173328/112596112-46467200-8e03-11eb-9a94-eb83ebbdc604.png)

This modal should be brought up when the user clicks on 'Forgot password', so perhaps the Login component?

> I am also thinking of two options:

Either's fine, whichever one you feel is best! 

> I can create a separate 'modal' folder for this component or I can add it to a folder that it will relate to at some point in time. Let me know what works best for you.

Could we have a new `components` folder in `shared/` that contains the modal (no further subdirectory needed at this point)?

**Comment by RivaD2** [comment]
@knjk04 Thank you for answering my questions:)
  When you have time, if you can look into portals a bit more and give me some additional guidance, that would be great! I have read the documentation and it says, "Portals provide a first-class way to render children into a DOM node that exists outside the DOM hierarchy of the parent component."

In my mind I am trying to craft the DOM tree of this application and am not sure if our modal will be need to be a child rendered outside hierarchy of the parent (basically figuring out if creating a portal has an advantage over building from scratch (it seems to be faster of course).

**Comment by knjk04** [comment]
Sure, I'll look into this & get back to you shortly

**Comment by RivaD2** [comment]
@knjk04 I think I will go ahead and build the modal using Material-UI:
  - I will create the `Modal` Class based component and in the render have an onClick to hide the modal
  - In the `Login.tsx` file, I will need to add in a `showModal` method 
  - As the user clicks on `forgotPassWord` to trigger the Modal, it is there that I should pass in an `onClick` prop and pass in the method to show it
  - It looks like I can use some of the styles that are already in Login I believe...
 
Let me know if you have any questions and I will be glad to help!

**Comment by knjk04** [comment]
@RivaD2 Sorry, I hadn't had time to look into this yet, but the material-ui approach sounds good!

> From the looks of the example, it appears that we are relying on the user to click on or outside of the modal to close it (no closing icon in modal), so we will need to listen for a mouse click or keyboard press (is this correct?)

You're right that clicking outside of the modal should close it. The 'cancel' button should also close the modal.

Thanks again for your help on this!
