### ISSUE TITLE
Create reading goal section

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#666]
**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/11173328/112805256-434eba00-906d-11eb-8566-c874dd70ec2d.png)

Create the reading goal section as shown above.

**Additional context**

![image](https://user-images.githubusercontent.com/11173328/112805396-71cc9500-906d-11eb-94c2-4f5b059572d5.png)

The above screenshot shows what it should look like within the context of the entire page (the completed goals section is not yet there)

**Comment by ofvoler** [comment]
Can I take this, please?

**Comment by knjk04** [comment]
Sure, thanks a lot!
