### ISSUE TITLE
Create delete account endpoint

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#667]
Create a delete account endpoint that deletes the currently logged in account. It should take in the password as a parameter to re-authenticate the user (to handle the time of check to time of use issue).

**Comment by ZackHollander** [comment]
I can take this.

**Comment by knjk04** [comment]
@cmadhumita5 Unfortunately, this is already assigned to Zack. Feel free to request to be assigned on an unblocked and unassigned issue
