### ISSUE TITLE
Create a layout component

### ISSUE THREAD

**Issue by ofvoler** [Project-Books/book-project#674]
**Describe the solution you'd like**
Create a layout component that can be reused for all pages. Include the nav bar, set automatic margins and padding, and add the title of the page so that it is consistent throughout the web app.

**Additional context**
![my books](https://user-images.githubusercontent.com/25254891/114450908-9a43ab80-9ba4-11eb-8886-45c1278a8d33.png)

Should look similar to this, with the nav bar on the left and the page title to the right of it

**Comment by ofvoler** [comment]
I can work on this

**Comment by knjk04** [comment]
Thanks!
