### ISSUE TITLE
Create shelf view toggle

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#679]
**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/11173328/114820440-e403e000-9db6-11eb-9986-1a3e39d31a4e.png)

Add a shelf view toggle on the 'My books' page that uses our existing toggle, as shown above (without the red line).

For the time being, when the user enables list view, the currently shown shelves should not show.

**Comment by Rishi6229** [comment]
hey i would like to work on this issue if you want me to?

**Comment by Rishi6229** [comment]
i would like to know the section on which i will have to work

**Comment by knjk04** [comment]
Hi, I'll assign you to the issue. Thanks! 

You'll need to add this toggle to my books file in the frontend/ directory. Note that you'll need to branch from 0.2.0

**Comment by knjk04** [comment]
@Rishi6229 How are you getting on with this?

**Comment by knjk04** [comment]
@Rishi6229 As we have not heard back from you in a while, despite following up, I will unassign you from the issue

**Comment by Rishi6229** [comment]
I understand that I couldn't reply you reason being I'm currently covid
positive and my whole family is not well coping up with the losses of many
of my family members also.....so please reassign task to someone else.

**Comment by knjk04** [comment]
@Rishi6229 I'm sorry to hear that. I hope you get better soon!

**Comment by Pranjal-dew** [comment]
hi there, can I contribute to this issue?

**Comment by RivaD2** [comment]
@knjk04 I can take this one on 👍

**Comment by knjk04** [comment]
@RivaD2 Great, thanks!

**Comment by RivaD2** [comment]
Hi there Karan!
My approach is this:

- Import in Switch into myBooks
- into ` interface IState` add in `showListView` property and set value to boolean
- Add `showListView` into state and set it to false
- Create method `onToggleListView` that toggles state of list by setting it to be opposite of state value
- Conditionally render `BookList` component if `this.state.showListView ?` : `ShelfCarousel`
- Pass onClick prop into `Switch` component and pass it the callback for `onToggleListView` method

**Comment by knjk04** [comment]
Hi Riva, that sounds great. Thanks!
