### ISSUE TITLE
Verify password strength

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#688]
**Describe the solution you'd like**
Check that the password strength is very strong on the backend with zxcbn4j. If it isn't, we shouldn't save the user/update the user's password. We need to update our controller endpoints to notify the frontend why the operation was not successful.

**Additional context**
Branch from `0.2.0` and set it as the destination branch in your pull request.

**Comment by BOYLOVEOI** [comment]
Hello, I would like to contribute! I would like to work on this for a project that I am completing, and I was wondering if I could have help throughout this process?

Thank You, 
Paul

**Comment by knjk04** [comment]
Hi Paul, thanks for your interest in this issue! I'll assign you to it.

If you need any help about the issue itself, feel free to create a GitHub discussion or ask on our Slack workspace.

I saw your email, but I think it's best to ask on GitHub or on Slack as it allows others to benefit from the answers.

> which class you were specifically referring to where you would want me to verify the password's strength

In the `register()` method in `UserService.java`:

```java
// ...

// check the password strength is very strong here before we go on to encode the password

User userToRegister = User.builder()
                          .email(user.getEmail())
                          .password(passwordEncoder.encode(user.getPassword()))
                          .active(true)
                          .roles(Set.of(userRole))
                          .build();
// ..
```

> what you meant by testing "on the backend with zxcbn4j." 

On the frontend, we're using [zxcvbn](https://github.com/dropbox/zxcvbn) to check the password strength. This allows us to show the user in real-time how strong their password is and an appropriate error message if it is weak. 

We want to re-check the password strength on the backend (in Java on the server) to be on the safe side (we shouldn't trust the client).

I hope this helps

**Comment by cmadhumita5** [comment]
i want to work on it but cold not understand the requirement comparisons.please help

**Comment by knjk04** [comment]
@cmadhumita5 This issue is already assigned

**Comment by knjk04** [comment]
@BOYLOVEOI How are you getting on with this?

**Comment by knjk04** [comment]
@BOYLOVEOI Unassigning due to no response

**Comment by kumawatanupriya** [comment]
@knjk04 Hi I would like to work on it.

**Comment by knjk04** [comment]
@kumawatanupriya Hi, thanks! I'll assign you to this!

**Comment by knjk04** [comment]
@kumawatanupriya How are you getting on with this?

**Comment by kumawatanupriya** [comment]
@knjk04 I didn't get time, I'll work on  it this weekend.

**Comment by knjk04** [comment]
@kumawatanupriya That's fine, thanks for letting us know

**Comment by kumawatanupriya** [comment]
@knjk04 please find the rough patch in pull request https://github.com/Project-Books/book-project/pull/724

Actually I see there is a folder called constraints which has password strength checker,  why didn't you suggested that. Is there anything wrong with that folder. I couldn't figure out. Please review the PR and let me know.

**Comment by knjk04** [comment]
> Actually I see there is a folder called constraints which has password strength checker, why didn't you suggested that. Is there anything wrong with that folder. I couldn't figure out.

@kumawatanupriya You're right, I forgot about that. You can look at our previous implementation in 0.1.0 (you'd have to look back in the main branch) to see how we were handling that

**Comment by kumawatanupriya** [comment]
@knjk04 Hi....I don't see any code in main branch for backend, I just see target and .iml file.

**Comment by knjk04** [comment]
>  Branch from 0.2.0 and set it as the destination branch in your pull request.

Note that you'll need to create your branch from 0.2.0 and set it as the destination branch in your pull request. You can ignore the main branch

**Comment by kumawatanupriya** [comment]
@knjk04 Hi, please check the PR  #724

**Comment by Snape25** [comment]
Is this issue still open? if yes, i would like to work on this.

**Comment by knjk04** [comment]
Hi @Snape25, thanks I'll assign you to the issue!

If you need help with anything, we'll be happy to help you over a [GitHub Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) or our [Slack workspace](https://camo.githubusercontent.com/eef8443bce0a2fdc0706ffcd99f91181ac849a4ef423a1ed61386ca0a8b448bb/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f736c61636b2d7465616d626f6f6b70726f6a6563742d3441313534423f6c6f676f3d736c61636b)

**Comment by Snape25** [comment]
Hello, so i just need to check if the password strength constraint is getting violated, and respond with a 400 status right?
