### ISSUE TITLE
Create user role enum

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#689]
Instead of using a String to represent the user role type, use an enum instead. 

We need the following role types (case sensitive):
- USER
- ADMIN

Branch from `0.2.0` and set it as the destination branch in your pull request.

**Comment by jamalkhattab** [comment]
Hello, can I try to make this my first contribution?

**Comment by knjk04** [comment]
Hello, sure. Thanks! Let us know if you need a hand with anything

**Comment by jamalkhattab** [comment]
Hey @knjk04, just wondering if I should only create the enum or also refactor the following classes: UserService, UserServiceTest to use the enum instead of the String "USER".

**Comment by jopijuco** [comment]
@jamalkhattab yes I believe you must do it in order to implement the enum you created.
