### ISSUE TITLE
Only save a UserCreatedShelf if its name is not taken

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#698]
**Describe the solution you'd like**
The name of a `UserCreatedShelf` should not match any of the predefined shelves (see the `PredefinedShelfName` enum) or any existing `UserCreatedShelf`. 

We need to ensure that this check is case insensitive (e.g. 'READ' is not allowed if 'read' exists). One way of checking whether the shelf name exists is by writing custom JPQL queries. Alternatively, we can use Java streams on all existing predefined and custom shelves.

**Additional context**
Branch from `0.2.0` and create a pull request to merge into it.

**Comment by olusolaa** [comment]
@knjk04 I can take this.

**Comment by olusolaa** [comment]
Alright.

**Comment by knjk04** [comment]
@F0rgiv Sure, thanks!

**Comment by F0rgiv** [comment]
@knjk04 Hey there! Quick clarifying question.
I have created the method UserCreatedShelfService.shelfWithNameExists() That is now working as expected. Would you like me to add call to this within the createCustomShelf() method and throw an error if the shelf exists?

**Comment by knjk04** [comment]
@F0rgiv Yes, a custom exception would be great. Thanks!

**Comment by knjk04** [comment]
@F0rgiv Unassigning due to no response on the PR

**Comment by Syemon** [comment]
Hi @knjk04, can I take this one?

**Comment by knjk04** [comment]
Hi @Syemon, sure. Thanks a lot!

**Comment by Syemon** [comment]
Can I trim shelfName during check as well? I want to avoid saving names like " READ".

**Comment by knjk04** [comment]
Sure, that's a good idea

**Comment by Syemon** [comment]
Hey, my branch is ready for review, but I can't read contributing document. The content inside [link](https://project-books.github.io/docs/development/contributing/) is broken. I assume that I should make PR into 0.2.0?
