### ISSUE TITLE
Handle many-to-many relationship between Book and Publisher

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#699]
In `Book.java`, the parent of the many-to-many relationship, we should have methods to add and remove a publisher to handle the bidirectional relationship.

Once this is implemented, we can remove the `addBookToPublisher()` method in `PublisherService.java`.

**Additional context**

Branch from `0.2.0` and create a pull request to merge into it.

**Comment by kumawatanupriya** [comment]
@knjk04 I would like to work on it.

**Comment by knjk04** [comment]
@kumawatanupriya Thanks!

**Comment by kumawatanupriya** [comment]
Hey @knjk04 why do you want to do that?. why addBookToPublisher() function be in PublisherService.java?

**Comment by knjk04** [comment]
Hi, we're looking to move the method from `PublisherService` to the `Book` class

**Comment by kumawatanupriya** [comment]
@knjk04 please review this PR https://github.com/Project-Books/book-project/pull/714
