### ISSUE TITLE
Include author name in Book's equal() and hashCode()

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#707]
Include the author name in Book's equal() and hashCode()

Branch from `0.2.0` and set it as the destination branch in your pull request

**Comment by Vaidehi-Joshi** [comment]
Hi, I would like to take up this issue

**Comment by knjk04** [comment]
@Vaidehi-Joshi Thanks, I'll assign you to it.

I've also updated the issue description to state that you should branch from `0.2.0` and set it as the destination branch

**Comment by Vaidehi-Joshi** [comment]
Okay will do that, also can you tell me how to join the slack or discord channel if there is one?

**Comment by knjk04** [comment]
There's a link to our Slack workspace on our README at the top

![image](https://user-images.githubusercontent.com/11173328/118594372-42025980-b7a1-11eb-9c78-e84eee90113a.png)

**Comment by knjk04** [comment]
@Vaidehi-Joshi How are you getting on with this?

**Comment by knjk04** [comment]
@Vaidehi-Joshi Unassigning due to no response

**Comment by KACHIDA** [comment]
Hi , I would like to work on this issue. @knjk04

**Comment by knjk04** [comment]
Thanks, I'll assign you to it

**Comment by yasuomaidana** [comment]
Could you assign it to me?

**Comment by knjk04** [comment]
@yasuomaidana This is already assigned, unfortunately

**Comment by knjk04** [comment]
@KACHIDA How are you getting on with this?

**Comment by knjk04** [comment]
@KACHIDA Unassigning due to no response.

@yasuomaidana Are you still interested in this?

**Comment by abhity16** [comment]
@knjk04 Can I take it up ?

**Comment by knjk04** [comment]
@abhity16 Sure, thanks!

**Comment by knjk04** [comment]
@abhity16 Do you have an update on this?

**Comment by rhit-namburs** [comment]
Hi I would like to work on this issue and will get it done in a timely manner.

**Comment by abhity16** [comment]
@knjk04 
Sorry for delayed response. I got busy in other work and could not spend time on it. Please assign it to any other interested member.

**Comment by knjk04** [comment]
@abhity16 That's fine, thanks for letting us know

**Comment by knjk04** [comment]
@rhit-namburs As we only assign one issue at a time to new contributors, you're welcome to re-request to work on this after completing your currently assigned issue

**Comment by drunkenlegend** [comment]
Hi @knjk04 , I would like to take up the issue. I am new to spring and this would be a good start for me in open-source.

**Comment by knjk04** [comment]
Hi @drunkenlegend, thanks! I'll assign you to this. Feel free to reach out via a GitHub discussion or post on our #book-project Slack channel should you need any help
