### ISSUE TITLE
Show the books across all shelves

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#71]
**Is your feature request related to a problem? If so, please describe.**
There is not yet a way for a user to see their books across all shelves

**Describe the solution you'd like**
- An option to select the books in all shelves in the ComboBox above the grid

**Comment by knjk04** [comment]
This is blocked by issue #18

**Comment by Tom-private** [comment]
Idea: add a new predefined Shelf called "All Shelves", which can be selected in the comboBox.
- there would need to be some logic in ```getBooksInChosenPredefinedShelf``` and ```getBooksInChosenCustomShelf``` like
```if (chosenShelf is All_shelves) then query the db for all books``` 
- it must not be possible to select the "all shelves" shelf when adding / updating a book

**Comment by Tom-private** [comment]
Update: Basic implementation with the new predefined Shelf is done (view is working, new shelf is not shown in the "add book" form).
Should I create a WIP PR so that you can have a look at it before I check the tests, cleanup the code and make sure, that I did not miss something?

**Comment by knjk04** [comment]
Thanks for expressing an interest in this!

> Should I create a WIP PR so that you can have a look at it before I check the tests, cleanup the code and make sure, that I did not miss something?

Sure, go ahead.

> I hope you do not mind, that I was storming ahead a bit. I just wanted to look a bit into this and suddenly hours passed and code was written... ^^'

Haha, that's fine :)
