### ISSUE TITLE
Refactor dark mode switch to only work on Nav Bar

### ISSUE THREAD

**Issue by RivaD2** [Project-Books/book-project#723]
We currently have dark mode implemented using Material-UI's [Palette](https://material-ui.com/customization/palette/). We want current pages/future pages have a white background, so dark mode is not needed for the entire site at this time.

Please refactor this implementation so that when the `Enable dark mode` switch is clicked, the nav bar **only** is switched to a dark background. The nav bar should stay white by default. 

**For reference**
Currently, after clicking on 'settings' in the nav, and enabling the dark mode switch, Material-UI inputs are hidden(e.g. the input on the delete account page) due to the dark mode theme. See below:

**Light mode nav by default**
![white-nav-default](https://user-images.githubusercontent.com/67027945/122444599-90984480-cf55-11eb-96ee-46549c25823f.png)

**Input visible in light mode**
![light-mode-delete-account](https://user-images.githubusercontent.com/67027945/122444946-e836b000-cf55-11eb-874f-03db0740fcf4.png)

**Input hidden in dark mode**
![Screen Shot 2021-06-16 at 4 36 39 PM](https://user-images.githubusercontent.com/67027945/122445134-174d2180-cf56-11eb-82a8-31a5fc81ece1.png)

**Things to note:**
- Describe your approach with us first
- Double check that all Material-UI inputs and buttons have current style intact after implementation is finished
- Read our contributing guidelines

**Comment by rhit-namburs** [comment]
Hi I would like to work on this issue!

**Comment by knjk04** [comment]
@rhit-namburs Thanks, I'll assign you to it!

**Comment by knjk04** [comment]
@rhit-namburs How are you getting on with this?

**Comment by Pranjal-dew** [comment]
hi there, can I contribute to this issue?

**Comment by knjk04** [comment]
@Pranjal-dew How are you getting on with this?

**Comment by knjk04** [comment]
@Pranjal-dew Unassigning due to no response, as per our contributing document

**Comment by knjk04** [comment]
@grace-ko Hi, sure. Thanks! If you need a hand, feel free to ask on our #book-project channel on Slack or create new GitHub Q&A discussion

**Comment by grace-ko** [comment]
@knjk04 sorry for the delay, just got set up. I think easiest way would be to add customization in the theme file for the dark mode, what do you think?

**Comment by RivaD2** [comment]
> @RivaD2 How does that sound?

I think that sounds like a good approach!

**Comment by knjk04** [comment]
@grace-ko Appreciate you may have been busy, but how are you getting on with this? Also, there may not be enough time to get this merged in before the 31st, so would you still be interested in working on this outside of Hacktoberfest?

**Comment by grace-ko** [comment]
@knjk04 Yes please, thanks for your patience. Update coming shortly!
