### ISSUE TITLE
StringUtils.pluralize doesn't take into consideration all cases

### ISSUE THREAD

**Issue by konkos** [Project-Books/book-project#732]
StringUtils.pluralize doesn't seem to work properly 
e.g if word=bus => StringUtils.pluralize("bus",2) would return buss when buses is the correct form.
 OR if word=phenomenon => StringUtils.pluralize("phenomenon ",2) would return phenomenos when phenomena is the correct form.

**Comment by knjk04** [comment]
Thanks for bringing this up! It seems like it might be quite difficult to cover all of the possible cases. What do you think?

**Comment by konkos** [comment]
There is probably some api that could do that but it sounds like it is too much work. The simpler solution to cover some cases "manually". I will PR a proposed solution

**Comment by konkos** [comment]
Another solution I have found is to use ( atteo/evo-inflector ). I have tested is a bit seems to work relatively well

**Comment by knjk04** [comment]
Thanks for looking into this! Unfortunately, given that we only need it for one specific use case, I think it would be better to not use the library right now. It's an extra dependency to manage that we do not currently need. 

I'll close this issue. However, I appreciate you bringing this up and for raising a PR. If we do find ourselves in a situation where we need the more general solution, we can look into this again. For the time being, a comment explaining the limitation and use case (we may need to move this into the goal package) will suffice.
