### ISSUE TITLE
Call add shelf endpoint

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#745]
**Describe the solution you'd like**
When we click on the [add shelf button](https://github.com/Project-Books/book-project/blob/main/frontend/src/my-books/MyBooks.tsx#L175), we should call the add shelf endpoint: https://github.com/Project-Books/book-project/blob/0.2.0/backend/src/main/java/com/karankumar/bookproject/backend/controller/ShelfController.java#L4.

- Verb: POST
- Endpoint: `localhost:8080/api/shelf`
- Pass in shelf name as a path variable

This endpoint call should be added here: https://github.com/Project-Books/book-project/blob/main/frontend/src/my-books/ShelfModal.tsx#L38

We would need to handle the bad requests that we get back accordingly with error messages (red text)

**Comment by brandon-hoang-le** [comment]
Hi @knjk04, new to this but I would like to work on this!

**Comment by knjk04** [comment]
Hi @brandon-hoang-le, thanks! I'll assign you to this. Feel free to create a new GitHub discussion or ask on the #book-project channel on Slack if you need a hand with anything

**Comment by brandon-hoang-le** [comment]
Awesome, thank you!

**Comment by knjk04** [comment]
Unassigning at your request

**Comment by hungle132** [comment]
Hello @knjk04 I would like to attempt this issue.

**Comment by knjk04** [comment]
Hello @hungle132, thanks! I've assigned you to this. If you need a hand with anything, do let us know over Slack or through a GitHub discussion

**Comment by knjk04** [comment]
@hungle132 I've edited the issue description. You can branch from the `main` branch and set `main` as the destination branch in your pull request

**Comment by knjk04** [comment]
@hungle132 How are you getting on with this?

**Comment by hungle132** [comment]
@knjk04 I tried building the backend with the following steps on the main page and I get an infinite loops and nothing builds.

**Comment by knjk04** [comment]
How long has this been running for?

**Comment by hungle132** [comment]
This is what I get when i run mvnw.cmd clean install and it runs for 1 minute max.

**Comment by knjk04** [comment]
@hungle132 Do you have an update on this?

**Comment by knjk04** [comment]
@hungle132 Unassigning due to no response

**Comment by hiyingnn** [comment]
Hello, I'm interested in taking up this issue! Do let me know if it's available!

**Comment by knjk04** [comment]
Thanks, @hiyingnn! I'll assign you to this

**Comment by knjk04** [comment]
@hiyingnn How are you getting on with this?

**Comment by knjk04** [comment]
@hiyingnn Unassigning due to no response

**Comment by ppalanisami** [comment]
Hi, I am a new comer. I would like to take this issue. Will you please assign this to me?

**Comment by knjk04** [comment]
Hi @ppalanisami, thanks for your interest! When do you think you could have a non-draft pull request ready?

**Comment by ppalanisami** [comment]
@knjk04 Just I had a deep dive in to this issue and I see the actual functionality has been implemented. Can you please provide some more information what exactly to be implemented?

**Comment by ppalanisami** [comment]
@knjk04 Just FYI: I have around 20 Hours time until end of this weekend.

**Comment by knjk04** [comment]
@ppalanisami Here is the line in React: https://github.com/Project-Books/book-project/blob/main/frontend/src/my-books/ShelfModal.tsx#L38. We are not calling the backend endpoint (this is a frontend React issue)

**Comment by ppalanisami** [comment]
@knjk04 sorry. I am a backend developer. I can't help on React. Is there anything in Backend?

**Comment by knjk04** [comment]
@ppalanisami That's fine, I'll unassign you from this issue. Note that this was issue had the 'react' and 'frontend' labels. You can look for other labels of interest, such as Spring: https://github.com/Project-Books/book-project/issues?q=is%3Aopen+is%3Aissue+label%3Aspring

**Comment by priya1712d** [comment]
Hi @knjk04  Do you still need help on this? Could I work on this issue?

**Comment by knjk04** [comment]
Hi @priya1712d, thanks for the offer! I'll assign it to you

**Comment by priya1712d** [comment]
Hi @knjk04 
Thank you for assigning the issue.

I am facing this issue while accessing DB 
[HY000][1130] null, message from server: "Host '172.21.0.1' is not allowed to connect to this MySQL server". I am not connected to any VPN.


These are the logs I see in Docker.
MY-000061] [Server] 1105  Input Output error while reading file /data/application/init.sql, line 0, I/O error code 1

Could you help?

**Comment by knjk04** [comment]
Hi @priya1712d, what OS are you using?

**Comment by priya1712d** [comment]
@knjk04 MacOS

**Comment by knjk04** [comment]
How did you start the database?

**Comment by priya1712d** [comment]
I followed this section

Access database
To access the MySQL database when docker-compose is running:

Go to http://localhost:8081/
Log in with the details below:
Username: root
Password: rootpassword
Click on connect

**Comment by knjk04** [comment]
![image](https://user-images.githubusercontent.com/11173328/150980760-5118c2dc-af77-45eb-9bf1-b3491d58ed63.png)

I wasn't able to reproduce this, so it may be something on your end. 

Are you using a new Mac with an Apple silicon chip? If so, did you uncomment this line: https://github.com/Project-Books/book-project/blob/0.2.0/backend/docker-compose.yml#L6?

**Comment by priya1712d** [comment]
@knjk04  Hey I was able to resolve that by creating a new init.sql in db folder, some reason it was not able to access it. 

So, now I can access the DB, but not using IDE. I have the same error :(

**Comment by priya1712d** [comment]
@knjk04 
All issues resolved. Apparently, I already had some version of MySql server running on my machine on the same port which was creating issues.

I have started working on this issue.

Approach:-

Step 1. Create a common method for post requests in HTTPClient.
Step 2. Call the create shelf API in ShelfModal.
Step 3. Show errors on modal or a message saying 'Shelf created successfully'.

Queries:-

1. Is there already a modal in the project where errors can be displayed for reference?
2. Is it a good idea to show the 'Shelf created successfully' or errors messages on the main page and close the Modal immediately?
