### ISSUE TITLE
Limit the number of failed password attempts

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#748]
**Is your feature request related to a problem? If so, please describe.**
A malicious user can repeatedly try as many different possible passwords to gain unauthorised access to an account.

**Describe the solution you'd like**
Limit the number of failed login attempts to three attempts. After three attempts, we should block the user for a day.

**Additional context**
Discuss your implementation with us first

**Comment by Lexinka291** [comment]
Can I take this issue? 
My implementation whould be that after each failed attempt warning "Your email or password is incorrect. Please try again" will be extended with frase "Remaining attempts [numOfRemainingAttempts]". If the user will fail 3 attemps I would block email address for 24 hours. (With message like "This address is blocked for [remaining hours], please contact administrator for more information". If you have other idea, I can try it as well.

**Comment by knjk04** [comment]
@Lexinka291 Thanks for our interest in this! Just to clarify, are you looking to work on the frontend (React) or backend (Spring) for this?

**Comment by Lexinka291** [comment]
I would rather use Spring but cant promise that it wont end with React :) . In any case I will post here if I consider changing from Spring to React

**Comment by knjk04** [comment]
How would you go about recording failed login attempts?

**Comment by Lexinka291** [comment]
Actually I found some good example how to make it.  I will need to create some boolean variable in dtbs for User to know if acc is locked also save time to know how long will be locked. The example is here: [example](https://www.codejava.net/frameworks/spring-boot/spring-security-limit-login-attempts-example ). Do you think its a good way to implement this or have you any other ideas?

**Comment by knjk04** [comment]
I was thinking of a similar approach where we have a table to record all failed login attempts. We can store the email address and a timestamp. Even if a user has only failed log in attempt, it would be good if we can record this (e.g. in the future, we may want to send an email to inform a user about this in case it's not them)

**Comment by Lexinka291** [comment]
Deal ;) Thanks!

**Comment by viniciusrplima** [comment]
The task remains unresolved? Can I work on it?

**Comment by knjk04** [comment]
Sure, @viniciusrplima. I'll assign you to it. Thanks!

**Comment by viniciusrplima** [comment]
Thank you!

**Comment by viniciusrplima** [comment]
I think that the example given by previous guy is good. I will make some adjustments and comment here tonight.

**Comment by viniciusrplima** [comment]
I propose some changes in this [example](https://www.codejava.net/frameworks/spring-boot/spring-security-limit-login-attempts-example). I think that we can move MAX_FAILED_ATTEMPTS and LOCK_TIME_DURATION to application.properties.

**Comment by viniciusrplima** [comment]
We can change the success and failure handles with listeners to AuthenticationSuccessEvent and AuthenticationFailureBadCredentialsEvent.

**Comment by viniciusrplima** [comment]
I already implemented it. I'll do some refactorings and then i'll do a PR.
