### ISSUE TITLE
User not informed of a server error when creating an account

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#750]
**Describe the bug**

We should display the following text when we get a 500 server error when attempting to create a new account: 'Something went wrong. Please try again later.' in red text (see how we currently display error text for weak passwords).

**Additional context**

Branch from 0.2.0 and set it as the destination branch in your pull request

**Comment by brandon-hoang-le** [comment]
Hey @knjk04 ! I'll sign up for this.

**Comment by knjk04** [comment]
Thanks, @brandon-hoang-le!
