### ISSUE TITLE
Spring REST docs: 'include file not found asciidoc'

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#756]
'include file not found asciidoc' in the index.adoc file. The project.build.directory in pom.xml should be looking in the target/ directory, but this needs to be confirmed because asciidoc is looking in the src/main/asciidoc directory

**Comment by Wildschut** [comment]
Hi, can I work on this issue?

**Comment by knjk04** [comment]
Hi, sure, I'll assign you to the issue. Thanks!

**Comment by knjk04** [comment]
If you need a hand with this, feel free to get in touch with us over our Slack workspace (link is the badge in the README) or by creating a new GitHub Q&A discussion

**Comment by Wildschut** [comment]
Thank you for the heads up. Will do so if I get stuck somewhere...
