### ISSUE TITLE
Invalidate JWT token after account deletion

### ISSUE THREAD

**Issue by adrianbranescu** [Project-Books/book-project#757]
Currently, JSON Web Tokens (JWTs) are used for passing authentication information. These tokens expire automatically, after a period of time.

Most requests need authorization information; otherwise, the requests are rejected (server returns 403 Forbidden response).

For example, if you want to list users, you will have to send valid authentication information.

The problem is that, after user account deletion, user JWT remains valid (until it expires) and can be used to make requests that normally should be rejected.

Steps to reproduce the issue:

1) Login using Postman (you may wish to create a new user account before, as you will have to delete it later)
https://github.com/Project-Books/book-project/wiki/Connecting-to-the-backend-via-Postman

2) Delete your own account
Using Postman, send a DELETE request to localhost:8080/api/user, having a raw body which contains email and password key/value pairs.

3) Make some requests where you use the JWT that belonged to the account you have just deleted.
Example: GET localhost:8080/api/user/users
Normally, this request should be rejected, but in practice you can successfully retrieve the result, because the JWT that is sent with the request is still valid.

**Additional context**
- Read our contributing guidelines first!
- We'll require you to discuss you implementation approach before being assigned to this
- Branch from `main` and set it as the destination branch in your pull request

**Comment by olusolaa** [comment]
I can take this

**Comment by olusolaa** [comment]
@knjk04 can I take this?

**Comment by knjk04** [comment]
@olusolaa Thanks for your interest in this! We're currently using a MySQL database (H2 in-memory database for tests). Our JWT tokens are set to expire after 7 days.

I think it's better if we don't use an in-memory database for this. It would require us to have a separate one from our persistent one only for this. If we would need to restart the database for whatever days, a user may have to be issued a new JWT token, even before 7 days is up.

Let us know if you have any ideas on how to implement this before we assign this to you. While we could store the blacklist in our persistent database, this may accumulate over time and it may take a while to search through the entire table if so.

**Comment by olusolaa** [comment]
> If we would need to restart the database for whatever days, a user may have to be issued a new JWT token, even before 7 days is up.

@knjk04 it's only the blacklisted token we want to save in the H2, it doesn't affect the other users.

**Comment by mslowiak** [comment]
A blacklisted tokens table can be created in an existing database.
We can check if the used token is on the blacklist.
To prevent this table from growing so much, we can apply some corn jobs that will be deleting records from the database for blacklisted tokens that already had an expiration date in the past. Then those tokens will be rejected in a normal way, the same as expired tokens.

**Comment by knjk04** [comment]
@mslowiak Agreed, I think this is a better approach

**Comment by knjk04** [comment]
@mslowiak Would you be interested in working on this?

**Comment by mslowiak** [comment]
Yes, I will take care of that ticket

**Comment by knjk04** [comment]
@mslowiak Thanks a lot!

**Comment by knjk04** [comment]
@mslowiak How are you getting on with this?

**Comment by mslowiak** [comment]
Sry for late response, still in progress
