### ISSUE TITLE
Create 'Add book' modal

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#763]
**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/11173328/135040275-d67be4d9-1011-4ea9-8bdc-b3fa12eff9b7.png)

Create a new 'Add book' modal component:

- Have red asterisks and validation for the required fields
- Clicking reset should clear all of the fields (and not show any error text)
- Page count should only accept numbers
- This should be responsive and adapt to screen sizes (see our existing modals)
- Clicking on the plus icon should create another author or shelf field, but these are not mandatory
- Send a POST to /api/books (https://github.com/Project-Books/book-project/blob/main/backend/src/main/java/com/karankumar/bookproject/backend/controller/BookController.java#L123)

![image](https://user-images.githubusercontent.com/11173328/135040593-4f0ae9fa-a05e-4fca-bba9-a7bf715dd4bc.png)
- Trigger opening the modal when the user clicks on 'Add book' (see above)

**Additional context**
- Be sure to read the contributing guidelines first!
- Branch from `main` and set it as the destination branch in your PR

**Comment by EvaKrizal** [comment]
Hi, is this issue available?

**Comment by knjk04** [comment]
Hi, this issue is currently blocked. We're working on finalising our design for this. I can let you know once it's unblocked and available to pick up
