### ISSUE TITLE
Make shelf/list view toggle 'sticky'

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#765]
**Currently**

![image](https://user-images.githubusercontent.com/11173328/135079827-6b2f1f57-828e-46a5-9d92-c788a43b0f15.png)

Currently, we display the toggle at the bottom of the page.

**Describe the solution you'd like**

See page 2 of our [mockups](https://www.figma.com/proto/MWYSlKNoyg3Ja3EAeectcQ/Book-Project-UI-Copy?node-id=1%3A2&scaling=min-zoom). The toggle is always present, even when you scroll up or down.

**Additional context**
- Be sure to read the contributing guidelines first!

**Comment by arshxyz** [comment]
Hi, I would like to claim this issue, thanks.

**Comment by knjk04** [comment]
Hi @arshxyz, sure, I'll assign you to the issue. Thanks!
