### ISSUE TITLE
Include name of book in thumbnail for list view

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#766]
**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/11173328/135080612-b3f842aa-eab0-4cce-a3a4-b787ffcd87e9.png)

Similar to the above image where we include the title of the book in the thumbnail, we should do the following in the list view. Currently, it looks like the following screenshot:

![image](https://user-images.githubusercontent.com/11173328/135080729-d8edcfdd-8936-46c3-af2c-dc471ad063b7.png)

**Additional context**
- Be sure to read the contributing guidelines first!

**Comment by kpnigalye** [comment]
If I understood correctly, in the list view title of the book should be there in the thumbnail. If the text is too long, is it ok to the change size of the thumbnail? It yes, I would like to give it a try.

**Comment by knjk04** [comment]
> If I understood correctly, in the list view title of the book should be there in the thumbnail.

That's correct

> If the text is too long, is it ok to the change size of the thumbnail?

If the text is too long, we can truncate the title and use ellipsis (e.g. 'Harry Potter and the Order ...').

Would you still like to work on this?

**Comment by kpnigalye** [comment]
yeah sure..thanks

**Comment by knjk04** [comment]
If you need help with anything, we'll be happy to help you over a [GitHub Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) or our [Slack workspace](https://camo.githubusercontent.com/eef8443bce0a2fdc0706ffcd99f91181ac849a4ef423a1ed61386ca0a8b448bb/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f736c61636b2d7465616d626f6f6b70726f6a6563742d3441313534423f6c6f676f3d736c61636b)

**Comment by kpnigalye** [comment]
I have added a character limit for the text to be displayed inside the thumbnail. The screen will look like this now.
![image](https://user-images.githubusercontent.com/8084464/135724167-b682645d-8101-432c-884c-a83fdd4b15fe.png)
Let me know if it will work for you.

**Comment by knjk04** [comment]
This looks good, thanks!

**Comment by kpnigalye** [comment]
I have created a PL but I am bot able to assign it to you. Can you please check my PL?
