### ISSUE TITLE
Add filter and search bar

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#767]
**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/11173328/135081135-44cb88c8-edb3-4089-b0e7-785f35cc5344.png)

Add the filter and search bar:
- For now, the filter shouldn't do anything when clicked
- The results in the list view should filter to match the query (the book title that was searched for)

**Additional context**
- Be sure to read the contributing guidelines first!

**Comment by qwe123coder** [comment]
hey i could try this

**Comment by knjk04** [comment]
Hi @qwe123coder, thanks! I've assigned you to it. If you need a hand with anything, feel free to get in touch with us over our #book-project channel on Slack or by creating a new GitHub Q&A discussion

**Comment by knjk04** [comment]
@qwe123coder Unassigning due to no response, as per our contributing guidelines
