### ISSUE TITLE
Fix genre name sent to client

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#768]
**Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/11173328/135081742-e3faac04-137b-4dee-93b1-8dadf7405a25.png)

In the list view on the frontend, we are not displaying the genres the way we want to.

**Steps to reproduce**

Either
- Run the frontend and backend, go the 'my books' page on the frontend and toggle 'list view',
- Or examine the response in a REST client like Postman

We should be sending the human-friendly (not in all-caps and no underscores) representation of our genres. See our [BookGenre ](https://github.com/Project-Books/book-project/blob/main/backend/src/main/java/com/karankumar/bookproject/backend/model/BookGenre.java) class the frontend.

We want a fix that would work for all endpoints called because we always want to send the genres without underscores and not in all-caps.

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us first
- Branch from `main` and set `main` as the destination branch in your pull request

**Comment by pedro-cze** [comment]
Hi, can I have a look at this one?

**Comment by knjk04** [comment]
Hi @pedro-cze, thanks for your interest! Before I assign you to this, could you please let us know what your implementation approach is?

**Comment by pedro-cze** [comment]
Hi, @knjk04 sure, the fix seems to be pretty easy here. Using [`@JsonValue`](https://fasterxml.github.io/jackson-annotations/javadoc/2.8/com/fasterxml/jackson/annotation/JsonValue.html) on the `genre` field...

`@JsonValue
    private final String genre;
`

**Comment by knjk04** [comment]
Hi @pedro-cze, that would work well. Thanks! I'll assign you to this
