### ISSUE TITLE
Create PredefinedShelf controller

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#769]
**Describe the solution you'd like**

Create a new PredefinedShelvesController with GET endpoints that return a list of books in each of the four predefined shelves.

- See the 4 shelves in this enum: https://github.com/Project-Books/book-project/blob/main/backend/src/main/java/com/karankumar/bookproject/backend/model/PredefinedShelfName.java 
- Entity: https://github.com/Project-Books/book-project/blob/main/backend/src/main/java/com/karankumar/bookproject/backend/model/PredefinedShelf.java

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Branch from `main` and set `main` as the destination branch in your pull request

**Comment by pavolo99** [comment]
Hi @knjk04, I would like to work on this issue. May I ?

**Comment by knjk04** [comment]
Hi @pavolo99, sure, I'll assign you to the issue. Thanks!

**Comment by pavolo99** [comment]
Thanks.

So, the PredefinedShelvesController should contain of 4 separate endpoints for each shelf name (TO READ, READING, READ, DID_NOT_FINISH), correct?

**Comment by knjk04** [comment]
@pavolo99 That's right

**Comment by knjk04** [comment]
@pavolo99 How are you getting on with this issue? If you need any help on this, feel free to reach out to us on [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-punc8os7-Iz9PTCAkYcO_0S~XwtO5_A)

If you need more time, that's fine, but please let us know.

**Comment by pavolo99** [comment]
@knjk04 Issue is resolved. You can close it.
