### ISSUE TITLE
Import books from Goodreads

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#77]
**Describe the solution you'd like**
Take in a csv file that was exported from Goodreads and import it into the app.

If a particular book was in a bookshelf that corresponds to a 'to read', reading or read predefined book shelf, the import tool should be able to automatically move the book into that shelf. Otherwise, the user needs to be prompted and asked which shelf to put the book in.

An imported book should be bound by the relevant fields.

**Additional context**
[Sample file](https://www.goodreads.com/assets/sample_export.csv)

- Refer to Vaadin's documentation on the [upload component](https://vaadin.com/components/vaadin-upload/java-examples)

- We can ignore the average rating, year published and original publication year columns
- If a date read has been speciifed, the book should go in the 'read' shelf
- Until the publisher and binding (we call it 'book type') attributes are added to the `Book` entity, we can ignore it 
- If a book does not have a title and/or an author, we do not add it
- Since we're using a 10-point scale, we should scale any ratings by 2 (Goodreads uses a 5-point scale with no half stars)
- If a user has a book shelf that we don't have for the user, we need to add it
- If there are any errors in parsing the file (e.g. a missing required field), ignore that row, but try to add as many books as possible (not atomic)

In the future, we will provide the user with an option to review the imports. This would allow a user to make any changes (e.g. update their rating)

**Comment by knjk04** [comment]
This can be unblocked once custom shelves are in place

**Comment by c99SRS** [comment]
Hi @knjk04 , Can I work on this?

**Comment by knjk04** [comment]
Unfortunately, we only [assign one issue at a time to new contributors](https://github.com/Project-Books/book-project/blob/master/CONTRIBUTING.md#new-contributors-assigned-to-at-most-one-issue-at-a-time). Once you've completed your other issue, if this issue is still unassigned, feel free to request to be assigned

**Comment by labradav** [comment]
Hi @knjk04 , can I work on this?

**Comment by knjk04** [comment]
@labradav Sure, thanks!

**Comment by labradav** [comment]
Hey @knjk04 , I'm trying to run `mvn clean install` but getting the following error in Intellij:

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project book-project: Fatal error compiling: invalid target release: 11 -> [Help 1]`

I have selected the Project SDK version as Java 11. Any idea what I might be doing wrong?

**Comment by knjk04** [comment]
Not at first glance, but feel free to join our [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-i7lept44-rgJ9yB0A2vedJTLyyfkjKQ) workspace and then we (myself or someone else) can help you out with this

**Comment by knjk04** [comment]
@labradav As discussed over Slack, I've provided some more context

**Comment by knjk04** [comment]
@labradav I know you have a draft PR created for this. As you're still working on this, I think it's unlikely that we'll get time to review & merge before the end of Hacktoberfest, so I'll remove the label. Are you still happy to work on this?

**Comment by labradav** [comment]
@knjk04 Yes I would like to complete it irrespective of Hacktoberfest.

**Comment by knjk04** [comment]
@labradav That's great to hear, thanks!

**Comment by knjk04** [comment]
@amit1307 Could you please try this on macOS?
