### ISSUE TITLE
Make 'VIEW ALL' text the same height as the shelf name

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#771]
**Describe the bug**

![image](https://user-images.githubusercontent.com/11173328/135128099-584f6010-0edd-4181-9d7d-5a02d51a1338.png)

Make 'VIEW ALL' the same height as the shelf name. It is currently aligned with the bottom, but it should also have the same height as the top

**Expected behaviour**

![image](https://user-images.githubusercontent.com/11173328/135127924-e1672130-77a4-4796-9a8a-f9cd00a90d98.png)

It should look like the above

**Additional context**

- Read our contributing guidelines first!
- Discuss your implementation approach with us first
- Branch from main and set main as the destination branch in your pull request

**Comment by rachelsalazar** [comment]
Hi @knjk04, could I please work on this issue?

**Comment by knjk04** [comment]
Hi @rachelsalazar, sure. Thanks!
