### ISSUE TITLE
Create a JSON patch method in the book controller

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#775]
**Describe the solution you'd like**
In the [update ](https://github.com/Project-Books/book-project/blob/main/backend/src/main/java/com/karankumar/bookproject/backend/controller/BookController.java#L131)method of our BookController, use JSON patch to determine what attribute to change.

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Branch from `main` and set `main` as the destination branch in your pull request

**Comment by mslowiak** [comment]
Hi @knjk04, can I work on that issue? :)

**Comment by knjk04** [comment]
Hi @mslowiak, sure! Thanks! If you need a hand with anything, feel free to ask on our #book-project channel on Slack or by creating a new GitHub Q&A discussion
