### ISSUE TITLE
Create goal modal

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#776]
**Describe the solution you'd like**
When a user clicks on the following 

![image](https://user-images.githubusercontent.com/11173328/135134544-e55fd60a-26ff-47f5-b357-321b1a1b7703.png)

we should open a new goal component that looks like the image below:

![image](https://user-images.githubusercontent.com/11173328/135134592-48fe4f10-bfb4-40b7-8f39-5ec9a8f609a8.png)

If 'Books' is selected rather than 'Pages', it should look like the image below:

![image](https://user-images.githubusercontent.com/11173328/135134691-3f6c00a6-e401-4853-b56a-fd722687012c.png)

In both cases, the modal should be responsive like our other modals. The input field should only accept positive numbers greater than 1.

We haven't set up the backend endpoints yet, so clicking on 'Add goal' should not yet do anything.

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Branch from `main` and set `main` as the destination branch in your pull request

**Comment by aryanchopra** [comment]
hey, I'd like to work on this feature, could you assign me to it?

**Comment by knjk04** [comment]
Hi @aryanchopra, sure! Thanks a lot! If you need a hand with anything, feel free to ask on our #book-project channel on Slack or by creating a new GitHub Q&A discussion
