### ISSUE TITLE
Make list view sortable

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#778]
**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/11173328/135137628-fd530c24-08d2-4148-be47-345d1d3b6fdd.png)

Clicking on any of the columns should sort by that column. By default, we should sort from in ascending order (A-Z for all columns except for rating, where should sort numerically). We should display a small up arrow next to the column to indicate it is being sorted. Clicking again should display a down arrow and sort in descending order. Clicking a third time should undo the sort.

We should allow for multiple columns to be sorted at any given time (multiple sorts).

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Branch from `main` and set `main` as the destination branch in your pull request

**Comment by Devenkapoor7303** [comment]
Hey can I work on this issue?

**Comment by knjk04** [comment]
Hi @Devenkapoor7303, sure, I'll assign you to the issue. Thanks!

**Comment by knjk04** [comment]
@Devenkapoor7303 How are you getting on with this issue? If you need any help on this, feel free to reach out to us on [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-punc8os7-Iz9PTCAkYcO_0S~XwtO5_A)

If you need more time, that's fine, but please let us know.

**Comment by knjk04** [comment]
Hi @LoicB, thanks! I'll assign you

**Comment by LoicB** [comment]
Hi @knjk04 Yes, I am still interested, thanks

**Comment by shivampapat** [comment]
Hey, is this issue still open?

**Comment by knjk04** [comment]
Hi @shivampapat, @LoicB is currently working on this
