### ISSUE TITLE
Send email confirmations

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#779]
**Describe the solution you'd like**
Send an email confirmation when a user creates a new account, changes their password or deletes their account.

We should have a new Maven module for this email notification service.

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Branch from `main` and set `main` as the destination branch in your pull request

**Comment by MartinSedlacko** [comment]
Hello, 

I would like to work on this task.

**Comment by knjk04** [comment]
Hi @MartinSedlacko, thanks for your interest in this! Could you please let us know what your implementation approach is before we assign you?

**Comment by MartinSedlacko** [comment]
This would be my approach
        * create parent pom and new module for EmailService 
	* add dependency for spring-boot-starter-mail
	* configuration to application.properties for Spring Boot Mail(host, port, username, password, auth, starttls)
	* create EmailServiceImpl which contains method to sendEmail(from, to, subject, body)
	* create EmailTemplate class for newAccount, changePassword and deleteAccount messages.
	* call method sendEmail from UserController after successfull action(new Account created, changed Passowrd or deleted account).

**Comment by knjk04** [comment]
@MartinSedlacko Thanks, I've assigned you to the issue!

**Comment by knjk04** [comment]
How are you getting on with this issue? If you need any help on this, feel free to reach out to us on [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-punc8os7-Iz9PTCAkYcO_0S~XwtO5_A)

If you need more time, that's fine, but please let us know.

**Comment by MartinSedlacko** [comment]
Almost done, I need to make just a few changes and it will be ready for PR.
