### ISSUE TITLE
Create book overview page

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#780]
**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/11173328/135140577-114dfec0-29d2-43b2-bca0-45babb5928ed.png)

Create a book details that looks like the following. It should use the details we get back from the backend. We should route to this page if a user clicks on one of the rows in the list view (not the shelf view for now).

Clicking on the pencil icon and 'Submit a review' should not do anything for now.

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Branch from `main` and set `main` as the destination branch in your pull request

**Comment by pato060** [comment]
Hello, I would like to work on this issue.

**Comment by knjk04** [comment]
Hi @pato060, sure, I'll assign you to the issue. Thanks!

**Comment by knjk04** [comment]
Hi @pato060, how are you getting on with this?

**Comment by pato060** [comment]
> Hi @pato060, how are you getting on with this?

Hey, it is completed you have already approved my PR.

**Comment by knjk04** [comment]
@pato060 Oops, thanks!
