### ISSUE TITLE
Remove drop shadow from buttons

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#787]
**Describe the solution you'd like**
Our buttons should not have any drop shadow. Change the following set of buttons:

The add buttons on the 'my books' page
![image](https://user-images.githubusercontent.com/11173328/135501222-abb36bcb-f002-445e-818b-0296f85feaeb.png)

The buttons in the 'Add shelf' modal 
![image](https://user-images.githubusercontent.com/11173328/135501285-c6cc258e-5b59-4fe8-ae1f-8426ff7f2084.png)

Log in button at root page
![image](https://user-images.githubusercontent.com/11173328/135501502-a0950721-120b-44d7-abda-f6f6aee9be60.png)

Create account button
![image](https://user-images.githubusercontent.com/11173328/135501568-1ae19ac2-6bb7-41d4-a81b-c583d1972f68.png)

**Without drop shadow**

The add buttons on the 'my books' page:
![image](https://user-images.githubusercontent.com/11173328/135502077-c4b6ffe5-ca5d-47de-b1ae-10d7c6b60c6f.png)

Add shelf modal buttons:
![image](https://user-images.githubusercontent.com/11173328/135502134-109b9d0d-a799-46ea-8e50-278b9483c406.png)

Log in button:
![image](https://user-images.githubusercontent.com/11173328/135501708-bb46b546-f707-4523-994b-6a6d684caf45.png)

Create account button:
![image](https://user-images.githubusercontent.com/11173328/135501986-21653ed6-0595-4560-8a99-737f593bca3a.png)

You can also refer to our [Figma mockups](https://www.figma.com/proto/MWYSlKNoyg3Ja3EAeectcQ/Book-Project-UI-(Copy)?node-id=11%3A76&scaling=min-zoom) to see how the buttons should look.

**Additional context**
- Be sure to read the contributing guidelines first!
- Branch from `main` and set `main` as the destination branch in your pull request

If you need help with anything, we'll be happy to help you over a [GitHub Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) or our [Slack workspace](https://camo.githubusercontent.com/eef8443bce0a2fdc0706ffcd99f91181ac849a4ef423a1ed61386ca0a8b448bb/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f736c61636b2d7465616d626f6f6b70726f6a6563742d3441313534423f6c6f676f3d736c61636b)

**Comment by ProCode2** [comment]
@knjk04 Can I take this up? If so, Please assign me this issue.

**Comment by harshmathurx** [comment]
I would like to take this issue up
I tried this in my own fork 
We need to add a prop called `disableElevation` to the button element 
Please assign it to me

**Comment by knjk04** [comment]
Hi @ProCode2, sure, I'll assign you to the issue. Thanks!

**Comment by knjk04** [comment]
Hi @harshmathurx, sorry but Pradipta got there ahead of you by a few minutes. I can let you know if this becomes available again for whatever reason, though

**Comment by harshmathurx** [comment]
> Hi @harshmathurx, sorry but Pradipta got there ahead of you by a few minutes. I can let you know if this becomes available again for whatever reason, though

it's all good, I understand :)
sure lmk, thanks

**Comment by ProCode2** [comment]
Sorry guys, I didn't check this one anymore as @harshmathurx had already done it and uploaded screenshots. You can take this one up.

**Comment by knjk04** [comment]
@harshmathurx I'll assign you to this, thanks!

**Comment by harshmathurx** [comment]
Thanks
