### ISSUE TITLE
Add React tests

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#789]
**Describe the solution you'd like**
We currently don't have any tests for our React frontend. Add some meaningful React tests.

See https://reactjs.org/docs/testing.html

**Additional context**
- Be sure to read the contributing guidelines first!
- Come up with a list of suggestions on what to test before we assign you. 
- Branch from `main` and set `main` as the destination branch in your pull request

If you need help with anything, we'll be happy to help you over a [GitHub Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) or our [Slack workspace](https://camo.githubusercontent.com/eef8443bce0a2fdc0706ffcd99f91181ac849a4ef423a1ed61386ca0a8b448bb/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f736c61636b2d7465616d626f6f6b70726f6a6563742d3441313534423f6c6f676f3d736c61636b)

**Comment by ShlokMohanty** [comment]
@knjk04 i want to take up and work on this issue can you assign me the task ?

**Comment by knjk04** [comment]
@ShlokMohanty Thanks for your interest in this.

> Come up with a list of suggestions on what to test before we assign you.

Note that for this issue we can require you to look through our code and come up with a list of things to test before assigning you to ensure we're both in agreement

**Comment by ShlokMohanty** [comment]
> @ShlokMohanty Thanks for your interest in this.
> 
> > Come up with a list of suggestions on what to test before we assign you.
> 
> Note that for this issue we can require you to look through our code and come up with a list of things to test before assigning you to ensure we're both in agreement

sure @knjk04 will come up with some suggestions
