### ISSUE TITLE
Set fetch types to lazy

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#80]
In the `Book` entity, the fetch types for the `Author` and `PredefinedShelf` fields are currently `eager`. They should be `lazy`.

**Comment by bhavika1** [comment]
Hi, I would like to work on this as my first issue.

**Comment by knjk04** [comment]
Sure, that would be great. Thanks!

**Comment by shadikajevand** [comment]
@knjk04 Hi, I can give this a try :)

**Comment by knjk04** [comment]
Sure, thanks!

**Comment by djnautiyal** [comment]
I'm not sure of the "hibernate" label, but may I take this up as a first timer?

**Comment by knjk04** [comment]
Sure, I'll assign you to the issue. 

As a heads-up, this may be tricky, so feel free to reach out to us on [Slack](https://codecov.io/gh/Project-Books/book-project) if you need anything. There's a discussion on the #book-project channel about how to go about solving it

**Comment by knjk04** [comment]
Unfortunately, we only [assign one issue at a time to new contributors](https://github.com/Project-Books/book-project/blob/master/CONTRIBUTING.md#new-contributors-assigned-to-at-most-one-issue-at-a-time). Once you've completed your other issue, if this issue is still unassigned, feel free to request to be assigned

**Comment by knjk04** [comment]
@djnautiyal 
How are you getting on with this issue? If you need more time, that's fine, but please let us know.

If you need any help on this, feel free to reach out to us on [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-i7lept44-rgJ9yB0A2vedJTLyyfkjKQ)

**Comment by djnautiyal** [comment]
Hi @knjk04 , I'm still studying on the issue. Have joined the slack group, and will connect once I have something substantial. Thank you for asking

**Comment by djnautiyal** [comment]
Hi @knjk04, I don't think I will be able to work on this. Kindly reassign the issue. Apologies for the trouble. I'll take up an easier issue.

**Comment by knjk04** [comment]
@djnautiyal That's fine, thanks for letting us know

**Comment by andrewass** [comment]
@knjk04 May i work on this issue?

**Comment by knjk04** [comment]
@andrewass Sure, I'll assign you to the issue. Thanks!

**Comment by kumawatanupriya** [comment]
@knjk04 Hi, May I work on it??

**Comment by knjk04** [comment]
@kumawatanupriya Sure, thanks again for your help!

**Comment by knjk04** [comment]
@kumawatanupriya How are you getting on with this issue?

**Comment by kumawatanupriya** [comment]
@knjk04 didn't get time, will work on it in coming days

**Comment by kumawatanupriya** [comment]
@knjk04 can you check this pull request https://github.com/Project-Books/book-project/pull/662

**Comment by kumawatanupriya** [comment]
Hi @knjk04, please check the pull request again.  #662

**Comment by kumawatanupriya** [comment]
Hi @knjk04 , please check the PR #662 again. I have used different approach.Let me know if that works or not.

**Comment by knjk04** [comment]
@kumawatanupriya Sure, I'll take a look. Thanks
