### ISSUE TITLE
Re-read books

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#81]
**Describe the solution you'd like**
Add the option to mark a book as being re-read. 

If a book is being read again, a new start date (and eventually end date) will be required.

**Comment by knjk04** [comment]
Re-read books should also count towards the reading goal

**Comment by lindnc5** [comment]
Hi, can I be assigned to this?

**Comment by knjk04** [comment]
Sure, I'll assign you to the issue. Thanks!

**Comment by knjk04** [comment]
@lindnc5 How are you getting on with this issue? If you need more time, that's fine, but please let us know.

If you need any help on this, feel free to reach out to us on [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-i7lept44-rgJ9yB0A2vedJTLyyfkjKQ)

**Comment by lindnc5** [comment]
Making progress on this again now, got a little busy.

**Comment by knjk04** [comment]
@lindnc5 Thanks for the update. So that we know whether we'll be able to get time to review and merge your PR in before the 31st of October (for Hacktoberfest), do you have an idea of when you'll have this completed by?

**Comment by knjk04** [comment]
@lindnc5 Just following up on this. Do you have an idea of when this will be completed by?

**Comment by knjk04** [comment]
@lidnc Unfortunately, as we have not heard back from you in a while, I will unassign you from the issue. This is in line with our contributing guidelines.

**Comment by amanjmd** [comment]
Hi, can I take this up? Although I am new to open source but I have gone through the contributors guide and am keen to work on such a project.

**Comment by knjk04** [comment]
Hi, sure. Thanks! If you need any help, feel free to create a GitHub discussion or connect with us over Slack

**Comment by amanjmd** [comment]
Hi , sure thanks . Will share the approach document soon.

**Comment by amanjmd** [comment]
[BookProject-re-read.pdf](https://github.com/Project-Books/book-project/files/6695991/BookProject-re-read.pdf)
Hi , please find attached the approach document. Kindly let me know , when can we discuss further.

**Comment by knjk04** [comment]
@amanjmd How are you getting on with this?

**Comment by knjk04** [comment]
Discussed offline

**Comment by knjk04** [comment]
Hi @amanjmd, how are you getting on with this issue?

**Comment by odfsoft** [comment]
Is this issue still available for assigment? I would like to work on it

**Comment by knjk04** [comment]
@amanjmd Unassigning due to no reply

**Comment by knjk04** [comment]
@odfsoft Are you still interested in working on this?

**Comment by amanjmd** [comment]
Yes Karan … I will work on it by next week … give some more time … I’ve
travelling quite a lot … not able to s type down much … will connect with
you by next week

**Comment by knjk04** [comment]
@amanjmd Do you have an update on this?

**Comment by knjk04** [comment]
@amanjmd Unassigning due to no response

**Comment by priya1712d** [comment]
Could I work on this one?

**Comment by knjk04** [comment]
@priya1712d Would you instead be interested in working on #947, as you have already looked into that?
