### ISSUE TITLE
Create statistics page

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#813]
**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/11173328/153915797-b741eaf3-4470-4629-aaaa-8927bf3a2358.png)

Create a statistics page that looks like the above. For the image, you can use one of the existing images we're already using. This data should be hardcoded for now (we'll later fetch this from the backend).

You'll also need to add a new item to the navigation bar (you can ignore the fact that the navigation bar looks slightly different).

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Branch from `main` and set `main` as the destination branch in your pull request

If you need help with anything, we'll be happy to help you over a [GitHub Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) or our [Slack workspace](https://camo.githubusercontent.com/eef8443bce0a2fdc0706ffcd99f91181ac849a4ef423a1ed61386ca0a8b448bb/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f736c61636b2d7465616d626f6f6b70726f6a6563742d3441313534423f6c6f676f3d736c61636b)

**Comment by adrianrojek** [comment]
Hello is this issue still open ?  I´d like to help, can you assign it to me ?

**Comment by ManishOffi** [comment]
Hye @knjk04 ,
Please assign me for this issue?

**Comment by knjk04** [comment]
Hi @ManishOffi, this is already assigned to Adrian. If this becomes available again for whatever reason, I'll let you know

**Comment by Emiliano-Russo** [comment]
Hello is this issue still open ? I´d like to help, can you assign it to me ?

**Comment by knjk04** [comment]
Hi @adrianrojek, I know you said you were still working on this, but how are you getting on (it's fine if you need more time)?

**Comment by knjk04** [comment]
@adrianrojek Unassigning due to no response

**Comment by knjk04** [comment]
Hi @Emiliano-Russo, are you still interested in picking this up?

**Comment by Kalshone** [comment]
Hello is this issue still open? I´d like to help, can you assign it to me?

**Comment by knjk04** [comment]
Hi @Kalshone, it's still open. Thanks, I'll assign it to you

**Comment by knjk04** [comment]
@Kalshone How are you getting on with this?

**Comment by knjk04** [comment]
@Kalshone Unassigning due to no response

**Comment by Girish-Bharadwaj** [comment]
Hello! I would like to work on this issue

**Comment by knjk04** [comment]
Hi @Girish-Bharadwaj, thanks for offering to help with this! I'll assign you to it. I've updated the issue description to match the same as the latest mockup designs

**Comment by Girish-Bharadwaj** [comment]
Hello @knjk04 
Here is the image link of the page on how it looks. If it's ok I will create a PR.
https://ibb.co/kx507jq

**Comment by knjk04** [comment]
Hi @Girish-Bharadwaj, this looks good so far! Here are a couple of thoughts on how you can get this even closer to the mockups:

- Centre the 'Statistics' header (if you could get this to work for all pages as well, that would be great!)
- Only capitalise the first word in the three book boxes ('Most Liked Book' would become 'Most liked book', etc.)
- Remove the shadow behind the book covers
- Add the spine effect (see #798) to the book covers
- The book covers should be slighter squarer (the corners are currently too rounded)
- Have the left side of the 'Most liked book' box align with the left side of the 'Most read genre' box
- Decrease the width between the left bottom boxes (most read genre and most liked genre) and the right bottom boxes 
- Make the border colour of the bottom boxes fainter (a lighter grey)

Thanks!

**Comment by Girish-Bharadwaj** [comment]
@knjk04 
I have worked on the design changes mentioned. Here is the link for the image
https://drive.google.com/file/d/1wNsY6eJFALFFWm1gqg6NLN6zpv3lhRjI/view?usp=sharing

I tried to center the Statistics heading but it will change the layout in the my-books component. So I thought we should pass 
the style or condition as a prop to the Layout component. Since I am new can you help out in any other way?

**Comment by knjk04** [comment]
Hi @RivaD2, is it possible for us to make a page component that all of our pages can inherit from that has a centred heading, like in the screenshot in the issue description?

**Comment by RivaD2** [comment]
> Hi @RivaD2, is it possible for us to make a page component that all of our pages can inherit from that has a centred heading (like in the screenshot in the issue description)?

Hi there! It is indeed :)

`Layout.tsx` is handling the Layout for components. This how many of the pages are inheriting a specific layout. `Layout.tsx` takes in `LayoutProps`, and that type (see bottom of `Layout.tsx` file) has a property called`centered` which is a boolean.

To get your page to have a centered header:
- import in the `Layout` component
- pass props of `centered` and set it to true -> `centered={true}`
- This should center it for ya. 

A helpful thing might be to first, review Layout component and props, then review `DeleteAccount.tsx` line 83 to see how centered prop is passed :) 👍

**Comment by Girish-Bharadwaj** [comment]
Hi
Thank you so much for guiding me.
I used the prop to center the Layout page.
Here is the link to the screenshot of the page.
https://drive.google.com/file/d/1wsXOloqfYEvGZzYCC53Rvpk5wOxClW8w/view?usp=sharing

**Comment by knjk04** [comment]
Hi @Girish-Bharadwaj,

Thanks, this is good progress. One thing I noticed is the subtexts (e.g. 'biography') do not align with the heading (e.g. 'Most read genre'). 

Could you please update this? Thanks!

**Comment by Girish-Bharadwaj** [comment]
Yeah sure. Will update those changes

**Comment by Girish-Bharadwaj** [comment]
@knjk04 I have updated the changes.
Here is the screenshot link: https://drive.google.com/file/d/1wsXOloqfYEvGZzYCC53Rvpk5wOxClW8w/view

**Comment by knjk04** [comment]
@Girish-Bharadwaj That looks great, thanks a lot! You should be ready for creating a pull request

**Comment by sophiastr** [comment]
i want to deal with this issue.
I am interested in contributing to the project you are developing.
Do you still need help?
I'm a beginner but I will try really hard.

**Comment by knjk04** [comment]
Hi @sophiastr, this issue has already been assigned, but feel free to request to be assigned to a non-blocked and unassigned issue: https://github.com/Project-Books/book-project/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee+-label%3Ablocked
