### ISSUE TITLE
Add more integration tests

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#817]
**Describe the solution you'd like**
In addition to testing our entire backend (from the endpoint to the database call), we will also have Spring REST docs for that controller.

Similar to our [UserControllerIntegrationTest](https://github.com/Project-Books/book-project/blob/main/backend/book-app/src/test/java/com/karankumar/bookproject/integration/UserControllerIntegrationTest.java), add some meaningful integration tests that cover different scenarios (e.g. branches, edge cases).

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Branch from `main` and set `main` as the destination branch in your pull request

If you need help with anything, we'll be happy to help you over a [GitHub Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) or our [Slack workspace](https://teambookproject.slack.com/join/shared_invite/zt-punc8os7-Iz9PTCAkYcO_0S~XwtO5_A#/shared-invite/email)

**Comment by maykim51** [comment]
@knjk04  Could I work on this issue? I'd like to work on this case:
- "check if the service passes in a weak password or an email that already exists in our db when creating an account, an exception is thrown"

**Comment by vladimirr9** [comment]
Hello, I'd maybe want to look more into practicing writing tests as well as help you out. The links seem broken on my side.

**Comment by knjk04** [comment]
Hi @vladimirr9, thanks for your interest in this. I've updated the links. Before I assign you, could you please come up with a list of what to test and let us know?

**Comment by erinmcconnell12** [comment]
@knjk04, could I work on test cases for this? I could add some parameterized tests in order to ensure weak passwords fail and strong/very strong passwords pass, and/or create tests for a user attempting to create an account with a previously linked email address, if that has not already been implemented.

**Comment by knjk04** [comment]
@erinmcconnell12 Thanks, both sound good. I'll assign you to this. Let us know if you need a hand with anything via Slack or a GitHub discussion
