### ISSUE TITLE
Avoid Lombok pitfalls

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#825]
**Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/11173328/136708571-cbf93334-f923-4eda-865e-b7c614a0502d.png)

Ensure the code in our [model package](https://github.com/Project-Books/book-project/tree/main/backend/src/main/java/com/karankumar/bookproject/backend/model) adheres to newly added Lombok section in [our style guide](https://project-books.github.io/docs/development/styleguides/java-styleguide/).

[See pitfalls article](https://www.jpa-buddy.com/blog/lombok-and-jpa-what-may-go-wrong/).

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Branch from `main` and set `main` as the destination branch in your pull request

If you need help with anything, we'll be happy to help you over a [GitHub Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) or our [Slack workspace](https://camo.githubusercontent.com/eef8443bce0a2fdc0706ffcd99f91181ac849a4ef423a1ed61386ca0a8b448bb/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f736c61636b2d7465616d626f6f6b70726f6a6563742d3441313534423f6c6f676f3d736c61636b)

**Comment by pedro-cze** [comment]
Hi @knjk04, I could have a look at this one in case it's available. Many thanks.
