### ISSUE TITLE
Add paging for get all books endpoint

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#839]
**Is your feature request related to a problem? If so, please describe.**
Returning all books may be a very large payload.

**Describe the solution you'd like**
Return a fixed size (for now, we will hardcode this to 50 per page) of results per page. Our [endpoint](https://github.com/Project-Books/book-project/blob/main/backend/book-app/src/main/java/com/karankumar/bookproject/controller/BookController.java#L107) should take the page number rather than returning all results.

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Branch from `main` and set `main` as the destination branch in your pull request

If you need help with anything, we'll be happy to help you over a [GitHub Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) or our [Slack workspace](https://camo.githubusercontent.com/eef8443bce0a2fdc0706ffcd99f91181ac849a4ef423a1ed61386ca0a8b448bb/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f736c61636b2d7465616d626f6f6b70726f6a6563742d3441313534423f6c6f676f3d736c61636b)

**Comment by knjk04** [comment]
Hi @kapilgahlot1998, sure. Thanks!

**Comment by kapilgahlot1998** [comment]
Hi 
I have updated the all book API endpoint. Now it will also take page number as a request param. But for this change in UI also need to update API call. Can I update the API call in UI ?

**Comment by kapilgahlot1998** [comment]
Hi 
There was one sonar cloud issue for a todo comment that i have added for informing purpose. As of now I have removed that todo.
Please review

**Comment by sushantohalder** [comment]
is this issue closed?

**Comment by sushantohalder** [comment]
@knjk04 please assign this to me.. I am interested to work on this

**Comment by knjk04** [comment]
@sushantohalder How are you getting on with this?

**Comment by vladimirr9** [comment]
Hello I'd be willing to try this if possible.

**Comment by knjk04** [comment]
@sushantohalder Unassigning due to no repsonse

**Comment by knjk04** [comment]
@vladimirr9 Thanks, I'll assign you to it!

**Comment by knjk04** [comment]
@vladimirr9 How are you getting on with this?

**Comment by vladimirr9** [comment]
Going well, we discussed it on slack
