### ISSUE TITLE
Add input validation when updating user password

### ISSUE THREAD

**Issue by adrianbranescu** [Project-Books/book-project#861]
When a user wants to change account password, certain constraints for the new password need to be met.
Currently, a user can change a password with an invalid one.

Password validation constraints are already applied at user registration, but nothing prevents the user from later changing the password with an invalid one.

![ChangePassword](https://user-images.githubusercontent.com/59761765/147314876-5444cc7e-8957-47cf-bb03-29b65df6cfb2.png)

**Comment by BigOsvaap** [comment]
I would like to work on this issue if that is possible

**Comment by knjk04** [comment]
Thanks, @BigOsvaap!
