### ISSUE TITLE
Material UI text field text overlaps with text field border

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#864]
**Describe the bug**

![image](https://user-images.githubusercontent.com/11173328/148653312-7fa97766-a9b6-4ba4-a792-fef83b494de0.png)

The text for a text field overlaps the text field border when you click on it.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to http://localhost:3000/
2. Click on the username or password text field
3. See the error

**Expected behaviour**

![image](https://user-images.githubusercontent.com/11173328/148653248-d0270066-162e-4372-a662-4c0025e9ccaf.png)

The text should not overlap the text field border, as with the above image.

**Additional context**

- Read our contributing guidelines first!
- Discuss your implementation approach with us first
- Provide us with an estimate on how long you think it will take you to complete
- Branch from main and set main as the destination branch in your pull request

Add any other context about the problem here (e.g. stack trace, branch name, commit hash, etc.).

**Comment by Krishpandya682** [comment]
Hi, this is literally my first open source contribution and I do not know if this solution is feasible to you or not but I have just figured out that the issue gets resolved by installing the @mui/material library along with a couple other libraries and changing a few imports from @material-ui/core to @mui/material. If this is an appropriate solution can I implement that change?

**Comment by knjk04** [comment]
Hi @Krishpandya682. Sure, go for it. We still want it to be pill-shaped rather than rectangular. Thanks!
