### ISSUE TITLE
Verify that the BookDto has the required fields

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#871]
**Is your feature request related to a problem? If so, please describe.**

For simplicity, we assumed that the object being passed into the response is valid.

**Describe the solution you'd like**

Verify that the `BookDto` object being passed in has the required fields (title, author & predefined shelf): https://github.com/Project-Books/book-project/blob/main/backend/book-app/src/main/java/com/karankumar/bookproject/controller/BookController.java#L130. If not, we should return a new exception (400 bad request).

We should be using Spring's validation annotations to automatically validate the input: https://docs.spring.io/spring-framework/docs/3.2.x/spring-framework-reference/html/validation.html#validation-mvc-triggering.

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Provide us with an estimate on how long you think it will take you to complete
- Branch from `main` and set `main` as the destination branch in your pull request

If you need help with anything, we'll be happy to help you over a [GitHub Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) or our [Slack workspace](https://camo.githubusercontent.com/eef8443bce0a2fdc0706ffcd99f91181ac849a4ef423a1ed61386ca0a8b448bb/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f736c61636b2d7465616d626f6f6b70726f6a6563742d3441313534423f6c6f676f3d736c61636b)

**Comment by jackippolito4** [comment]
I will take this up!

**Comment by gabrielronei** [comment]
Hi, can i take this one?

To solve this, i'm going to use `@Valid` from `javax.validation` on parameter of the controller to validate fields on BookDTO that i'm going to anotate with `@NotBlank` from `javax.validation.constraints` and with this, the controller will throw a BAD REQUEST if is invalid.

I think that i can finish it in an hour, to setup the project, add the validation and test.

**Comment by jackippolito4** [comment]
> Hi, can i take this one?
> 
> To solve this, i'm going to use `@Valid` from `javax.validation` on parameter of the controller to validate fields on BookDTO that i'm going to anotate with `@NotBlank` from `javax.validation.constraints` and with this, the controller will throw a BAD REQUEST if is invalid.
> 
> I think that i can finish it in an hour, to setup the project, add the validation and add the controller test.
> 
> I have only one question about, the max and the min of the strings(title, author and predefined shelf). Does it have a limit?

I would like to do this part I have been talking directly to knjk04 directly about it

**Comment by knjk04** [comment]
Thanks, @jackippolito4. I'll assign this to you

**Comment by knjk04** [comment]
Hi @gabrielronei, I'm afraid Jack asked first, but I'll be adding some more backend issues in due course

**Comment by gabrielronei** [comment]
@jackippolito4 @knjk04 no problem guys, thank you for the answer :heart:

**Comment by jackippolito4** [comment]
@gabrielronei If you join the slack, we can communicate there and you can assist me

**Comment by knjk04** [comment]
@jackippolito4 How are you getting on with this?

**Comment by knjk04** [comment]
@jackippolito4 Unassigning due to no response

**Comment by knjk04** [comment]
@gabrielronei Are you still interested in helping with this?

**Comment by anujasupekar** [comment]
Hi, if this issue is unassigned, I would like to work on this task

**Comment by knjk04** [comment]
Hi @anujasupekar, thanks! I'll assign this to you
