### ISSUE TITLE
User not informed if password is not strong enough

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#874]
**Describe the bug**

If a user types in a strong password when trying to create an account, we should inform them that only very strong passwords are allowed. We should only show this error message (red text underneath the 'sign in' button, like our other error messages) when the user clicks on the 'Create account' button (or presses enter).

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to http://localhost:3000/sign-up
2. Enter `testemail@test.com` for the email address
3. Enter `Testeando123` in the password and confirm password fields
4. Click on the create account button
5. See error

**Expected behaviour**

The following error message (red text) should display:

Your password is too weak, only very strong passwords are allowed. Please try again.

**Screenshots**

![image](https://user-images.githubusercontent.com/11173328/151524725-ba29abea-7a44-4c8f-a620-8002da9fac50.png)

**Additional context**

See `onCreateAccountClicked()` in `Register.tsx`:

![image](https://user-images.githubusercontent.com/11173328/151525496-a31c0e53-82dc-4174-8bad-40a3a555d6ce.png)

Where the console.log line is, we should add a check to see if the password is not very strong and, if so, display the error message. We can then remove the condition that checks this in the if statement (which could not be an else if).

- Read our contributing guidelines first!
- Discuss your implementation approach with us first
- Provide us with an estimate on how long you think it will take you to complete
- Branch from main and set main as the destination branch in your pull request

Add any other context about the problem here (e.g. stack trace, branch name, commit hash, etc.).

**Comment by GrahamKirwan** [comment]
@knjk04 Can I take this? Can have it completed today

**Comment by knjk04** [comment]
@GrahamKirwan sure, thanks!
