### ISSUE TITLE
Show email taken error message

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#877]
**Is your feature request related to a problem? If so, please describe.**
We currently do not show an error message when this fails, so a user may not know what is wrong (they are clicking the create account button but nothing is happening).

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/11173328/151530989-05fffc44-5605-4b4d-8d87-eb9cc590fa43.png)

If an email is taken, we receive this error message in the response from the backend. We should display this as red error text (like we do elsewhere) back to the user.

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Provide us with an estimate on how long you think it will take you to complete
- Branch from `main` and set `main` as the destination branch in your pull request

If you need help with anything, we'll be happy to help you over a [GitHub Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) or our [Slack workspace](https://teambookproject.slack.com/join/shared_invite/zt-punc8os7-Iz9PTCAkYcO_0S~XwtO5_A#/shared-invite/email)

**Comment by ahmedsaheed** [comment]
hi @knjk04 can i jump on this as my first issue. Seems very feasible.

**Comment by nbentoneves** [comment]
Hi, I would like to be part of the project. Can I pick this one?
Thanks

**Comment by nbentoneves** [comment]
**Additional context**
- Be sure to read the contributing guidelines first!: ✔️ 
- Discuss your implementation approach with us before we assign you to it: 
Create a new state attribute to store the registration failed message (like the project does for Login), my suggestion is `registerFailed`. Showing the error the same way the project does for the `state.serverError`.
- Provide us with an estimate on how long you think it will take you to complete: ~1 week with testing
