### ISSUE TITLE
Redesign navigation bar

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#879]
**Describe the solution you'd like**

Our current navigation bar:

![image](https://user-images.githubusercontent.com/11173328/151532004-47a8a5fd-103a-47d1-b68f-5c6d9cea54e1.png)

Desired:

![image](https://user-images.githubusercontent.com/11173328/151531976-05602c83-dcc7-45e9-b7a0-425443cdde11.png)

We would like our navigation bar to look like the image above. This includes:

- Showing a rectangular grey box (with rounded corners) around the currently selected item (page)
- Change the text colour from black to grey
- Replace the grey shadow line with the non-shadow line
- Make the logout button text red

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Provide us with an estimate on how long you think it will take you to complete
- Branch from `main` and set `main` as the destination branch in your pull request

If you need help with anything, we'll be happy to help you over a [GitHub Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) or our [Slack workspace](https://teambookproject.slack.com/join/shared_invite/zt-punc8os7-Iz9PTCAkYcO_0S~XwtO5_A#/shared-invite/email)

**Comment by JustinStrik** [comment]
Can I pick up this issue?

**Comment by knjk04** [comment]
Hi @JustinStrik, thanks for your interest. How long do you think it will take you to complete this?

**Comment by mayanksony** [comment]
Is this issue still open?
Can I contribute?

**Comment by knjk04** [comment]
Hi @mayanksony, how are you getting on with this?

**Comment by knjk04** [comment]
Hi @mayanksony, we will unassign this from you as we have not heard back

**Comment by Melodyyueqi** [comment]
Hi, is this issue still open? Can I try to contribute?

**Comment by TomBurrows101** [comment]
Hi,

I'd like to take this issue up, to confirm, all that is left is:
- Add a (curved edged) box around the active item
- Change the text from black to grey
- Change the grey shadow line to the non-shadow line

I believe that is all left to do, after a previous PR changed the logout button colour?
