### ISSUE TITLE
Show book search results

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#882]
**Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/11173328/151540891-d7908cb4-8c92-4549-8a5d-b99033688b84.png)

Show the book search results we get from our Books API (GraphQL server). It should look like the mockup above. For now, we can use the same image for all of the search results because we won't be able to retrieve the thumbnails from the backend, but we should display the right author and title.

There should be at most four books shown per row. This should be responsive -- it should show fewer books for smaller devices.

When there are no results:

![image](https://user-images.githubusercontent.com/11173328/151540825-a053b044-ec17-4f22-8994-fe4723359220.png)

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Provide us with an estimate on how long you think it will take you to complete
- Branch from `main` and set `main` as the destination branch in your pull request

If you need help with anything, we'll be happy to help you over a [GitHub Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) or our [Slack workspace](https://teambookproject.slack.com/join/shared_invite/zt-punc8os7-Iz9PTCAkYcO_0S~XwtO5_A#/shared-invite/email)

**Comment by knjk04** [comment]
@RivaD2 Would you be interested in picking up this issue?

**Comment by RivaD2** [comment]
> @RivaD2 Would you be interested in picking up this issue?

@knjk04, yes I would be happy to take this one on 👍 

My approach here would be continuing to build off of my last PR (Issue #772). I should map over the `data` returned from the GraphQL query and render it (I already set the component up for this).

 I will use CSS grid and build a responsive layout similar to the layout I built for our list view ( I think flexbox could work nicely here too). I can use conditional rendering to show books if there are some, or the image provided if results are not found.

It might be nice to build a separate component for results not found and then import that in to the `searchResults` component (not sure if that is overkill but it is a thought...)

I expect to have this done by the end of next week 👍 

**Questions:**
-  Can you provide me with the image for results not found so I can use it?
- Can you send me the link to our mockups?
- The filter button beside the search input  in the example shown above is not something I should add right now correct? From what I see here, I should focus on layout and rendering results.
                        
Thank you Karan :)

**Comment by knjk04** [comment]
Sounds good, thanks! 

> It might be nice to build a separate component for results not found and then import that in to the searchResults component (not sure if that is overkill but it is a thought...)

I don't think we need this as a separate component right now, but it's a good idea

I'll ask Braja (the person working on the mockups) for the image and I'll email the link over. Yes, we can ignore the filter button for now (I should have mentioned that!)

**Comment by RivaD2** [comment]
@knjk04 I assigned myself to the ticket 👍  ( I forgot I could do that :)).

**Comment by RivaD2** [comment]
@knjk04 
Last two questions for now:

Will I be using same query to show book results (`findByTitleIgnoreCase()`)?

Do we already have books in the database? I see the model in Book-API but can't seem to locate the books.

**Comment by RivaD2** [comment]
> @knjk04 Last two questions for now:
> 
> Will I be using same query to show book results (`findByTitleIgnoreCase()`)?
> 
> Do we already have books in the database or do I need to add books to the DB? If I do need to add them, I might need some guidance on where to start.
> 
> I can see the instructions on the Books-API repo for accessing the DB.

@knjk04 Do you have any updates on the above? ( I know you are super busy 👍  I wanted to follow up on this so I can work on it soon) 👍

**Comment by knjk04** [comment]
@RivaD2 Thanks for following up. Sorry, I thought I responded to this.

> Will I be using same query to show book results (findByTitleIgnoreCase())?

Yes, it'll be the same query.

> Do we already have books in the database or do I need to add books to the DB? If I do need to add them, I might need some guidance on where to start.

We have books in our test database. The books we have in this script are the ones you should see if you search for them: https://github.com/Project-Books/books-api/blob/main/src/main/resources/db/migration/V23__INSERT_BOOKS.sql.

**Comment by RivaD2** [comment]
> @RivaD2 Thanks for following up. Sorry, I thought I responded to this.
> 
> > Will I be using same query to show book results (findByTitleIgnoreCase())?
> 
> Yes, it'll be the same query.
> 
> > Do we already have books in the database or do I need to add books to the DB? If I do need to add them, I might need some guidance on where to start.
> 
> We have books in our test database. The books we have in this script are the ones you should see if you search for them: https://github.com/Project-Books/books-api/blob/main/src/main/resources/db/migration/V23__INSERT_BOOKS.sql.

I tried making the query last week but I remember that it was not returning any books. Just to confirm, the graphql endpoint is still the same and I don't need to hit any other endpoints to return the books right?

 The query should just return the books from my understanding.

**Comment by knjk04** [comment]
It should be the same:

![image](https://user-images.githubusercontent.com/11173328/152656618-de3077b6-6b0b-41cd-8b40-74a38098366d.png)

If it doesn't work for you, perhaps check the logs to see if you encountered any errors. If no errors, you can check the database to check that you do have data in there. Let me know if you need a hand with any of this

**Comment by RivaD2** [comment]
@knjk04 I have a question regarding the layout. For now, when I search by author, it is not working. Do we have the query set up for this? If I search by title, that works fine.

Currently, at most, only 1 book will show. I type in  the name of one book into the searchbar and it returns that one book. If we were to search by authors, then that could potentially show more one.

**Comment by RivaD2** [comment]
@knjk04 How many books do we have in the DB? Is it 4?  It looks like we have 4 books, all with different titles and authors but with the same isbn #'s.

Currently, if I type in the title of one of the books into the search bar, I get that 1 book back which is great! 

However, my blockage right now is figuring out a way to get all books showing from the database using one query. 

Currently, the way it is set up is that the user has to type something into the search bar. When the page loads, the query is made but the data is null if nothing is entered into the search bar.

If I try to search using anything but the title of the books, the query results are null.

Do you have any guidance on this? Thank you advance for your assistance 👍

**Comment by knjk04** [comment]
@RivaD2 That's right, we currently have 4 (this is just in the test database, I'm looking to add more once I've sorted out some other issues with cloud providers). 

I'll need to change findByTitleIgnoreCase to return an array. I can also look to add some more books with the same name so we can test this properly (I've made a new GitHub issue ticket for this: https://github.com/Project-Books/books-api/issues/144). In the meantime (as a temporary solution), could you please add 8 results (duplicating the first one 7 times)?

**Comment by RivaD2** [comment]
@knjk04 sounds good! I will go ahead and update the component to show 8 books as requested.

 I believe I don't have access to the `cover` yet/thumbnails (as mentioned in issue) and the issue says to use same image for all books for now so I will see what I can find there. 👍

**Comment by RivaD2** [comment]
@knjk04 I followed the instructions on the repo for running the database and running the backend. I am getting an error: ` message from server: "Host '172.20.0.1' is not allowed to connect to this MySQL server"`. 

I am not sure where the ip is coming from etc. so perhaps you can take a look at recent changes 👍

**Comment by knjk04** [comment]
@RivaD2 Someone else recently encountered the [same issue](https://github.com/Project-Books/book-project/discussions/870#discussioncomment-2152141). I've migrated us from MySQL to PostgreSQL, so try the new instructions in the README and let me know if it's still not working (if you see any flyway issues in the backend, you can try running `./mvnw flyway:clean`

**Comment by RivaD2** [comment]
> @RivaD2 Someone else recently encountered the [same issue](https://github.com/Project-Books/book-project/discussions/870#discussioncomment-2152141). I've migrated us from MySQL to PostgreSQL, so try the new instructions in the README and let me know if it's still not working (if you see any flyway issues in the backend, you can try running `./mvnw flyway:clean`

@knjk04  Hi there! 

I used the repo instructions in the readme prior to my last message but I am still getting errors. There are two errors occurring, one for `running the database` , the other for `running the backend`.  The repo instructions for `running the db`  asks for users to: 
 - Navigate to the [backend/](https://github.com/Project-Books/book-project/tree/main/backend)[](https://github.com/Project-Books/book-project#access-database-optional) directory in a terminal
- Start the PostgreSQL database using `docker-compose up -d db`
- Once that is done though, this error is shown: `Can't find a suitable configuration file in this directory or any parent. Are you in the right directory?` The yml file is not found.


- The next error is when I `try to run the backend`. I follow instructions on readme, ( .mvnw clean install and then try to start app with provided jar file etc.) and then I then get the error I mentioned previously:

`"Host '172.20.0.1' is not allowed to connect to this MySQL server"`

**Comment by knjk04** [comment]
> It looks like we moved the docker files into a new directory book-app.

You're right, I've corrected the instructions in the readme. Let me know if the issue still persists with postgres

**Comment by RivaD2** [comment]
> > It looks like we moved the docker files into a new directory book-app.
> 
> You're right, I've corrected the instructions in the readme. Let me know if the issue still persists with postgres

@knjk04 Here is an update:

- In the `/book-app` directory, I ran `docker-compose up -d` vs `docker-compose up -d db`  and it worked fine (if I run the latter command, I get: `ERROR: No such service: db` 
- Then I navigated to `/backend` and followed instructions in readme to run the backend and I am still getting the same error message as mentioned previously: `"Host '172.20.0.1' is not allowed to connect to this MySQL server"`. 
- I then tried to run `./mvnw flyway:clean` because I did see a flyaway issue on backend and I still get the error message above in addition to other errors indicating the build failed:

<img width="1440" alt="Screen Shot 2022-02-14 at 9 13 56 AM" src="https://user-images.githubusercontent.com/67027945/153913230-1777acd4-6858-46e0-be86-2dc09ba4f7fb.png">

<img width="1357" alt="Screen Shot 2022-02-14 at 9 14 18 AM" src="https://user-images.githubusercontent.com/67027945/153913097-f4c47d72-e058-4051-9c4c-f1b2245be39a.png">

<img width="1414" alt="Screen Shot 2022-02-14 at 9 12 13 AM" src="https://user-images.githubusercontent.com/67027945/153912666-4651d8d8-8a8f-4bb6-a7f5-c75e88779efc.png">

<img width="1438" alt="Screen Shot 2022-02-14 at 9 09 39 AM" src="https://user-images.githubusercontent.com/67027945/153912543-c2053fbd-f6d7-4cad-aeba-25716accd8a8.png">

I am not sure how to proceed. Is there anything I might be missing, something we can check elsewhere?

**Comment by knjk04** [comment]
@RivaD2 Have you merged the latest changes from `main` into your branch? If you're still running into this issue, could you please create a draft PR and I can take a look further

**Comment by RivaD2** [comment]
@knjk04 When I first reported errors, I had already pulled all changes in. Now after doing another pull/getting branch even with main, I am still hitting errors after I try to start the application with the `jar` file. I also  tried running:`./mvnw flyway:clean` again (but no success).

I have created a draft so you can take a look.  👍
