### ISSUE TITLE
Create add book modal

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#883]
**Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/11173328/151536084-8d89e06a-b590-41ee-9204-5ed6e0211383.png)

When a user clicks on the add book button on the 'my books' page, we should show the modal above. 

- Pressing cancel or the 'X' button should close the modal
- Clicking reset should reset all fields to their default state

- For now, we will assume there is only allowed to be one author

- The pages field should only take integers (1 or greater)
- For the status field, exactly one option should be chosen (not multiple). See below for what it should look like when an option is chosen
- We should add validation to ensure that the book title and author's name field are not empty when the user clicks on the 'Add book' button
- We should get the list of shelves from the /api/books/genres (GET) endpoint. A user can select only one genre from this list

![image](https://user-images.githubusercontent.com/11173328/151539835-9b483976-9d2b-4d3d-a245-d4c45e94978a.png)

- We should get the list of shelves from the /api/shelf (GET) endpoint. A user can select multiple shelves from this list

![image](https://user-images.githubusercontent.com/11173328/151539566-76fd6dbe-f3e4-43c4-9c7d-801609b14fcb.png)

- When the user clicks on the add book button, we should call the /api/book (POST) endpoint

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Provide us with an estimate on how long you think it will take you to complete
- Branch from `main` and set `main` as the destination branch in your pull request

If you need help with anything, we'll be happy to help you over a [GitHub Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) or our [Slack workspace](https://teambookproject.slack.com/join/shared_invite/zt-punc8os7-Iz9PTCAkYcO_0S~XwtO5_A#/shared-invite/email)

**Comment by samspecial** [comment]
Glad the design for the add-book feature is finally out and I am interested in bringing this to reality @knjk04

**Comment by knjk04** [comment]
Thanks, @samspecial. How long do you think this will take you?

**Comment by samspecial** [comment]
> Thanks, @samspecial. How long do you think this will take you?

2 days

**Comment by samspecial** [comment]
> > Thanks, @samspecial. How long do you think this will take you?
> 
> 2 days

I am currently in the middle of a task which might hinder me from not working on this immediately. 
Kindly let me know if this seats well with you

**Comment by knjk04** [comment]
@samspecial That's fine, do you know roughly when you would be able to start working on this?

**Comment by samspecial** [comment]
> @samspecial That's fine, do you know roughly when you would be able to start working on this?

I should commence in the new week - 7th February 2022 to be precise

**Comment by knjk04** [comment]
That's fine, thanks for the update!

**Comment by knjk04** [comment]
Hi @samspecial, how are you getting on with this?

**Comment by samspecial** [comment]
> Hi @samspecial, how are you getting on with this?

@knjk04 I'll be starting today. Apologies for not updating you before now.

I will give an update later in the day

**Comment by knjk04** [comment]
@samspecial How are you getting on with this?

**Comment by samspecial** [comment]
> @samspecial How are you getting on with this?

I have been ill lately, just got back to work. This is why I have not responded since Friday.

Currently clearing my table, I will share screenshot by tomorrow as I might not be able to work on it today.

Sincere apologies.

**Comment by knjk04** [comment]
@samspecial No problem at all, I'm glad to hear you're better now (or I hope you get better soon)!

**Comment by samspecial** [comment]
Hi @knjk04 I am currently having issues writing my code to adapt to what is obtainable in the project repo. I have no worked with TypeScript before this time. I would love to request you avail me this weekend to go through the rudiment and basic of TypeScript needed to come up with the implementation as I have gone to buy Maximilian Schwarzmüller which I trust will facilitate me learning

**Comment by knjk04** [comment]
Hi @samspecial, would it be OK if I assign you to #884 instead? It would be good if we can get this particular issue implemented soon because it would allow us to test and release quicker
