### ISSUE TITLE
Redesign add goal modal

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#884]
**Describe the solution you'd like**

Current add goal modal:

![image](https://user-images.githubusercontent.com/11173328/151537583-22d4cfe3-c77f-4221-a338-7d641cfcdce1.png)

To see this, go to localhost:3000/goal and click on the no goal set box.

We would like the add goal modal to look like the following:

![image](https://user-images.githubusercontent.com/11173328/151537549-c605b59b-c93c-407a-b13b-a24175e3edd9.png)

Clicking on the dropdown should show the options 'books' and 'pages'.

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Provide us with an estimate on how long you think it will take you to complete
- Branch from `main` and set `main` as the destination branch in your pull request

If you need help with anything, we'll be happy to help you over a [GitHub Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) or our [Slack workspace](https://teambookproject.slack.com/join/shared_invite/zt-punc8os7-Iz9PTCAkYcO_0S~XwtO5_A#/shared-invite/email)

**Comment by Ashu5** [comment]
Hi @knjk04 Can I take this up?

**Comment by knjk04** [comment]
Hi @Ashu5, thanks for your interest. How long do you think it will take you to complete this?

**Comment by Ashu5** [comment]
Hi @knjk04 1 day of effort is fine. So I can complete it by 04 Feb.

**Comment by knjk04** [comment]
Hi @Ashu5, sorry, I missed this. Are you still interested in working on this?

**Comment by mayanksony** [comment]
can i contribute?

**Comment by knjk04** [comment]
@mayanksony We only assign at most one issue at a time to new contributors (see our contributing document). However, once your PR for the other issue is merged, you can then work on this if it's still available and you're still interested. Thanks!

**Comment by samspecial** [comment]
> @mayanksony We only assign at most one issue at a time to new contributors (see our contributing document). However, once your PR for the other issue is merged, you can then work on this if it's still available and you're still interested. Thanks!

@knjk04 You can go ahead to add me to this

**Comment by CGRDMZ** [comment]
i would like to work on this one @knjk04. i have some questions before starting. This will be my first contribution to an open source project, so i am sorry if the answers are so obvious.

1. The new design has a divider with the full width of the container but since the modal is a shared component and has a padding by default, is it okay for me to change the Modal component to take a prop for padding?
2. Is there a design file for the design in the image, so that i can have a reference? or should i just eyeball the values?

**Comment by didendron** [comment]
Hi @knjk04. Can i take this?
