### ISSUE TITLE
Show name of book in my books

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#885]
**Describe the solution you'd like**

Currently:

![image](https://user-images.githubusercontent.com/11173328/151538149-1c269b21-f97a-4bed-9299-cfc1fbcb437c.png)

We would like to show the name of the book instead of a blank rectangle:

![image](https://user-images.githubusercontent.com/11173328/151538214-f9cdcf25-3fca-4ace-b542-ddf0061ca948.png)

![image](https://user-images.githubusercontent.com/11173328/151538279-431f062e-7327-4637-8f2c-f3611a5f433d.png)

The name of each book should be centred. If there is not enough room to show the full book title, we should use an ellipsis (...). Each thumbnail should have a grey background and the spine effect, as in the above image.

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Provide us with an estimate on how long you think it will take you to complete
- Branch from `main` and set `main` as the destination branch in your pull request

If you need help with anything, we'll be happy to help you over a [GitHub Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) or our [Slack workspace](https://teambookproject.slack.com/join/shared_invite/zt-punc8os7-Iz9PTCAkYcO_0S~XwtO5_A#/shared-invite/email)

**Comment by priya1712d** [comment]
@knjk04 Hi!
I would like to work on this.

**Comment by knjk04** [comment]
@priya1712d Thanks!
