### ISSUE TITLE
Redesign book placeholder in list view on my books page

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#886]
**Describe the solution you'd like**

Current design:

![image](https://user-images.githubusercontent.com/11173328/151539081-2003d429-9f10-4bd8-b715-396913de3bd1.png)

Desired:

![image](https://user-images.githubusercontent.com/11173328/151538902-690fe056-7231-4c21-a533-032f32a6bc0f.png)

The book thumbnails should be taller and we should show an ellipsis (3 dots: ...) rather than cutting off the text. The thumbnails should be grey and have a spine effect

![image](https://user-images.githubusercontent.com/11173328/151539216-c1b34d90-be33-4d6d-b476-ffa9a44d3dfd.png)

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Provide us with an estimate on how long you think it will take you to complete
- Branch from `main` and set `main` as the destination branch in your pull request

If you need help with anything, we'll be happy to help you over a [GitHub Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) or our [Slack workspace](https://teambookproject.slack.com/join/shared_invite/zt-punc8os7-Iz9PTCAkYcO_0S~XwtO5_A#/shared-invite/email)

**Comment by knjk04** [comment]
@priya1712d Would you be interested in working on this?

**Comment by priya1712d** [comment]
sure!
