### ISSUE TITLE
Redesign view all button

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#888]
**Describe the solution you'd like**

Currently:

![image](https://user-images.githubusercontent.com/11173328/151542316-ed3df2b9-c874-4724-b386-f8e9fb2f5841.png)

Desired:

![image](https://user-images.githubusercontent.com/11173328/151542289-5b721a4b-c373-46dc-9c5c-f0c72ee4b026.png)
### 

On the my books page, we should redesign the view all button to look the like above image. This should show for all shelves.

![image](https://user-images.githubusercontent.com/11173328/151542385-efde4f1a-f1e4-4050-8098-40b49c0c98e5.png)

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Provide us with an estimate on how long you think it will take you to complete
- Branch from `main` and set `main` as the destination branch in your pull request

If you need help with anything, we'll be happy to help you over a [GitHub Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) or our [Slack workspace](https://teambookproject.slack.com/join/shared_invite/zt-punc8os7-Iz9PTCAkYcO_0S~XwtO5_A#/shared-invite/email)

**Comment by OrlundoHubbard** [comment]
@knjk04 I'd like to work on this issue.

**Comment by knjk04** [comment]
@OrlundoHubbard thanks for your interest. How long do you think it will take you to complete this?

**Comment by OrlundoHubbard** [comment]
I can have it done in a day or so.

**Comment by OrlundoHubbard** [comment]
@knjk04

**Comment by knjk04** [comment]
@OrlundoHubbard Thanks, I'll assign you to this

**Comment by OrlundoHubbard** [comment]
thanks! @knjk04

**Comment by OrlundoHubbard** [comment]
@knjk04 where can I find the code for this "view all" button? Which component is it in?

**Comment by knjk04** [comment]
Here it is: https://github.com/Project-Books/book-project/blob/main/frontend/src/shared/book-display/ShelfCarousel.tsx#L86

**Comment by OrlundoHubbard** [comment]
@knjk04 ah ok thank you.

**Comment by OrlundoHubbard** [comment]
@knjk04 how are the dependencies supposed to be run? What's the command? I get the below error when running `npm install -g yarn`
<img width="661" alt="Screen Shot 2022-01-31 at 2 33 30 PM" src="https://user-images.githubusercontent.com/88997637/151868813-451cd29e-8c1f-4f21-87a2-d88bcccfbd84.png">

**Comment by knjk04** [comment]
@OrlundoHubbard What commands did you follow to start the frontend?

You can try

`yarn install`

to install the dependencies, followed by

`yarn start`

to run the app. (This is instead of running `docker-compose up`).

If that doesn't work, it may be something specific on your machine

**Comment by knjk04** [comment]
@OrlundoHubbard How are you getting on with this?

**Comment by knjk04** [comment]
@OrlundoHubbard Unassigning due to no response

**Comment by poshi1865** [comment]
@knjk04 may I please take this up?

**Comment by knjk04** [comment]
@poshi1865 Sure, thanks again!

**Comment by poshi1865** [comment]
![Read1](https://user-images.githubusercontent.com/63964405/155008396-1e1a8a83-0451-4c89-914b-a4098edd9193.png)
![Read2](https://user-images.githubusercontent.com/63964405/155008426-2a64bab9-e770-474b-995c-6043af3517f0.png)

@knjk04 do these look alright?

**Comment by knjk04** [comment]
![image](https://user-images.githubusercontent.com/11173328/155081428-41701002-636d-4ab6-8afc-abbabc8b48b8.png)

@poshi1865 It looks good so far! Is there a way to ensure the bubble always aligns with the top of the shelf name (see the above picture)?

**Comment by poshi1865** [comment]
@knjk04 Do you mean that the bottom of the shelf name should align with the bottom of the bubble? Or should there be an equal amount of "bubble" on the top and bottom of the grid lines?

**Comment by poshi1865** [comment]
![1 px](https://user-images.githubusercontent.com/63964405/155089216-569f8395-5bf6-48a9-9094-f7dc6c2a8c90.png)

@knjk04 Maybe this is better?

**Comment by knjk04** [comment]
> @knjk04 Maybe this is better?

I agree, that looks good. Thanks!

**Comment by poshi1865** [comment]
@knjk04 I've created a pull request for this, please review and let me know if everything is fine.
