### ISSUE TITLE
Update book to author relationship

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#889]
**Describe the solution you'd like**
As a book can have multiple authors and an author can have multiple books, we should update the relationship in Book.java to be many-to-many (a bridge table is also needed). You should also ensure that the fetch type is still lazy and we avoid lazy initialisation exceptions.

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Provide us with an estimate on how long you think it will take you to complete
- Branch from `main` and set `main` as the destination branch in your pull request

If you need help with anything, we'll be happy to help you over a [GitHub Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) or our [Slack workspace](https://teambookproject.slack.com/join/shared_invite/zt-punc8os7-Iz9PTCAkYcO_0S~XwtO5_A#/shared-invite/email)

**Comment by jaymeriegel** [comment]
Heey @knjk04,
I would like to work on this issue!

**Comment by knjk04** [comment]
Hi @jaymeriegel, how are you getting on with this?

**Comment by jaymeriegel** [comment]
Hello @knjk04, sorry for not answering, I had some issues. This week I will finish the task!

**Comment by knjk04** [comment]
@jaymeriegel No matter, let us know if you need help with anything!

**Comment by jaymeriegel** [comment]
Hey, @knjk04

Dude, unfortunately I'm going to need to uncompromise the issue. We are in a turbulent time in my company and I'm completely out of time. I apologize for what happened.

**Comment by knjk04** [comment]
Hi @jaymeriegel, that's fine. Thanks for letting us know

**Comment by jbezems** [comment]
I would like to work on this issue if it is no longer taken!

**Comment by knjk04** [comment]
@jbezems Thanks, I'll assign this to you!

**Comment by jbezems** [comment]
My approach here to implement the many-to-many relationship between Book and Author reflects the many-to-many relationship between Book and Tag.

First, I will remove the attribute of author_id from CREATE_BOOK.sql. The author id will instead be referenced from the bridge table created in Book.java. Consequently, ALTER_BOOK and ALTER_BOOK_RENAME_CONSTRAINTS will have to be changed to reference the book id in the bridge table.

In Book.java, I will use the ManyToMany annotation type, and change the author variable to a set of Authors. The fetch would be set as lazy and the cascade would be set to MERGE and REFRESH. I will use the JoinTable annotation to create the bridge table, setting the join columns as the book_id and author_id, and setting these attributes both as foreign keys to reference their respective tables. 

It will also be necessary to change the book variable in Author.java to have the ManyToMany annotation (similar to in Tag.java). 

This is my first time using JPA, so I will most likely have questions as I work to understand how the Java code interfaces with the database. Please also correct me if my explanation may seem shortsighted in any way!

Thank you - I'm looking forward to contributing :)
