### ISSUE TITLE
Create statistics controller

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#890]
**Describe the solution you'd like**

We would like a statistics controller with endpoints to get 
- the most liked book
- the least liked book 
- the longest read book
- the most read genre (books that have been marked as 'read')
- average rating given to read books
- most liked genre
- average page length for read boks

If there are multiple books with the same rating or page length, take the first one

![image](https://user-images.githubusercontent.com/11173328/151544496-20ed59d3-01f9-4ee2-bd23-833453c799f8.png)

Tests are required. For instance, we need to verify that we are including books in our calculations that belong to the logged-in user, not other users.

See our classes in the [statistics package](https://github.com/Project-Books/book-project/tree/main/backend/book-app/src/main/java/com/karankumar/bookproject/statistics)

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Provide us with an estimate on how long you think it will take you to complete
- Branch from `main` and set `main` as the destination branch in your pull request

If you need help with anything, we'll be happy to help you over a [GitHub Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) or our [Slack workspace](https://teambookproject.slack.com/join/shared_invite/zt-punc8os7-Iz9PTCAkYcO_0S~XwtO5_A#/shared-invite/email)

**Comment by lrvignesh** [comment]
Hi @knjk04 - I would like to work on this!

**Comment by knjk04** [comment]
Thanks, @lrvignesh! I'll assign it to you

**Comment by knjk04** [comment]
Hi @lrvignesh, how are you getting on with this?

**Comment by lrvignesh** [comment]
Hi @knjk04, Apologies - Something came up at work. I should be able to make progress on this in this week.

**Comment by knjk04** [comment]
Hi @lrvignesh. do you have an update on this? Is there anything we can help with?

**Comment by knjk04** [comment]
@lrvignesh Unassigning at your private request

**Comment by luisya22** [comment]
It should be one endpoint or multiple endpoints?

**Comment by calnighters** [comment]
Hi, I'd like to work on this if it's available :)

**Comment by epic-problem** [comment]
Hello, if still available I am also up for impementing this!

**Comment by zantoichi** [comment]
Hello! If this is still available @knjk04 I would love working on it.

**Comment by brantheeman** [comment]
I would like to give this solution a shot

**Comment by pol-alok** [comment]
Hi @knjk04,

- I have read the requirements and believe I can make this a reality.
- If it is available please give me a chance.

Thanks,
Ravikant Pal

**Comment by chandan13tiwari** [comment]
Hi @knjk04 , I would like to work on this. I've read the code, I can make this StatisticsController to cover all the requirements.
Please let me know if you want me to assign this issue. We'll discuss the approach then.

**Comment by N-S-H** [comment]
Hi @knjk04 , I would like to work on this. Please let me know if you want to assign this issue to me

**Comment by ayushdubey755** [comment]
Hi @knjk04 Finally I found a project of my domain, can I contribute for Statistics controller. I usually work on springboot for more than a year this will be my great start in terms of open source contribution that will add some value to your project.
Assign me if you are ok so that i can start analysing the code workflow

**Comment by rremiao** [comment]
Hi @knjk04 me and a couple other fellow colleagues will be working on this issue in the next few months! Hope our final implementation suits your needs when we eventually make the merge request!

**Comment by prasad669** [comment]
Hello @knjk04 is this issue still available for contribution ?

**Comment by saket2001** [comment]
Hello @knjk04 is this issue still available for contribution ?

**Comment by chojnackia** [comment]
Hi guys, i see some of you already wanted to start or even started to work on this, so let me know if you would abandon this :D

**Comment by AdityaMY007** [comment]
Hi @knjk04,
I will be happy to work on this issue,
please let me know if this issue still available for contribution ?

**Comment by hakimamarullah** [comment]
Hi @knjk04, I would like to work on this. Is this issue still open for contribution? Thank you

**Comment by sharmasiddarth** [comment]
Is this issue still open ? I would like to work on this. Please let me know.

**Comment by bayotheman** [comment]
Hi @knjk04, I would like to work on this issue if it's still available for contribution, Thanks.

**Comment by OkoroaforKelechiDivine** [comment]
If this issue is still open, please I will like to take up on everything.

**Comment by SwethaTamatam** [comment]
Hi @knjk04, I would like to work on this issue. Please let me know if it is available. Thank you

**Comment by sambhavk** [comment]
Hi @knjk04 , I have done the backend changes [commit](https://github.com/Project-Books/book-project/compare/main...sambhavk:book-project:%23890-create-statistics-controller).

PFB one of the curl req and resp - 

Req:
`curl --location --request GET 'localhost:5000/books/most-liked' \
--header 'Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyQHVzZXIudXNlciIsImF1dGhvcml0aWVzIjpbeyJhdXRob3JpdHkiOiJVU0VSIn1dLCJpYXQiOjE2NjgyNDI2NzQsImV4cCI6MTY2ODgxNjAwMH0.ssh4HQcN3sK0bVOKt-jVwJIBuWlFdOjJvTFj0LmcxgnNb6NdI6fpf5518MfC4GNWqVeygdC-_xH9v_-hkl2Q0g'`

Resp: 
`{
    "title": "Harry Potter and the Order of Phoenix",
    "numberOfPages": 612,
    "pagesRead": 773,
    "bookGenre": [
        "Fairy tale"
    ],
    "bookFormat": null,
    "seriesPosition": 8,
    "edition": null,
    "bookRecommendedBy": "Thomas",
    "isbn": null,
    "yearOfPublication": 2001,
    "author": {
        "fullName": "Robert Galbraith"
    },
    "predefinedShelf": {
        "shelfName": "Read"
    },
    "userCreatedShelf": null,
    "tags": [
        {
            "name": "Adventure"
        }
    ],
    "publishers": [
        {
            "name": "Scholastic Corporation"
        }
    ],
    "rating": "9.5/10",
    "dateStartedReading": "2022-11-10",
    "dateFinishedReading": "2022-11-12",
    "bookReview": "Must Read Book. Really Enjoyed it"
}`

I would like to complete the remaining frontend work as well. You can assign it to me if it is available. Thank you!

**Comment by nunzioono** [comment]
Is this feature still assignable?

**Comment by chavikram** [comment]
Hii @knjk04 I would like to work on this issue . Is this still open ?

**Comment by nunzioono** [comment]
I'm waiting to work on it too @knjk04

**Comment by nunzioono** [comment]
However seems someone maybe solved it before us, at least in the comments that's what is written

**Comment by knjk04** [comment]
Hi all, apologies for the very late response in getting back to all of you.

It's great to see that so many of you were interested in working on this!

Unfortunately, I will be archiving this project as I no longer have the time to maintain it. Thank you so much for offering to work on this!
