### ISSUE TITLE
Only use email service if profile is prod

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#891]
**Describe the solution you'd like**
We only want to use the email service if the current active profile is prod, not dev (we mock this for test).

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Provide us with an estimate on how long you think it will take you to complete
- Branch from `main` and set `main` as the destination branch in your pull request

If you need help with anything, we'll be happy to help you over a [GitHub Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) or our [Slack workspace](https://teambookproject.slack.com/join/shared_invite/zt-punc8os7-Iz9PTCAkYcO_0S~XwtO5_A#/shared-invite/email)

**Comment by gabrielronei** [comment]
Hey @knjk04, can i take this one?

So for it, i'm going to create a Interface with the method to send the email and make two implementations, one is EmailService and the other is FakeEmailService and anotate with `@Profile` to make spring know which one he is going to inject.

**Comment by knjk04** [comment]
Hi @gabrielronei, 

I've updated the issue description. We can ignore the test profile because we're mocking the email service for that, so I don't think we'll need to create a fake email service.

One workaround we are using is here where we check the active environment: https://github.com/Project-Books/book-project/blob/main/backend/book-app/src/main/java/com/karankumar/bookproject/account/UserController.java#L102. However, there may be a better and cleaner approach

**Comment by gabrielronei** [comment]
Oh @knjk04, i think that i've made a mistake on my explanation, the workaround to ignore this **if(environment...)** is to use the annotation `@Profile` on EmailService, and the spring will inject only on prod mode. 
I can do a simple version for you to see and check if you approve.

**Comment by knjk04** [comment]
That sounds good, thanks. I'll assign you to this
