### ISSUE TITLE
Unable to find the ModelMapper class

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#893]
**Describe the bug**

![image](https://user-images.githubusercontent.com/11173328/151695263-b7393a04-1881-4ab6-9271-fd437eaea24d.png)

When the steps above (from the README) are followed, I get a NoClassDefFound error from ModelMapper. This results in not being able to initialise and run the main class.

![image](https://user-images.githubusercontent.com/11173328/151695246-cf0b22d3-2dc7-410a-9480-73ec34177321.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Follow approach for running the backend in the README
2. See error

**Expected behaviour**

No error and the applications runs.

**Your system**

For backend-related bugs, tell us your 
- OS: Windows 10
- which type of JDK you're running (e.g. Oracle JDK or OpenJDK)
- JDK version number (including the minor and patch version): Open JDK 11.7

**Additional context**

- Read our contributing guidelines first!
- Discuss your implementation approach with us first
- Provide us with an estimate on how long you think it will take you to complete
- Branch from main and set main as the destination branch in your pull request

Add any other context about the problem here (e.g. stack trace, branch name, commit hash, etc.).

**Comment by priya1712d** [comment]
@knjk04  
Hello! Could I help with this?

**Comment by knjk04** [comment]
Hi @priya1712d, thanks for offering to help again! I'll assign you to this
