### ISSUE TITLE
Upgrade react-scripts to 5.0.0

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#902]
**Is your feature request related to a problem? If so, please describe.**
react-scripts@4.0.1 depends on various packages that have security flaws.

**Describe the solution you'd like**
Upgrade react-scripts@4.0.1 to react-scripts@5.0.0.

There may be some breaking changes, so take a look at the [changelog](https://github.com/facebook/create-react-app/blob/main/CHANGELOG.md).

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Provide us with an estimate on how long you think it will take you to complete
- Branch from `main` and set `main` as the destination branch in your pull request

If you need help with anything, we'll be happy to help you over a [GitHub Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) or our [Slack workspace](https://teambookproject.slack.com/join/shared_invite/zt-punc8os7-Iz9PTCAkYcO_0S~XwtO5_A#/shared-invite/email)

**Comment by priya1712d** [comment]
Hello @knjk04 ! 
Could I can pick this up?

**Comment by knjk04** [comment]
Hi @priya1712d, thanks again!
