### ISSUE TITLE
Make Book to UserCreatedShelf relationship many-to-many

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#905]
**Describe the solution you'd like**
Make the [Book](https://github.com/Project-Books/book-project/blob/main/backend/book-app/src/main/java/com/karankumar/bookproject/model/Book.java) to [UserCreatedShelf](https://github.com/Project-Books/book-project/blob/main/backend/book-app/src/main/java/com/karankumar/bookproject/shelf/model/UserCreatedShelf.java) relationship many-to-many.

You should also ensure that the fetch type is still lazy and we avoid lazy initialisation exceptions.

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Provide us with an estimate on how long you think it will take you to complete
- Branch from `main` and set `main` as the destination branch in your pull request

If you need help with anything, we'll be happy to help you over a [GitHub Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) or our [Slack workspace](https://teambookproject.slack.com/join/shared_invite/zt-punc8os7-Iz9PTCAkYcO_0S~XwtO5_A#/shared-invite/email)

**Comment by brunbs** [comment]
Hi, I'd like to help with this if you still want. But I need some directions: should I fork it first then find a solution and then discuss the implementation? Or do I discuss the implementation first, get assigned to and just then fork the project?

**Comment by knjk04** [comment]
Hi @brunbs, thanks for offering to help with this.

Either is fine, but I'd recommend the former:

> fork it first then find a solution and then discuss the implementation?

The purpose of this is so that we can discuss early on whether that's the best approach (and perhaps alternative approaches that may be better) before you go off and actually implement the solution to save you time (and in case your solution is not what we were looking for).
