### ISSUE TITLE
Proxy error: Could not proxy request /api/shelf/books/read from localhost:3000 to http://localhost:8080.

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#912]
**Describe the bug**

When running the frontend in a docker container, I get a proxy error:

```
frontend-dev | Proxy error: Could not proxy request /api/shelf/books/reading from localhost:3000 to http://localhost:8080.
frontend-dev | See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).
```

Log: https://gist.github.com/knjk04/0d7e7dca7fb1394030b707a60c60580c

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the frontend using Docker (see instructions in the README)
2. Log in with the test user credentials
3. Inspect network tab
4. Go to list view
5. See error

**Expected behaviour**

200 OK API calls.

**Your system**

If it's frontend-related, tell us which 
- Browser and browser version you see the bug on
- your Node and npm versions

For backend-related bugs, tell us your 
- operating system
- which type of JDK you're running (e.g. Oracle JDK or OpenJDK)
- JDK version number (including the minor and patch version) 
- which IDE and version you're using (if relevant)

**Additional context**

- Read our contributing guidelines first!
- Discuss your implementation approach with us first
- Provide us with an estimate on how long you think it will take you to complete
- Branch from main and set main as the destination branch in your pull request

Add any other context about the problem here (e.g. stack trace, branch name, commit hash, etc.).

**Comment by priya1712d** [comment]
Hi @knjk04 
Could I work on this?
:)
