### ISSUE TITLE
Add bot to follow up on assigned issue

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#922]
**Is your feature request related to a problem? If so, please describe.**
Following up on an assigned issue 7 days after it was assigned is currently a manual process, which is tedious and error-prone (we have to remember to follow up).

**Describe the solution you'd like**
If the assigned user has not commented on the issue or created a PR within 7 days of when we assigned them to the issue, we should have a bot follow up on their progress by asking: 

> 'Hi {github username}, how are you getting on with this? If you need a hand, let us know by creating a GitHub discussion or asking on our #book-project channel on our Slack workspace'.

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Provide us with an estimate on how long you think it will take you to complete
- Branch from `main` and set `main` as the destination branch in your pull request

If you need help with anything, we'll be happy to help you over a [GitHub Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) or our [Slack workspace](https://teambookproject.slack.com/join/shared_invite/zt-punc8os7-Iz9PTCAkYcO_0S~XwtO5_A#/shared-invite/email)

**Comment by priya1712d** [comment]
Or probably this one first!

**Comment by priya1712d** [comment]
Hey @knjk04 !
Do you recommend any framework for this?

**Comment by knjk04** [comment]
Hi @priya1712d, there are some good [Probot](https://probot.github.io/) apps that may work. One option I found was this reminder bot: https://probot.github.io/apps/reminders/

**Comment by priya1712d** [comment]
Yes, sure! feel free to tag me to other interesting backend issues or new frontend features! :)

**Comment by knjk04** [comment]
Added
