### ISSUE TITLE
Add bot to unassign issue

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#923]
**Is your feature request related to a problem? If so, please describe.**
 Unassigning an unresponsive assignee from an issue 7 days after we have followed up is currently a manual process, which is tedious and error-prone (we have to remember to unassign them).

**Describe the solution you'd like**
7 days after our bot (see #922) has followed up on the issue, if we have still not heard back from the assigned user on the issue or by them creating a PR, we should unassign them from the issue with the message:

> Hi {GitHub username}, in line with our contributing guidelines, as we have not heard back from you 7 days after following up, we will assign you from this issue.

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Provide us with an estimate on how long you think it will take you to complete
- Branch from `main` and set `main` as the destination branch in your pull request

If you need help with anything, we'll be happy to help you over a [GitHub Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) or our [Slack workspace](https://teambookproject.slack.com/join/shared_invite/zt-punc8os7-Iz9PTCAkYcO_0S~XwtO5_A#/shared-invite/email)

**Comment by priya1712d** [comment]
Could I work on this?
