### ISSUE TITLE
Create endpoint to check if email exists

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#925]
**Is your feature request related to a problem? If so, please describe.**
When we log in on the frontend, we ask for the email and password together. If we ask for them separately, we can provide a nicer user experience by letting the user know which (out of email and password) field they typed in was incorrect

**Describe the solution you'd like**
Create an endpoint in the [UserController](https://github.com/Project-Books/book-project/blob/main/backend/book-app/src/main/java/com/karankumar/bookproject/account/controller/UserController.java) that uses our [service method](https://github.com/Project-Books/book-project/blob/main/backend/book-app/src/main/java/com/karankumar/bookproject/account/service/UserService.java#L138) to see whether the email exists.

If the email does not exist, we should return a 404. If the email does exist, we can return 200 OK. This should be a GET method.

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Provide us with an estimate on how long you think it will take you to complete
- Branch from `main` and set `main` as the destination branch in your pull request

If you need help with anything, we'll be happy to help you over a [GitHub Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) or our [Slack workspace](https://teambookproject.slack.com/join/shared_invite/zt-punc8os7-Iz9PTCAkYcO_0S~XwtO5_A#/shared-invite/email)

**Comment by kuruvasatya** [comment]
Hi @knjk04, I would love to work on this please assign me this issue.

**Comment by knjk04** [comment]
Hi @kuruvasatya, thanks!

**Comment by kuruvasatya** [comment]
hey @knjk04, Thanks for assigning this to me, I hope I have completed the task, I raised a PR, please review it and let me know if any thing else is needed/changed.
