### ISSUE TITLE
Move model package inside book package

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#927]
**Describe the solution you'd like**
Move our [model ](https://github.com/Project-Books/book-project/tree/main/backend/book-app/src/main/java/com/karankumar/bookproject/model) package inside the [book](https://github.com/Project-Books/book-project/tree/main/backend/book-app/src/main/java/com/karankumar/bookproject/book) package.

You may encounter a query syntax exception (see https://gist.github.com/knjk04/f7f4c6b875eb2ef10e4bd7cadd20aa8b).

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Provide us with an estimate on how long you think it will take you to complete
- Branch from `main` and set `main` as the destination branch in your pull request

If you need help with anything, we'll be happy to help you over a [GitHub Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) or our [Slack workspace](https://teambookproject.slack.com/join/shared_invite/zt-punc8os7-Iz9PTCAkYcO_0S~XwtO5_A#/shared-invite/email)

**Comment by TaeyeonRoyce** [comment]
Hi, I'm a student who studies programming(Java, Spring).
I'm recently finding open source to contribute and I want to do about this issue.
I might be insufficient to solve this issue, but I want to fork this project and analyze codes to try it.
I already read contribution docs. Please let me try this issue.

**Comment by TaeyeonRoyce** [comment]
Hi @knjk04, I solved this issue (move model package inside book package) and I'd like to say about how I solved this.
First, move model package inside book package. As you noticed, it causes "com.karankumar.bookproject.model.PredefinedShelfName.READ".
So I fixed JPA query where in method "findReadShelf2" which approaches to PredefinedShelfName.

After work, I run all test and passed except for the test that failed in the main branch. (ReadingGoalControllerIntegrationTest)

As you know, all classes that imported model package have been changed.
I also bring back some setting files such as "application-dev.properties" and "docker-compose.yml".

Please check my PR and let me know if I missed or did wrong.
Thank you for assigned me.
