### ISSUE TITLE
'Connecting to Backend' link is broken in documents

### ISSUE THREAD

**Issue by priya1712d** [Project-Books/book-project#935]
**Describe the bug**

'Connecting to Backend' link is broken in documents

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to ReadMe.md
2. Click on _Connecting to Backend_

**Expected behaviour**

It should open this link https://project-books.github.io/docs/development/how-to/backend-postman/

**Screenshots**

<img width="1234" alt="Screenshot 2022-02-17 at 21 10 22" src="https://user-images.githubusercontent.com/29104924/154562961-84ede765-8e34-42de-a931-a86085a74bad.png">

**Additional context**

- Read our contributing guidelines first!
- Discuss your implementation approach with us first
- Provide us with an estimate on how long you think it will take you to complete
- Branch from main and set main as the destination branch in your pull request

Add any other context about the problem here (e.g. stack trace, branch name, commit hash, etc.).

**Comment by TaeyeonRoyce** [comment]
I also encounter same error.
Link from README to contributing document also has same errors.

You can approach to link after some url changes.

Before : 
https://project-books.github.io/docs/development/how-to/backend-postman/

After :
https://project-books.github.io/development/how-to/backend-postman/

I'm just a student and my opinion is not official.

**Comment by knjk04** [comment]
Thanks @priya1712d and @TaeyeonRoyce! Would one of you like to submit a PR for this?
