### ISSUE TITLE
Content is dripping out of tiles in List view 

### ISSUE THREAD

**Issue by priya1712d** [Project-Books/book-project#936]
**Describe the bug**
Content is dripping out of tiles in List view

**To Reproduce**
1. Log in to the application
2. Go to list view

**Expected behavior**
Name of the book should be visible properly

**Screenshots**
<img width="1255" alt="Screenshot 2022-02-17 at 21 41 09" src="https://user-images.githubusercontent.com/29104924/154567498-7006fce4-7aaa-4f59-b1e1-e3b145466750.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 98.0

- Be sure to read our contributing guidelines
- Discuss your implementation approach with us first
- If you need help with anything, feel free to create a new [GitHub Q&A discussion](https://github.com/Project-Books/books-api/discussions/categories/q-a) or on our [Slack workspace](https://join.slack.com/t/teambookproject/shared_invite/zt-punc8os7-Iz9PTCAkYcO_0S~XwtO5_A)

**Comment by knjk04** [comment]
Hi @priya1712d, thanks for bringing this up!

We have an issue for this: #886
