### ISSUE TITLE
Contributing.md has broken link

### ISSUE THREAD

**Issue by PalAditya** [Project-Books/book-project#939]
**Describe the bug**

The link to Contribution documentation in [Contributing.md](https://github.com/Project-Books/book-project/blob/main/CONTRIBUTING.md) seems broken. It points to https://project-books.github.io/docs/development/contributing/ but should probably point to https://project-books.github.io/development/contributing/

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to  [Contributing.md](https://github.com/Project-Books/book-project/blob/main/CONTRIBUTING.md) and click on the hyperlink
2. Observe 404 page

**Expected behaviour**

Should see the proper docs

**Screenshots**

![404](https://user-images.githubusercontent.com/25523604/154808489-7091c929-1f6d-43f2-a839-e4faea246be2.PNG)
![200](https://user-images.githubusercontent.com/25523604/154808492-869d9575-9b8e-4ab0-af79-6536db2c658b.PNG)

P.S: Happy to fix this, unless I'm missing a reason why this was left untouched for a while 😄

**Comment by PalAditya** [comment]
Sorry, appears to be a duplicate of https://github.com/Project-Books/book-project/issues/935. Closing in favour of that

**Comment by knjk04** [comment]
Hi @PalAditya, thanks for noticing this and bringing this up! I've assigned you to this (the other issue is to do with a different broken link -- we've recently changed lots of links!)
