### ISSUE TITLE
Frontend not able to connect to talk to backend

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#947]
**Describe the bug**

I am able to log in on the frontend, but the other endpoints are failing. Error message:

```
Syntax error: JSON.parse: unexpected character at line 1 column 1 of JSON data
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the app
2. Log in with the test user credentials (you can find the credentials in the README)
3. See the error

**Expected behaviour**

A list of books should show in the shelf and list view.

**Screenshots**

![image](https://user-images.githubusercontent.com/11173328/154216277-09064738-5672-49c8-9a6c-39bf1c3718cb.png)

**Your system**

Tell us your:
- OS: Windows 10 

If it's frontend-related, tell us which 
- Browser and browser version you see the bug on: Firefox 97.0.1

**Additional context**

- Read our contributing guidelines first!
- Discuss your implementation approach with us first
- Provide us with an estimate on how long you think it will take you to complete
- Branch from main and set main as the destination branch in your pull request

Add any other context about the problem here (e.g. stack trace, branch name, commit hash, etc.).

**Comment by priya1712d** [comment]
yes! feel free to assign this to me
