### ISSUE TITLE
Set up eslint pre-commit hook

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#957]
**Is your feature request related to a problem? If so, please describe.**
Not running eslint before pushing can lead to a failed linter build.

**Describe the solution you'd like**
Set up a [pre-commit](https://pre-commit.com/) hook so that it triggers eslint to run whenever we try to commit one of the frontend files (`.ts`, `.js`, etc.).

See https://github.com/pre-commit/mirrors-eslint

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Provide us with an estimate on how long you think it will take you to complete
- Branch from `main` and set `main` as the destination branch in your pull request

If you need help with anything, we'll be happy to help you over a [GitHub Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) or our [Slack workspace](https://teambookproject.slack.com/join/shared_invite/zt-punc8os7-Iz9PTCAkYcO_0S~XwtO5_A#/shared-invite/email)

**Comment by barnes-c** [comment]
Hey @knjk04, I would like to take care of this issue.

I've already read the contributing guidelines.

My approach would be to install pre-commit and add a '.pre-commit-config.yaml' to the frontend.
Configure the yaml files so it matches the style guide.

An estimate on how long I would need is Monday the 14th

**Comment by knjk04** [comment]
Hi @barnes-c, thanks for offering to help with this! I'll assign it to you

**Comment by knjk04** [comment]
Hi @barnes-c, how are you getting on with this?

**Comment by knjk04** [comment]
Hi @barnes-c, as we have not heard back from you, we will unassign you (as per our contributing guidelines)
