### ISSUE TITLE
Use sh instead of bash

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#972]
We currently [add bash](https://github.com/Project-Books/book-project/blob/main/frontend/Dockerfile#L16) to our Alpine-based image as we use it in our [frontend start script](https://github.com/Project-Books/book-project/blob/main/frontend/start.sh#L1).

So that we don't increase the size considerably, use `sh` instead of `bash`

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Provide us with an estimate on how long you think it will take you to complete
- Branch from `main` and set `main` as the destination branch in your pull request

If you need help with anything, we'll be happy to help you over a [GitHub Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) or our [Slack workspace](https://teambookproject.slack.com/join/shared_invite/zt-punc8os7-Iz9PTCAkYcO_0S~XwtO5_A#/shared-invite/email)

**Comment by akshathphillips** [comment]
Hello, I'd like to work on this!

**Comment by divyeshio** [comment]
Can you please assign this issue to me? I have already opened a PR #996  for it.

**Comment by knjk04** [comment]
Hi @divyeshio,

Unfortunately, I will be archiving this project as I no longer have the time to maintain it. Thanks again!
