### ISSUE TITLE
Edit favicon icon

### ISSUE THREAD

**Issue by katherinevivianw** [Project-Books/book-project#980]
- Favicon icon is already in the project under frontend > public > favicon.ico
- Needs to be connected to the index.html file 

Implementation: 
- add a line of code underneath the title line in index.html
- estimated time: 5 minutes

**Comment by AdwitiyaMishra** [comment]
Hi @katherinevivianw, I would like to work on this issue. I'm a first time contributor so let me know if it's available. Thanks.

**Comment by Hardik27** [comment]
Hi @katherinevivianw, please do check the PR: https://github.com/Project-Books/book-project/pull/981 for the above fix.

**Comment by knjk04** [comment]
Hi all, apologies for the very late response in getting back to you.

Unfortunately, I will be archiving this project as I no longer have the time to maintain it. Thanks again for your interest in working on the favicon!
