### ISSUE TITLE
Book Publisher Column. According to me a column with Book Publisher also help us in finding and updating book .

### ISSUE THREAD

**Issue by MauryaTech22** [Project-Books/book-project#983]
**Is your feature request related to a problem? If so, please describe.**

**Describe the solution you'd like**

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Provide us with an estimate on how long you think it will take you to complete
- Branch from `main` and set `main` as the destination branch in your pull request

If you need help with anything, we'll be happy to help you over a [GitHub Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) or our [Slack workspace](https://teambookproject.slack.com/join/shared_invite/zt-punc8os7-Iz9PTCAkYcO_0S~XwtO5_A#/shared-invite/email)

**Comment by SwethaTamatam** [comment]
Hi @MauryaTech22 I would like to work on this issue.

**Comment by knjk04** [comment]
Hi @MauryaTech22, apologies for the very late response in getting back to you.

Unfortunately, I will be archiving this project as I no longer have the time to maintain it. Thanks again!
