### ISSUE TITLE
Improve README.md Formatting and Readability

### ISSUE THREAD

**Issue by dyannya** [Project-Books/book-project#991]
The **README.md**, although greatly detailed, seems to be too cluttered and crowded at first glance, which makes it hard for some users and contributors to navigate / skim through.  

Some links are also not working as intended, such as the **“open collective | donate”** button under the **Donations** section. It currently directs the user to a blank page displaying the button image and not the website where one may donate to the project.

I am open to making this contribution, but will need assistance in terms of which sections and details would need more emphasis based on preference.

**Comment by vishalsingh2972** [comment]
@dyannya is this issue still open? could you please assign it to me if it is open. thanks!

**Comment by knjk04** [comment]
Hi both. Apologies for the very late response in getting back to you.

Unfortunately, I will be archiving this project as I no longer have the time to maintain it. Thanks again!  - Unfortunately, I will be archiving this project as I no longer have the time to maintain it. Thank you so much for offering to work on this!
